// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class BritishRoadNames
    {
        internal static readonly string[] GeneralBaseNames =
        {
            // Bäume, Hecken und Pflanzen
            "Alder",
            "Apple",
            "Ash",
            "Beech",
            "Birch",
            "Blackthorn",
            "Bluebell",
            "Bramble",
            "Cedar",
            "Chestnut",
            "Elder",
            "Elm",
            "Foxglove",
            "Hawthorn",
            "Hazel",
            "Heather",
            "Holly",
            "Hornbeam",
            "Ivy",
            "Laburnum",
            "Laurel",
            "Lavender",
            "Lilac",
            "Lime",
            "Maple",
            "Oak",
            "Pine",
            "Poplar",
            "Primrose",
            "Rose",
            "Rowan",
            "Sycamore",
            "Walnut",
            "Willow",
            "Wisteria",
            "Yew",

            // Königshaus, Adel und historische Namen
            "Albert",
            "Alexandra",
            "Anne",
            "Arthur",
            "Beatrice",
            "Charles",
            "Charlotte",
            "Churchill",
            "Clarence",
            "Crown",
            "Duke",
            "Duchess",
            "Edward",
            "Elizabeth",
            "George",
            "Hanover",
            "Henry",
            "James",
            "Jubilee",
            "King",
            "Mary",
            "Nelson",
            "Prince",
            "Princess",
            "Queen",
            "Regent",
            "Royal",
            "Victoria",
            "Wellington",
            "Windsor",

            // Orte, Grafschaften und Regionen
            "Abbey",
            "Balmoral",
            "Bath",
            "Bedford",
            "Berkshire",
            "Bristol",
            "Buckingham",
            "Cambridge",
            "Canterbury",
            "Chatsworth",
            "Chelsea",
            "Chester",
            "Cornwall",
            "Cumberland",
            "Devon",
            "Dover",
            "Durham",
            "Edinburgh",
            "Essex",
            "Exeter",
            "Gloucester",
            "Hampton",
            "Hampstead",
            "Kensington",
            "Kent",
            "Lancaster",
            "Leicester",
            "London",
            "Manchester",
            "Norfolk",
            "Nottingham",
            "Oxford",
            "Pembroke",
            "Plymouth",
            "Richmond",
            "Salisbury",
            "Somerset",
            "Surrey",
            "Sussex",
            "Warwick",
            "Westminster",
            "Winchester",
            "Worcester",
            "York",

            // Typische britische Bezeichnungen
            "Bridge",
            "Castle",
            "Chapel",
            "Church",
            "College",
            "Common",
            "Cross",
            "Dean",
            "Glebe",
            "Grange",
            "Green",
            "Hall",
            "Hill",
            "Lodge",
            "Manor",
            "Market",
            "Meadow",
            "Mill",
            "Orchard",
            "Park",
            "Priory",
            "Railway",
            "Rectory",
            "Riverside",
            "School",
            "Stables",
            "Station",
            "Theatre",
            "Town",
            "Trinity",
            "Village",
            "Water",
            "Wharf",
            "Woodland",

            // Landschaft und ländliche Begriffe
            "Beacon",
            "Brook",
            "Brookfield",
            "Burnside",
            "Dale",
            "Downs",
            "Glen",
            "Heath",
            "Highfield",
            "Hillcrest",
            "Leys",
            "Marsh",
            "Moor",
            "Moorland",
            "Northfield",
            "Riverbank",
            "Southfield",
            "Springfield",
            "Stonebridge",
            "The Dales",
            "Vale",
            "Waterside",
            "Westfield",
            "Eastfield",
            "Woodside"
        };

        internal static readonly string[] DirtBaseNames =
        {
            // Pflanzen, Hecken und Gehölze
            "Ash",
            "Beech",
            "Birch",
            "Blackthorn",
            "Bluebell",
            "Bramble",
            "Bracken",
            "Elder",
            "Foxglove",
            "Hawthorn",
            "Hazel",
            "Heather",
            "Holly",
            "Oak",
            "Primrose",
            "Rowan",
            "Willow",
            "Yew",

            // Tiere und ländliche Namen
            "Badger",
            "Deer",
            "Fox",
            "Hare",
            "Hedgehog",
            "Lark",
            "Otter",
            "Owl",
            "Pheasant",
            "Robin",
            "Shepherd's",
            "Squirrel",
            "Stag",
            "Swan",

            // Landschaft, Landwirtschaft und Wege
            "Brook",
            "Coppice",
            "Downland",
            "Farm",
            "Forest",
            "Green Lane",
            "Heath",
            "High Moor",
            "Hollow",
            "Low Moor",
            "Marsh",
            "Meadow",
            "Mill",
            "Moorland",
            "Old Farm",
            "Old Mill",
            "Old Quarry",
            "Orchard",
            "Quarry",
            "River",
            "Ridge",
            "Stone",
            "The Dales",
            "Windmill",
            "Wood",
            "Woodland"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            // Historische, königliche und innerstädtische Namen
            "Abbey",
            "Albert",
            "Angel",
            "Bell",
            "Blackfriars",
            "Brewer",
            "Castle",
            "Chapel",
            "Church",
            "Clarence",
            "Coach",
            "Cooper",
            "Crown",
            "Duke",
            "Falcon",
            "Fisher",
            "Friar",
            "Garden",
            "George",
            "Guildhall",
            "King",
            "Lion",
            "Market",
            "Merchant",
            "Mill",
            "Queen",
            "Regent",
            "Royal",
            "Rose",
            "Station",
            "Temple",
            "Victoria",
            "Wellington",
            "Wharf",
            "White Hart",
            "Windsor",
            "York",

            // Bäume und Pflanzen
            "Ash",
            "Elm",
            "Holly",
            "Ivy",
            "Laurel",
            "Oak",
            "Willow",
            "Yew"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "The Beeches",
            "The Brambles",
            "The Cedars",
            "The Close",
            "The Coppice",
            "The Crescent",
            "The Dene",
            "The Gardens",
            "The Glade",
            "The Green",
            "The Grove",
            "The Laurels",
            "The Limes",
            "The Meadows",
            "The Mews",
            "The Oaks",
            "The Paddock",
            "The Spinney",
            "The Willows",
            "The Woodlands"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Bridge Street",
            "Church Walk",
            "High Street",
            "London Road",
            "Main Street",
            "Market Place",
            "Mill Lane",
            "Old Road",
            "Station Approach",
            "The Broadway",
            "The Green",
            "The Parade",
            "The Square",
            "The Street",
            "Town Street",
            "Water Lane"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Eastway",
            "Kingsway",
            "Queensway",
            "Westway",
            "The Avenue",
            "The Causeway",
            "The Embankment",
            "The Esplanade",
            "The Parkway",
            "The Promenade"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Atlantic Highway",
            "Bath Road",
            "Bristol Road",
            "Coast Road",
            "Devon Expressway",
            "East Cross Route",
            "East Lancashire Road",
            "Ermine Street",
            "Fosse Way",
            "Great Cambridge Road",
            "Great Eastern Road",
            "Great North Road",
            "Great South West Road",
            "Great West Road",
            "Great Western Road",
            "Heads of the Valleys Road",
            "Highland Route",
            "London Road",
            "Mersey Gateway",
            "Moorland Route",
            "North Circular Road",
            "Northern Route",
            "Old Kent Road",
            "Oxford Road",
            "Severn Way",
            "South Circular Road",
            "Southern Route",
            "Thames Gateway",
            "Wales Way",
            "Watling Street",
            "Westway"
        };

        internal static readonly string[] DirtSuffixes =
        {
            "Track",
            "Track",
            "Lane",
            "Lane",
            "Byway",
            "Path",
            "Bridleway",
            "Drove",
            "Drift",
            "Greenway",
            "Way"
        };

        internal static readonly string[] AlleySuffixes =
        {
            "Mews",
            "Mews",
            "Passage",
            "Yard",
            "Alley",
            "Court",
            "Row",
            "Walk",
            "Wynd",
            "Arcade"
        };

        internal static readonly string[] ResidentialSuffixes =
        {
            "Close",
            "Close",
            "Crescent",
            "Court",
            "Gardens",
            "Grove",
            "Lane",
            "Mews",
            "Place",
            "Rise",
            "Terrace",
            "View",
            "Walk",
            "Drive",
            "End",
            "Green",
            "Heights",
            "Mead",
            "Park",
            "Reach",
            "Row",
            "Square",
            "Vale",
            "Villas",
            "Wood"
        };

        internal static readonly string[] StandardSuffixes =
        {
            "Road",
            "Road",
            "Street",
            "Street",
            "Lane",
            "Drive",
            "Way",
            "Hill",
            "Green",
            "Row",
            "Walk",
            "Place",
            "Approach"
        };

        internal static readonly string[] AvenueSuffixes =
        {
            "Avenue",
            "Avenue",
            "Way",
            "Road",
            "Parade",
            "Causeway",
            "Parkway",
            "Embankment",
            "Esplanade",
            "Promenade"
        };

    }
}
