// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class DutchRoadNames
    {
        internal static readonly string[] DirtBaseNames =
        {
            "Bos",
            "Heide",
            "Duin",
            "Polder",
            "Veen",
            "Zand",
            "Klei",
            "Akker",
            "Veld",
            "Weide",
            "Dijk",
            "Water",
            "Meer",
            "Rivier",
            "Beek",
            "Kanaal",
            "Molen",
            "Boerderij",
            "Hoeve",
            "Kerk",
            "Wilgen",
            "Eiken",
            "Beuken",
            "Berken",
            "Linden",
            "Elzen",
            "Populieren",
            "Esdoorn",
            "Kastanje",
            "Dennen",
            "Vossen",
            "Herten",
            "Reeën",
            "Ooievaar",
            "Reiger",
            "Zwaluw",
            "Kievit",
            "Merel",
            "Haas",
            "Konijn",
            "Noorder",
            "Zuider",
            "Ooster",
            "Wester",
            "Groene",
            "Oude",
            "Nieuwe",
            "Lage",
            "Hoge",

            "Riet",
            "Kwelder",
            "Sloot",
            "Wetering",
            "Kreek",
            "Lariks",
            "Es",
            "Meidoorn",
            "Hazelaar",
            "Hulst",
            "Brem",
            "Vlier",
            "Koren",
            "Graan",
            "Klaver",
            "Boterbloem",
            "Madelief",
            "Zuring",
            "Distel",
            "Vogel",
            "Grutto",
            "Lepelaar",
            "Fuut",
            "Eend",
            "Gans",
            "Zwaan",
            "Buizerd",
            "Sperwer",
            "Das",
            "Bever",
            "Otter",
            "Eekhoorn",
            "Marter",
            "Noordzee",
            "Wadden",
            "Veluwe",
            "Drenthe",
            "Twente",
            "Betuwe",
            "Peel",
            "Kempen",
            "Biesbosch",
            "Delta",
            "Drecht",
            "Waarden",
            "Uiterwaard",
            "Kamp",
            "Erf",
            "Dorp",
        };

        internal static readonly string[] DirtSuffixes =
        {
            "weg",
            "pad",
            "dijk",
            "laan",
            "kade",

            "route",
            "dreef",
            "baan",
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Oude Dijk",
            "Nieuwe Dijk",
            "Groene Dijk",
            "Zeedijk",
            "Rivierdijk",
            "Polderweg",
            "Bosweg",
            "Heideweg",
            "Duinweg",
            "Zandweg",
            "Kleiweg",
            "Veenweg",
            "Molenweg",
            "Kerkpad",
            "Bospad",
            "Jaagpad",
            "Kwelderweg",
            "Hooidijk",
            "Tiendweg",
            "Ringdijk",
            "Noorderdijk",
            "Zuiderdijk",
            "Westerdijk",
            "Oosterdijk",
            "Kanaaldijk",
            "Veendijk",
            "Weteringpad",
            "Schapendijk",
            "Boerenweg",
            "Landweg",
            "Veldweg",
            "Akkerweg",
            "Weideweg",
            "Hooiweg",
            "Rietweg",
            "Kadeweg",
            "Slootweg",
            "Waterweg",
            "Dennenpad",
            "Eikenpad",
            "Lindenpad",
            "Berkenpad"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "Kerk",
            "Markt",
            "Molen",
            "Haven",
            "Gracht",
            "Brug",
            "Poort",
            "Toren",
            "Klooster",
            "School",
            "Nieuw",
            "Oud",
            "Kleine",
            "Lange",
            "Korte",
            "Smalle",
            "Grote",
            "Vis",
            "Bakker",
            "Brouwer",
            "Kuiper",
            "Schipper",
            "Wever",
            "Timmerman",
            "Schoenmaker",
            "Slager",
            "Koopman",
            "Koren",
            "Kaas",
            "Vlees",
            "Hout",
            "Steen",
            "Zilver",
            "Goud",
            "Rozen",
            "Tulpen",
            "Lelies",
            "Viooltjes",
            "Linden",
            "Eiken",
            "Prinsen",
            "Keizers",
            "Heren",

            "Raadhuis",
            "Stadhuis",
            "Waag",
            "Vismarkt",
            "Korenmarkt",
            "Kerkhof",
            "Kapel",
            "Abdij",
            "Vest",
            "Wal",
            "Kade",
            "Sluis",
            "Werf",
            "Dok",
            "Schans",
            "Bolwerk",
            "Burcht",
            "Slot",
            "Gasthuis",
            "Weeshuis",
            "Gilde",
            "Koopmans",
            "Schippers",
            "Vissers",
            "Bakkers",
            "Slagers",
            "Smids",
            "Touwslagers",
            "Leerlooiers",
            "Pottenbakkers",
            "Metselaars",
            "Kleermakers",
            "Kruiden",
            "Bloemen",
            "Appel",
            "Peren",
            "Kersen",
            "Noten",
            "Druiven",
            "Kruis",
            "Sint",
            "Oranje",
            "Prins",
            "Koning",
            "Koningin",
            "Graaf",
            "Burgemeester",
        };

        internal static readonly string[] AlleySuffixes =
        {
            "straat",
            "steeg",
            "gang",
            "hof",
            "pad",
            "kade",
            "gracht",

            "poort",
            "wal",
            "erf",
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Damrak",
            "Rokin",
            "Kalverstraat",
            "Leidsestraat",
            "Utrechtsestraat",
            "Reguliersbreestraat",
            "Nieuwezijds Voorburgwal",
            "Oudezijds Voorburgwal",
            "Prinsengracht",
            "Keizersgracht",
            "Herengracht",
            "Singel",
            "Vijzelstraat",
            "Weteringschans",
            "Warmoesstraat",
            "Zeedijk",
            "Nes",
            "Spuistraat",
            "Haarlemmerdijk",
            "Haarlemmerstraat",
            "Jodenbreestraat",
            "Brouwersgracht",
            "Egelantiersgracht",
            "Bloemgracht",
            "Leliegracht",
            "Oudezijds Achterburgwal",
            "Nieuwezijds Kolk",
            "Kromme Waal",
            "Geldersekade",
            "Oude Hoogstraat",
            "Lange Niezel",
            "Korte Niezel",
            "Gravenstraat",
            "Sint Luciënsteeg",
            "Heisteeg",
            "Huidenstraat",
            "Runstraat",
            "Wolvenstraat",
            "Berenstraat",
            "Reestraat",
            "Hartenstraat",
            "Gasthuismolensteeg"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            "Linde",
            "Eiken",
            "Beuken",
            "Berken",
            "Wilgen",
            "Populieren",
            "Esdoorn",
            "Kastanje",
            "Acacia",
            "Iepen",
            "Elzen",
            "Dennen",
            "Rozen",
            "Tulpen",
            "Lelies",
            "Jasmijn",
            "Lavendel",
            "Viooltjes",
            "Zonnebloem",
            "Korenbloem",
            "Madelief",
            "Narcis",
            "Hyacint",
            "Merel",
            "Lijster",
            "Zwaluw",
            "Reiger",
            "Kievit",
            "Meeuw",
            "Valk",
            "Sperwer",
            "Uil",
            "Fazant",
            "Haas",
            "Konijn",
            "Vos",
            "Hert",
            "Ree",
            "Egel",
            "Park",
            "Bos",
            "Veld",
            "Weide",
            "Water",
            "Meer",
            "Beek",
            "Duin",
            "Heide",
            "Polder",
            "Zon",
            "Regenboog",
            "Morgen",
            "Avond",
            "Noorder",
            "Zuider",
            "Ooster",
            "Wester",

            "Meidoorn",
            "Hazelaar",
            "Hulst",
            "Vlier",
            "Sering",
            "Magnolia",
            "Rododendron",
            "Azalea",
            "Dahlia",
            "Iris",
            "Pioen",
            "Anjer",
            "Freesia",
            "Geranium",
            "Begonia",
            "Kamperfoelie",
            "Klaproos",
            "Boterbloem",
            "Distel",
            "Riet",
            "Bies",
            "Klaver",
            "Grutto",
            "Lepelaar",
            "Fuut",
            "Zwaan",
            "Eend",
            "Gans",
            "Nachtegaal",
            "Roodborst",
            "Specht",
            "Vink",
            "Mus",
            "Ekster",
            "Kraai",
            "Buizerd",
            "Otter",
            "Bever",
            "Das",
            "Marter",
            "Eekhoorn",
            "Vlinder",
            "Libel",
            "Bijen",
            "Hommels",
            "Maan",
            "Sterren",
            "Hemel",
            "Dageraad",
            "Schemer",
            "Lente",
            "Zomer",
            "Herfst",
            "Winter",
            "Regen",
            "Dauw",
            "Mist",
        };

        internal static readonly string[] ResidentialSuffixes =
        {
            "straat",
            "laan",
            "weg",
            "hof",
            "pad",
            "park",
            "singel",

            "dreef",
            "erf",
            "plantsoen",
            "plein",
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Lindelaan",
            "Eikenlaan",
            "Beukenlaan",
            "Berkenlaan",
            "Wilgenlaan",
            "Populierenlaan",
            "Acacialaan",
            "Kastanjelaan",
            "Rozenstraat",
            "Tulpenstraat",
            "Leliestraat",
            "Jasmijnstraat",
            "Lavendelstraat",
            "Viooltjesstraat",
            "Zonnebloemstraat",
            "Parklaan",
            "Boslaan",
            "Heidelaan",
            "Duinlaan",
            "Waterlaan",
            "Meerlaan",
            "Polderlaan",
            "Zonnehof",
            "Regenbooglaan",
            "Merelstraat",
            "Lijsterlaan",
            "Zwaluwstraat",
            "Reigerlaan",
            "Kievitstraat",
            "Fazantenlaan",
            "Hazenpad",
            "Vossenlaan",
            "Hertenlaan",
            "Reeënpad",
            "Egelantierstraat",
            "Bloemenlaan",
            "Groenelaan",
            "Veldhof",
            "Weidehof",
            "Waterhof",
            "Parkhof",
            "Boshof",
            "Zonnepark",
            "Morgenlaan",
            "Avondlaan",
            "Noorderlaan",
            "Zuiderlaan",
            "Oosterlaan",
            "Westerlaan"
        };

        internal static readonly string[] StandardBaseNames =
        {
            // Orte und Einrichtungen.
            "Kerk",
            "Dorps",
            "Markt",
            "Molen",
            "School",
            "Station",
            "Haven",
            "Kanaal",
            "Park",
            "Brug",
            "Raadhuis",
            "Stadhuis",
            "Post",
            "Museum",
            "Theater",
            "Universiteit",
            "Handel",
            "Industrie",
            "Fabriek",
            "Spoor",
            "Water",
            "Rivier",
            "Meer",
            "Polder",

            // Niederländische Persönlichkeiten und Dynastie.
            "Willem",
            "Wilhelmina",
            "Juliana",
            "Beatrix",
            "Bernhard",
            "Alexander",
            "Maurits",
            "Frederik",
            "Erasmus",
            "Spinoza",
            "Rembrandt",
            "Vermeer",
            "Van Gogh",
            "Mondriaan",
            "Escher",
            "Anne Frank",
            "Thorbecke",
            "Michiel de Ruyter",
            "Piet Hein",
            "Hugo de Groot",

            // Städte und Regionen.
            "Amsterdam",
            "Rotterdam",
            "Utrecht",
            "Den Haag",
            "Leiden",
            "Haarlem",
            "Delft",
            "Gouda",
            "Groningen",
            "Maastricht",
            "Eindhoven",
            "Tilburg",
            "Breda",
            "Arnhem",
            "Nijmegen",
            "Zwolle",
            "Deventer",
            "Alkmaar",
            "Friesland",
            "Zeeland",
            "Brabant",
            "Limburg",
            "Holland",

            "Hoofd",
            "Centrum",
            "Gemeente",
            "Burgemeester",
            "Koning",
            "Koningin",
            "Prins",
            "Oranje",
            "Republiek",
            "Vrijheid",
            "Vrede",
            "Bevrijding",
            "Herdenking",
            "Veteranen",
            "Europa",
            "Benelux",
            "Handels",
            "Koopmans",
            "Scheepvaart",
            "Werf",
            "Dok",
            "Sluis",
            "Dijk",
            "Plein",
            "Boulevard",
            "Ring",
            "Rand",
            "Binnen",
            "Buiten",
            "Noord",
            "Zuid",
            "Oost",
            "West",
            "Leeuwarden",
            "Assen",
            "Emmen",
            "Enschede",
            "Apeldoorn",
            "Amersfoort",
            "Hilversum",
            "Almere",
            "Lelystad",
            "Middelburg",
            "Vlissingen",
            "Dordrecht",
            "Schiedam",
            "Vlaardingen",
            "Zoetermeer",
            "Amstelveen",
            "Zaandam",
            "Hoorn",
            "Purmerend",
            "Den Bosch",
            "Roermond",
            "Venlo",
            "Sittard",
            "Heerlen",
            "Helmond",
            "Roosendaal",
            "Bergen op Zoom",
        };

        internal static readonly string[] StandardSuffixes =
        {
            "straat",
            "weg",
            "laan",
            "singel",
            "kade",
            "dijk",

            "baan",
            "dreef",
            "boulevard",
            "plein",
        };

        internal static readonly string[] StandardSpecialNames =
        {
            // Amsterdam.
            "Damrak",
            "Rokin",
            "Kalverstraat",
            "Leidsestraat",
            "Utrechtsestraat",
            "Vijzelstraat",
            "Stadhouderskade",
            "Overtoom",
            "Weteringschans",
            "Amstelveenseweg",
            "Haarlemmerweg",
            "Middenweg",
            "Weesperstraat",
            "Ceintuurbaan",
            "Wibautstraat",

            // Rotterdam.
            "Coolsingel",
            "Blaak",
            "Weena",
            "Westblaak",
            "Schiedamsedijk",
            "Maasboulevard",
            "Beukelsdijk",
            "Bergweg",
            "Nieuwe Binnenweg",
            "Oude Binnenweg",

            // Den Haag.
            "Lange Voorhout",
            "Prinsegracht",
            "Spui",
            "Bezuidenhoutseweg",
            "Laan van Meerdervoort",
            "Javastraat",
            "Kneuterdijk",
            "Rijswijkseweg",

            // Utrecht.
            "Oudegracht",
            "Nieuwegracht",
            "Maliebaan",
            "Amsterdamsestraatweg",
            "Biltstraat",
            "Catharijnesingel",

            "Stationsweg",
            "Stationsstraat",
            "Dorpsstraat",
            "Kerkstraat",
            "Molenstraat",
            "Schoolstraat",
            "Havenstraat",
            "Marktstraat",
            "Hoofdstraat",
            "Voorstraat",
            "Achterstraat",
            "Nieuwstraat",
            "Oudestraat",
            "Kerkweg",
            "Kanaalweg",
            "Rivierdijk",
            "Westerdijk",
            "Oosterdijk",
            "Noorderweg",
            "Zuiderweg",
            "Raadhuisstraat",
            "Wilhelminastraat",
            "Julianastraat",
            "Beatrixstraat",
            "Oranjestraat",
            "Prins Bernhardstraat",
            "Rembrandtstraat",
            "Vermeerstraat",
            "Van Goghstraat",
            "Erasmusstraat",
            "Spinozastraat",
            "Vrijheidsstraat",
            "Bevrijdingsweg",
            "Europalaan"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "Oranje",
            "Wilhelmina",
            "Juliana",
            "Beatrix",
            "Bernhard",
            "Alexander",
            "Maurits",
            "Frederik",
            "Erasmus",
            "Rembrandt",
            "Vermeer",
            "Van Gogh",
            "Mondriaan",
            "Vrijheid",
            "Bevrijding",
            "Europa",
            "Park",
            "Stad",
            "Haven",
            "Water",
            "Kanaal",
            "Rivier",
            "Noorder",
            "Zuider",
            "Ooster",
            "Wester",
            "Linde",
            "Eiken",
            "Kastanje",
            "Acacia",

            "Koning",
            "Koningin",
            "Prins",
            "Prinses",
            "Nederland",
            "Benelux",
            "Vrede",
            "Herdenking",
            "Veteranen",
            "Universiteit",
            "Museum",
            "Theater",
            "Centrum",
            "Maas",
            "Rijn",
            "Waal",
            "IJssel",
            "Schelde",
            "Amstel",
            "Vecht",
            "Bos",
            "Duin",
            "Polder",
            "Waterfront",
            "Stadshart",
            "Stations",
        };

        internal static readonly string[] AvenueSuffixes =
        {
            "laan",
            "boulevard",
            "singel",

            "dreef",
            "baan",
            "parkway",
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Museumplein",
            "Leidseplein",
            "Rembrandtplein",
            "Waterlooplein",
            "Frederiksplein",
            "Stationsplein",
            "Marktplein",
            "Raadhuisplein",
            "Kerkplein",
            "Oranjeplein",
            "Vrijheidsplein",
            "Europaplein",
            "Wilhelminaplein",
            "Julianaplein",
            "Beatrixlaan",
            "Oranjelaan",
            "Wilhelminalaan",
            "Julianalaan",
            "Bernhardlaan",
            "Alexanderlaan",
            "Parklaan",
            "Westblaak",
            "Coolsingel",
            "Catharijnesingel",
            "Stadhouderslaan",
            "Laan van Meerdervoort",
            "Laan op Zuid",
            "Maasboulevard",
            "Westzeedijk",
            "Burgemeester de Monchyplein",
            "Plein 1944",
            "Keizer Karelplein"
        };

        internal static readonly string[] HighwayRouteNames =
        {
            "A1",
            "A2",
            "A4",
            "A5",
            "A6",
            "A7",
            "A8",
            "A9",
            "A10",
            "A12",
            "A13",
            "A15",
            "A16",
            "A17",
            "A20",
            "A22",
            "A27",
            "A28",
            "A29",
            "A30",
            "A31",
            "A32",
            "A35",
            "A37",
            "A44",
            "A50",
            "A58",
            "A59",
            "A65",
            "A67",
            "A73",
            "A74",
            "A76",
            "A77",
            "A79",
            "A200",
            "A208",
            "A256",
            "A270",
            "A325",
            "A326",
            "A348",

            "N57",
            "N201",
            "N205",
            "N207",
            "N209",
            "N210",
            "N211",
            "N225",
            "N230",
            "N247",
            "N256",
            "N270",
            "N280",
            "N300",
            "N302",
            "N305",
            "N322",
            "N325",
            "N331",
            "N355"
        };
    }
}
