// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class FrenchRoadNames
    {
        internal static readonly string[] DirtPrefixes =
        {
            "Chemin",
            "Chemin",
            "Chemin",
            "Chemin rural",
            "Chemin vicinal",
            "Chemin communal",
            "Chemin forestier",
            "Route forestière",
            "Sentier",
            "Sentier",
            "Sente",
            "Piste",
            "Piste forestière",
            "Voie communale",
            "Traverse",
            "Allée forestière",
            "Chemin d'exploitation",
            "Chemin de halage",
            "Route rurale",
            "Piste agricole",
            "Layon",
            "Drève"
        };

        internal static readonly string[] DirtBaseNames =
        {
            "des Champs",
            "des Prés",
            "des Vignes",
            "des Vergers",
            "des Pommiers",
            "des Cerisiers",
            "des Châtaigniers",
            "des Noisetiers",
            "des Peupliers",
            "des Saules",
            "des Bouleaux",
            "des Érables",
            "des Hêtres",
            "des Sapins",
            "des Pins",
            "des Genêts",
            "des Bruyères",
            "des Moulins",
            "des Fermes",
            "des Granges",
            "des Étangs",
            "des Sources",
            "des Fontaines",
            "des Roches",
            "des Crêtes",
            "des Collines",
            "des Vallons",
            "des Landes",
            "des Marais",
            "des Dunes",
            "du Bois",
            "du Grand Bois",
            "du Petit Bois",
            "du Moulin",
            "du Vieux Moulin",
            "du Château",
            "du Manoir",
            "du Prieuré",
            "du Monastère",
            "du Calvaire",
            "du Lavoir",
            "du Puits",
            "du Pont",
            "du Gué",
            "du Ruisseau",
            "du Torrent",
            "du Lac",
            "du Marais",
            "du Plateau",
            "du Coteau",
            "du Vallon",
            "du Belvédère",
            "du Haut Village",
            "du Bas Village",
            "de la Forêt",
            "de la Clairière",
            "de la Prairie",
            "de la Ferme",
            "de la Grange",
            "de la Bergerie",
            "de la Chapelle",
            "de la Croix",
            "de la Fontaine",
            "de la Source",
            "de la Rivière",
            "de la Vallée",
            "de la Colline",
            "de la Montagne",
            "de la Côte",
            "de la Plaine",
            "de la Lande",
            "de la Tourbière",
            "de la Vieille Route",
            "de l'Ancienne Gare",
            "de l'Abbaye",
            "de l'Étang",
            "de l'Orée",
            "de l'Arbre Mort",
            "aux Loups",
            "aux Renards",
            "aux Chênes",
            "aux Alouettes",
            "des Blés",
            "des Moissons",
            "des Foins",
            "des Pâtures",
            "des Prairies",
            "des Bocages",
            "des Haies",
            "des Talus",
            "des Murets",
            "des Restanques",
            "des Lavandes",
            "des Oliviers",
            "des Noyers",
            "des Aulnes",
            "des Chênes",
            "des Charmes",
            "des Sorbiers",
            "des Genévriers",
            "des Églantiers",
            "des Chardons",
            "des Chevreuils",
            "des Sangliers",
            "des Lièvres",
            "des Perdrix",
            "des Bergers",
            "des Vachers",
            "des Lavandières",
            "des Sabotiers",
            "des Carriers",
            "des Bûcherons",
            "du Vieux Chêne",
            "du Chêne Vert",
            "du Gros Chêne",
            "du Pigeonnier",
            "du Four à Pain",
            "du Menhir",
            "du Dolmen",
            "du Vieux Pont",
            "du Pont de Pierre",
            "du Petit Étang",
            "du Grand Étang",
            "du Champ de Foire",
            "du Pré Long",
            "du Pré Fleuri",
            "du Pré des Moines",
            "du Bois Brûlé",
            "du Bois des Dames",
            "du Bois des Moines",
            "du Bois de la Reine",
            "du Mont Noir",
            "du Mont Rouge",
            "du Col",
            "du Pas",
            "du Ravin",
            "du Cirque",
            "du Saut",
            "de la Garenne",
            "de la Combe",
            "de la Gorge",
            "de la Falaise",
            "de la Dune Blanche",
            "de la Grande Lande",
            "de la Petite Lande",
            "de la Scierie",
            "de la Tuilerie",
            "de la Briqueterie",
            "de la Carrière",
            "de la Sablière",
            "de la Cressonnière",
            "de la Métairie",
            "de la Bastide",
            "de la Chartreuse",
            "de la Commanderie",
            "de la Vieille Ferme",
            "de la Maison Rouge",
            "de la Maison Blanche",
            "de l'Ermitage",
            "de l'Aqueduc",
            "de l'Écluse",
            "de l'Ancien Canal",
            "de l'Ancienne Mine",
            "aux Cerfs",
            "aux Biches",
            "aux Faisans",
            "aux Perdrix",
            "aux Trois Chênes",
            "aux Quatre Vents"
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Chemin des Écoliers",
            "Chemin des Douaniers",
            "Chemin des Vignes",
            "Chemin des Vergers",
            "Chemin des Moulins",
            "Chemin des Prés",
            "Chemin des Châtaigniers",
            "Chemin des Sources",
            "Chemin des Étangs",
            "Chemin du Vieux Moulin",
            "Chemin du Lavoir",
            "Chemin du Gué",
            "Chemin du Belvédère",
            "Chemin du Haut Village",
            "Chemin du Bas Village",
            "Chemin de la Ferme",
            "Chemin de la Bergerie",
            "Chemin de la Chapelle",
            "Chemin de la Croix",
            "Chemin de la Fontaine",
            "Chemin de la Vallée",
            "Chemin de la Forêt",
            "Chemin de l'Abbaye",
            "Chemin de l'Ancienne Gare",
            "Chemin rural des Champs",
            "Chemin rural des Prés",
            "Chemin rural du Moulin",
            "Chemin vicinal du Château",
            "Chemin vicinal de la Plaine",
            "Chemin communal du Bois",
            "Chemin communal des Fermes",
            "Chemin forestier des Sapins",
            "Chemin forestier des Hêtres",
            "Chemin forestier du Grand Bois",
            "Route forestière des Crêtes",
            "Route forestière de la Clairière",
            "Route forestière du Belvédère",
            "Piste forestière des Pins",
            "Piste forestière de l'Orée",
            "Sentier des Douaniers",
            "Sentier des Crêtes",
            "Sentier des Roches",
            "Sentier du Littoral",
            "Sentier du Lac",
            "Sentier de la Cascade",
            "Sentier de la Source",
            "Sentier de la Chapelle",
            "Sente des Vignes",
            "Sente des Écoliers",
            "Sente du Moulin",
            "Traverse des Collines",
            "Traverse du Vallon",
            "Voie communale des Vergers",
            "Voie communale du Plateau",
            "Chemin des Blés",
            "Chemin des Moissons",
            "Chemin des Pâtures",
            "Chemin des Bocages",
            "Chemin des Haies",
            "Chemin des Restanques",
            "Chemin des Lavandes",
            "Chemin des Oliviers",
            "Chemin des Noyers",
            "Chemin des Genévriers",
            "Chemin des Chevreuils",
            "Chemin des Sangliers",
            "Chemin des Bergers",
            "Chemin des Lavandières",
            "Chemin du Vieux Chêne",
            "Chemin du Pigeonnier",
            "Chemin du Four à Pain",
            "Chemin du Menhir",
            "Chemin du Dolmen",
            "Chemin du Pont de Pierre",
            "Chemin du Pré Long",
            "Chemin du Bois des Moines",
            "Chemin du Col",
            "Chemin du Ravin",
            "Chemin de la Garenne",
            "Chemin de la Combe",
            "Chemin de la Falaise",
            "Chemin de la Scierie",
            "Chemin de la Tuilerie",
            "Chemin de la Carrière",
            "Chemin de la Métairie",
            "Chemin de la Bastide",
            "Chemin de la Commanderie",
            "Chemin de l'Ermitage",
            "Chemin de l'Aqueduc",
            "Chemin de l'Écluse",
            "Chemin de l'Ancien Canal",
            "Chemin d'exploitation des Prés",
            "Chemin d'exploitation des Vergers",
            "Chemin de halage du Canal",
            "Chemin de halage de la Rivière",
            "Route rurale des Hameaux",
            "Route rurale du Plateau",
            "Route rurale de la Vallée",
            "Allée forestière des Chênes",
            "Allée forestière des Hêtres",
            "Allée forestière des Sorbiers",
            "Piste agricole des Moissons",
            "Piste agricole des Vignes",
            "Piste agricole du Pré Long",
            "Layon des Chasseurs",
            "Layon des Bûcherons",
            "Layon du Grand Bois",
            "Drève des Chênes",
            "Drève des Hêtres",
            "Drève du Château",
            "Sentier des Chevreuils",
            "Sentier des Cascades",
            "Sentier du Vieux Pont",
            "Sentier du Menhir",
            "Sentier de la Combe",
            "Sente aux Loups",
            "Sente aux Renards",
            "Traverse de la Grande Lande",
            "Voie communale de la Maison Rouge"
        };

        internal static readonly string[] AlleyPrefixes =
        {
            "Impasse",
            "Impasse",
            "Impasse",
            "Passage",
            "Passage",
            "Ruelle",
            "Ruelle",
            "Venelle",
            "Cour",
            "Petite Rue",
            "Traverse",
            "Montée",
            "Descente",
            "Rampe",
            "Escalier",
            "Sente",
            "Cité",
            "Courée",
            "Galerie",
            "Allée",
            "Calade"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "de l'Arche",
            "de l'Horloge",
            "de l'Église",
            "de la Chapelle",
            "de la Tour",
            "des Remparts",
            "du Château",
            "du Vieux Château",
            "du Donjon",
            "du Clocher",
            "du Presbytère",
            "du Prieuré",
            "du Couvent",
            "du Marché",
            "des Halles",
            "des Tanneurs",
            "des Tisserands",
            "des Forgerons",
            "des Potiers",
            "des Verriers",
            "des Boulangers",
            "des Orfèvres",
            "des Cordeliers",
            "des Mariniers",
            "des Pêcheurs",
            "des Artisans",
            "des Écoles",
            "des Jardins",
            "des Roses",
            "des Lilas",
            "des Glycines",
            "des Violettes",
            "des Colombes",
            "des Hirondelles",
            "du Chat",
            "du Coq",
            "du Lion",
            "du Cerf",
            "du Renard",
            "du Soleil",
            "de la Lune",
            "de l'Étoile",
            "de la Fontaine",
            "du Puits",
            "du Four",
            "du Moulin",
            "du Grenier",
            "de la Porte",
            "du Pont",
            "du Port",
            "du Quai",
            "de la Marine",
            "de la Gare",
            "du Théâtre",
            "de l'Ancienne Poste",
            "de la Paix",
            "de la Liberté",
            "Saint-Jacques",
            "Saint-Jean",
            "Saint-Martin",
            "Saint-Michel",
            "Saint-Nicolas",
            "Saint-Roch",
            "Sainte-Anne",
            "Sainte-Catherine",
            "Sainte-Marie",
            "Sainte-Claire",
            "Notre-Dame",
            "du Beffroi",
            "de la Citadelle",
            "de la Poterne",
            "de la Vieille Porte",
            "de la Porte Haute",
            "de la Porte Basse",
            "de la Halle aux Blés",
            "de l'Ancien Hôpital",
            "de l'Ancien Couvent",
            "de l'Ancienne Prison",
            "de l'Ancienne École",
            "de la Maison Commune",
            "de la Couronne",
            "du Dauphin",
            "du Lys",
            "de la Salamandre",
            "de la Licorne",
            "des Abeilles",
            "des Écuries",
            "des Remouleurs",
            "des Sabotiers",
            "des Menuisiers",
            "des Charpentiers",
            "des Serruriers",
            "des Chapeliers",
            "des Merciers",
            "des Drapiers",
            "des Imprimeurs",
            "des Relieurs",
            "des Libraires",
            "des Étuves",
            "des Lavandières",
            "des Bateliers",
            "des Tonnerliers",
            "des Vignerons",
            "des Meuniers",
            "des Jardiniers",
            "des Apothicaires",
            "du Tambour",
            "du Pilori",
            "du Bailli",
            "du Sénéchal",
            "du Vieux Logis",
            "du Petit Paris",
            "du Bon Secours",
            "de la Miséricorde",
            "de la Providence",
            "de la Charité",
            "des Trois Rois",
            "des Quatre Fils",
            "Saint-Louis",
            "Saint-Paul",
            "Saint-Pierre",
            "Saint-Thomas",
            "Sainte-Marguerite",
            "Sainte-Madeleine",
            "Sainte-Croix",
            "Notre-Dame-des-Champs"
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Impasse des Lilas",
            "Impasse des Roses",
            "Impasse des Glycines",
            "Impasse des Écoles",
            "Impasse des Jardins",
            "Impasse de l'Église",
            "Impasse de la Chapelle",
            "Impasse de la Fontaine",
            "Impasse du Moulin",
            "Impasse du Vieux Château",
            "Impasse du Clocher",
            "Impasse du Marché",
            "Impasse Saint-Jacques",
            "Impasse Saint-Martin",
            "Passage de l'Horloge",
            "Passage de l'Arche",
            "Passage des Tanneurs",
            "Passage des Artisans",
            "Passage des Halles",
            "Passage du Théâtre",
            "Passage du Commerce",
            "Passage de la Gare",
            "Ruelle des Forgerons",
            "Ruelle des Tisserands",
            "Ruelle des Potiers",
            "Ruelle du Four",
            "Ruelle du Puits",
            "Ruelle du Chat",
            "Ruelle du Coq",
            "Ruelle Saint-Jean",
            "Venelle des Jardins",
            "Venelle des Roses",
            "Venelle du Presbytère",
            "Venelle de la Tour",
            "Cour des Artisans",
            "Cour des Tanneurs",
            "Cour du Château",
            "Cour du Marché",
            "Petite Rue des Écoles",
            "Petite Rue du Moulin",
            "Traverse du Vieux Port",
            "Traverse des Remparts",
            "Montée du Château",
            "Montée de l'Église",
            "Montée Saint-Michel",
            "Descente du Port",
            "Descente de la Marine",
            "Rampe du Belvédère",
            "Rampe du Château",
            "Escalier de la Tour",
            "Escalier Saint-Roch",
            "Sente des Lilas",
            "Sente des Jardins",
            "Cité des Fleurs",
            "Cité des Artisans",
            "Impasse du Beffroi",
            "Impasse de la Citadelle",
            "Impasse de la Poterne",
            "Impasse de la Vieille Porte",
            "Impasse de la Halle aux Blés",
            "Impasse de l'Ancien Couvent",
            "Impasse de l'Ancienne École",
            "Impasse des Sabotiers",
            "Impasse des Menuisiers",
            "Impasse des Charpentiers",
            "Impasse des Jardiniers",
            "Impasse des Lavandières",
            "Impasse du Vieux Logis",
            "Impasse des Trois Rois",
            "Impasse Saint-Louis",
            "Passage du Beffroi",
            "Passage de la Citadelle",
            "Passage de la Poterne",
            "Passage de la Halle aux Blés",
            "Passage des Chapeliers",
            "Passage des Merciers",
            "Passage des Drapiers",
            "Passage des Imprimeurs",
            "Passage des Libraires",
            "Passage des Étuves",
            "Passage des Bateliers",
            "Passage du Dauphin",
            "Passage du Lys",
            "Passage de la Salamandre",
            "Passage de la Licorne",
            "Ruelle des Sabotiers",
            "Ruelle des Menuisiers",
            "Ruelle des Charpentiers",
            "Ruelle des Serruriers",
            "Ruelle des Chapeliers",
            "Ruelle des Merciers",
            "Ruelle des Drapiers",
            "Ruelle des Imprimeurs",
            "Ruelle des Meuniers",
            "Ruelle des Jardiniers",
            "Ruelle de la Poterne",
            "Ruelle du Beffroi",
            "Venelle des Lavandières",
            "Venelle des Vignerons",
            "Venelle des Abeilles",
            "Venelle de la Providence",
            "Venelle Sainte-Madeleine",
            "Cour des Écuries",
            "Cour des Imprimeurs",
            "Cour des Libraires",
            "Cour des Trois Rois",
            "Cour du Vieux Logis",
            "Cour de la Couronne",
            "Courée des Tisserands",
            "Courée des Ouvriers",
            "Courée du Moulin",
            "Galerie des Arcades",
            "Galerie du Commerce",
            "Galerie des Arts",
            "Calade du Château",
            "Calade de la Chapelle",
            "Calade des Remparts",
            "Montée de la Citadelle",
            "Montée du Beffroi",
            "Descente des Bateliers",
            "Descente du Vieux Port",
            "Rampe de la Poterne",
            "Escalier des Remparts",
            "Escalier de la Citadelle",
            "Traverse des Écuries",
            "Traverse du Petit Paris",
            "Petite Rue des Merciers",
            "Petite Rue des Chapeliers",
            "Cité des Jardins",
            "Cité des Cheminots",
            "Cité des Ouvriers"
        };

        internal static readonly string[] ResidentialPrefixes =
        {
            "Rue",
            "Rue",
            "Rue",
            "Rue",
            "Allée",
            "Allée",
            "Impasse",
            "Chemin",
            "Clos",
            "Square",
            "Place",
            "Sente",
            "Venelle"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            "des Acacias",
            "des Amandiers",
            "des Aubépines",
            "des Bouleaux",
            "des Cèdres",
            "des Cerisiers",
            "des Châtaigniers",
            "des Chênes",
            "des Érables",
            "des Frênes",
            "des Hêtres",
            "des Lauriers",
            "des Marronniers",
            "des Mélèzes",
            "des Noisetiers",
            "des Oliviers",
            "des Ormes",
            "des Peupliers",
            "des Pins",
            "des Platanes",
            "des Pommiers",
            "des Sapins",
            "des Saules",
            "des Tilleuls",
            "des Glycines",
            "des Hortensias",
            "des Iris",
            "des Jasmins",
            "des Jonquilles",
            "des Lavandes",
            "des Lilas",
            "des Marguerites",
            "des Mimosas",
            "des Pâquerettes",
            "des Pervenches",
            "des Primevères",
            "des Roses",
            "des Tulipes",
            "des Violettes",
            "du Bois Joli",
            "du Bosquet",
            "du Clos Fleuri",
            "du Coteau",
            "du Grand Jardin",
            "du Lac",
            "du Moulin",
            "du Parc",
            "du Petit Bois",
            "du Ruisseau",
            "du Soleil",
            "de la Clairière",
            "de la Colline",
            "de la Fontaine",
            "de la Forêt",
            "de la Lune",
            "de la Paix",
            "de la Prairie",
            "de la Source",
            "de la Vallée",
            "de l'Aube",
            "de l'Étang",
            "de l'Horizon",
            "de l'Orée du Bois",
            "de l'Arc-en-Ciel",
            "des Alouettes",
            "des Colombes",
            "des Écureuils",
            "des Hirondelles",
            "des Mésanges",
            "des Rossignols",
            "des Sources",
            "des Vergers",
            "de la Belle Étoile",
            "de la Bonne Fontaine",
            "de la Résidence",
            "de la Roseraie",
            "du Belvédère",
            "du Bon Accueil",
            "du Pré Vert",
            "Saint-Antoine",
            "Saint-Georges",
            "Saint-Joseph",
            "Saint-Laurent",
            "Saint-Martin",
            "Saint-Michel",
            "Sainte-Anne",
            "Sainte-Claire",
            "Sainte-Marie",
            "Sainte-Thérèse",
            "des Alisiers",
            "des Aulnes",
            "des Charmes",
            "des Cyprès",
            "des Genévriers",
            "des Ifs",
            "des Micocouliers",
            "des Sorbiers",
            "des Tamaris",
            "des Églantiers",
            "des Camélias",
            "des Capucines",
            "des Coquelicots",
            "des Dahlias",
            "des Genêts",
            "des Myosotis",
            "des Œillets",
            "des Pivoines",
            "des Bleuets",
            "des Fougères",
            "des Muguets",
            "des Narcisses",
            "des Pensées",
            "des Digitales",
            "des Anémones",
            "des Bergeronnettes",
            "des Chardonnerets",
            "des Fauvettes",
            "des Geais",
            "des Merles",
            "des Pinsons",
            "des Rouge-gorges",
            "des Tourterelles",
            "des Libellules",
            "des Papillons",
            "des Coccinelles",
            "du Bois Dormant",
            "du Bois Fleuri",
            "du Bois Clair",
            "du Petit Parc",
            "du Jardin des Roses",
            "du Jardin des Oiseaux",
            "du Verger",
            "du Vieux Verger",
            "du Pré Joli",
            "du Pré Fleuri",
            "du Pré des Sources",
            "du Val Fleuri",
            "du Val d'Or",
            "du Val Vert",
            "de la Belle Vue",
            "de la Bonne Étoile",
            "de la Douce Colline",
            "de la Grande Prairie",
            "de la Petite Prairie",
            "de la Haute Vallée",
            "de la Basse Vallée",
            "de la Rosée",
            "de la Brise",
            "de la Lumière",
            "de la Quiétude",
            "de la Sérénité",
            "de l'Espérance",
            "de l'Amitié",
            "de l'Harmonie",
            "de la Joie",
            "du Bonheur",
            "des Quatre Saisons",
            "des Trois Fontaines",
            "des Quatre Vents",
            "des Sept Collines",
            "Saint-Benoît",
            "Saint-Christophe",
            "Saint-François",
            "Saint-Paul",
            "Saint-Pierre",
            "Sainte-Bernadette",
            "Sainte-Cécile",
            "Sainte-Marguerite"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Rue des Acacias",
            "Rue des Amandiers",
            "Rue des Aubépines",
            "Rue des Bouleaux",
            "Rue des Cerisiers",
            "Rue des Chênes",
            "Rue des Érables",
            "Rue des Lauriers",
            "Rue des Marronniers",
            "Rue des Noisetiers",
            "Rue des Peupliers",
            "Rue des Pins",
            "Rue des Platanes",
            "Rue des Pommiers",
            "Rue des Sapins",
            "Rue des Saules",
            "Rue des Tilleuls",
            "Rue des Glycines",
            "Rue des Hortensias",
            "Rue des Iris",
            "Rue des Jasmins",
            "Rue des Lavandes",
            "Rue des Lilas",
            "Rue des Mimosas",
            "Rue des Roses",
            "Rue des Tulipes",
            "Rue des Violettes",
            "Rue du Bois Joli",
            "Rue du Clos Fleuri",
            "Rue du Moulin",
            "Rue du Parc",
            "Rue du Petit Bois",
            "Rue du Soleil",
            "Rue de la Clairière",
            "Rue de la Colline",
            "Rue de la Fontaine",
            "Rue de la Paix",
            "Rue de la Prairie",
            "Rue de la Source",
            "Rue de la Vallée",
            "Rue de l'Arc-en-Ciel",
            "Rue de l'Orée du Bois",
            "Rue des Alouettes",
            "Rue des Hirondelles",
            "Rue des Mésanges",
            "Rue des Vergers",
            "Allée des Acacias",
            "Allée des Cèdres",
            "Allée des Chênes",
            "Allée des Érables",
            "Allée des Marronniers",
            "Allée des Peupliers",
            "Allée des Pins",
            "Allée des Tilleuls",
            "Allée des Glycines",
            "Allée des Lilas",
            "Allée des Roses",
            "Allée du Parc",
            "Allée de la Roseraie",
            "Allée de la Source",
            "Impasse des Cerisiers",
            "Impasse des Lavandes",
            "Impasse des Mimosas",
            "Impasse des Pervenches",
            "Impasse du Bosquet",
            "Impasse de la Clairière",
            "Chemin du Bois Joli",
            "Chemin du Pré Vert",
            "Chemin de la Fontaine",
            "Clos des Amandiers",
            "Clos des Chênes",
            "Clos des Tilleuls",
            "Clos des Vignes",
            "Clos du Moulin",
            "Clos de la Roseraie",
            "Square des Érables",
            "Square des Marronniers",
            "Square des Mésanges",
            "Square du Belvédère",
            "Place des Tilleuls",
            "Place de la Fontaine",
            "Rue Saint-Antoine",
            "Rue Saint-Georges",
            "Rue Saint-Joseph",
            "Rue Saint-Laurent",
            "Rue Saint-Martin",
            "Rue Saint-Michel",
            "Rue Sainte-Anne",
            "Rue Sainte-Claire",
            "Rue Sainte-Marie",
            "Rue des Alisiers",
            "Rue des Aulnes",
            "Rue des Charmes",
            "Rue des Cyprès",
            "Rue des Genévriers",
            "Rue des Ifs",
            "Rue des Micocouliers",
            "Rue des Sorbiers",
            "Rue des Tamaris",
            "Rue des Églantiers",
            "Rue des Camélias",
            "Rue des Capucines",
            "Rue des Coquelicots",
            "Rue des Dahlias",
            "Rue des Genêts",
            "Rue des Myosotis",
            "Rue des Œillets",
            "Rue des Pivoines",
            "Rue des Bleuets",
            "Rue des Fougères",
            "Rue des Muguets",
            "Rue des Pinsons",
            "Rue des Rouge-gorges",
            "Rue des Tourterelles",
            "Rue des Papillons",
            "Rue des Coccinelles",
            "Rue du Bois Dormant",
            "Rue du Bois Fleuri",
            "Rue du Bois Clair",
            "Rue du Jardin des Roses",
            "Rue du Vieux Verger",
            "Rue du Pré Joli",
            "Rue du Val Fleuri",
            "Rue du Val d'Or",
            "Rue de la Belle Vue",
            "Rue de la Bonne Étoile",
            "Rue de la Rosée",
            "Rue de la Brise",
            "Rue de la Lumière",
            "Rue de la Quiétude",
            "Rue de la Sérénité",
            "Rue de l'Espérance",
            "Rue de l'Amitié",
            "Rue de l'Harmonie",
            "Rue de la Joie",
            "Rue du Bonheur",
            "Rue des Quatre Saisons",
            "Rue des Trois Fontaines",
            "Rue des Quatre Vents",
            "Allée des Alisiers",
            "Allée des Aulnes",
            "Allée des Charmes",
            "Allée des Cyprès",
            "Allée des Genévriers",
            "Allée des Sorbiers",
            "Allée des Tamaris",
            "Allée des Camélias",
            "Allée des Coquelicots",
            "Allée des Dahlias",
            "Allée des Genêts",
            "Allée des Pivoines",
            "Allée des Bleuets",
            "Allée des Fougères",
            "Allée des Pinsons",
            "Allée des Tourterelles",
            "Allée du Bois Fleuri",
            "Allée du Val Vert",
            "Allée de la Belle Vue",
            "Allée de la Sérénité",
            "Allée des Quatre Saisons",
            "Impasse des Camélias",
            "Impasse des Coquelicots",
            "Impasse des Dahlias",
            "Impasse des Genêts",
            "Impasse des Myosotis",
            "Impasse des Œillets",
            "Impasse des Pivoines",
            "Impasse des Bleuets",
            "Impasse des Fougères",
            "Impasse des Tourterelles",
            "Impasse du Pré Joli",
            "Impasse du Val Fleuri",
            "Impasse de la Bonne Étoile",
            "Chemin du Bois Dormant",
            "Chemin du Bois Fleuri",
            "Chemin du Vieux Verger",
            "Chemin des Trois Fontaines",
            "Clos des Alisiers",
            "Clos des Aulnes",
            "Clos des Cyprès",
            "Clos des Genévriers",
            "Clos des Sorbiers",
            "Clos des Tamaris",
            "Clos des Camélias",
            "Clos des Coquelicots",
            "Clos du Pré Fleuri",
            "Clos du Val d'Or",
            "Square des Alouettes",
            "Square des Pinsons",
            "Square des Rouge-gorges",
            "Square des Tourterelles",
            "Square des Quatre Saisons",
            "Place des Camélias",
            "Place des Quatre Vents",
            "Sente des Fougères",
            "Sente des Muguets",
            "Sente des Pinsons",
            "Venelle des Camélias",
            "Venelle des Genêts",
            "Venelle du Pré Joli",
            "Rue Saint-Benoît",
            "Rue Saint-Christophe",
            "Rue Saint-François",
            "Rue Saint-Paul",
            "Rue Saint-Pierre",
            "Rue Sainte-Bernadette",
            "Rue Sainte-Cécile",
            "Rue Sainte-Marguerite"
        };

        internal static readonly string[] StandardPrefixes =
        {
            "Rue",
            "Rue",
            "Rue",
            "Rue",
            "Route",
            "Route",
            "Place",
            "Place",
            "Cours",
            "Quai",
            "Faubourg",
            "Rue",
            "Place",
            "Parvis"
        };

        internal static readonly string[] StandardBaseNames =
        {
            "de la République",
            "de la Liberté",
            "de l'Égalité",
            "de la Fraternité",
            "de la Paix",
            "de la Victoire",
            "de la Résistance",
            "de la Libération",
            "de l'Indépendance",
            "de l'Europe",
            "de France",
            "du 8 Mai 1945",
            "du 11 Novembre 1918",
            "du 14 Juillet",
            "du Souvenir Français",
            "des Anciens Combattants",
            "des Déportés",
            "des Fusillés",
            "des Martyrs",
            "du Général de Gaulle",
            "du Général Leclerc",
            "du Maréchal Foch",
            "du Maréchal Joffre",
            "Georges Clemenceau",
            "Jean Jaurès",
            "Jean Moulin",
            "Jules Ferry",
            "Léon Gambetta",
            "Léon Blum",
            "Pierre Mendès France",
            "Robert Schuman",
            "Simone Veil",
            "Victor Hugo",
            "Émile Zola",
            "Alexandre Dumas",
            "Honoré de Balzac",
            "Gustave Flaubert",
            "Marcel Proust",
            "Jules Verne",
            "Antoine de Saint-Exupéry",
            "Albert Camus",
            "Jean de La Fontaine",
            "Molière",
            "Voltaire",
            "Jean-Jacques Rousseau",
            "Alphonse de Lamartine",
            "Arthur Rimbaud",
            "Paul Verlaine",
            "George Sand",
            "Colette",
            "Louise Michel",
            "Louis Pasteur",
            "Marie Curie",
            "Pierre Curie",
            "Irène Joliot-Curie",
            "Frédéric Joliot-Curie",
            "André-Marie Ampère",
            "Blaise Pascal",
            "René Descartes",
            "Denis Papin",
            "Gustave Eiffel",
            "Clément Ader",
            "Louis Blériot",
            "Jean Mermoz",
            "Roland Garros",
            "Auguste Renoir",
            "Claude Monet",
            "Édouard Manet",
            "Paul Cézanne",
            "Henri Matisse",
            "Auguste Rodin",
            "Camille Claudel",
            "Hector Berlioz",
            "Claude Debussy",
            "Maurice Ravel",
            "Georges Bizet",
            "Charles Gounod",
            "de l'Hôtel de Ville",
            "de la Mairie",
            "de la Préfecture",
            "du Palais de Justice",
            "de la Poste",
            "de la Gare",
            "des Écoles",
            "du Collège",
            "du Lycée",
            "de l'Université",
            "de la Bibliothèque",
            "du Musée",
            "du Théâtre",
            "du Marché",
            "des Halles",
            "de l'Hôpital",
            "du Stade",
            "du Port",
            "de la Marine",
            "du Château",
            "de la Citadelle",
            "des Remparts",
            "du Vieux Pont",
            "de la Cathédrale",
            "de l'Église",
            "de la Synagogue",
            "du Temple",
            "de l'Industrie",
            "du Commerce",
            "de l'Artisanat",
            "de l'Innovation",
            "de la Science",
            "des Arts",
            "de la Culture",
            "des Sports",
            "de Paris",
            "de Lyon",
            "de Marseille",
            "de Bordeaux",
            "de Lille",
            "de Toulouse",
            "de Nantes",
            "de Strasbourg",
            "de Nice",
            "de Rennes",
            "de Rouen",
            "de Dijon",
            "de Grenoble",
            "de Montpellier",
            "de Reims",
            "de Tours",
            "d'Orléans",
            "de Nancy",
            "de Metz",
            "de Bretagne",
            "de Normandie",
            "de Provence",
            "d'Alsace",
            "de Lorraine",
            "de Bourgogne",
            "de Champagne",
            "d'Auvergne",
            "de Savoie",
            "du Dauphiné",
            "des Alpes",
            "des Pyrénées",
            "du Jura",
            "des Vosges",
            "de la Loire",
            "de la Seine",
            "du Rhône",
            "de la Garonne",
            "de la Dordogne",
            "de la Somme",
            "de la Marne",
            "de la Meuse",
            "de l'Atlantique",
            "de la Méditerranée",
            "du 18 Juin 1940",
            "du 19 Mars 1962",
            "des Résistants",
            "des Justes",
            "des Héros",
            "des Volontaires",
            "des Droits de l'Homme",
            "des Droits de l'Enfant",
            "de la Citoyenneté",
            "de la Démocratie",
            "de la Solidarité",
            "de la Justice",
            "de la Tolérance",
            "de la Laïcité",
            "de la Mémoire",
            "de l'Avenir",
            "du Progrès",
            "de la Renaissance",
            "de la Concorde",
            "de l'Union",
            "de l'Entente",
            "de la Sous-Préfecture",
            "de la Médiathèque",
            "du Conservatoire",
            "du Théâtre Municipal",
            "du Centre Culturel",
            "du Jardin Public",
            "du Jardin Botanique",
            "du Parc des Expositions",
            "de la Caserne",
            "des Pompiers",
            "de la Gendarmerie",
            "du Gymnase",
            "de la Piscine",
            "de l'Hippodrome",
            "de l'Aérodrome",
            "de la Zone Artisanale",
            "de la Zone Industrielle",
            "du Technopôle",
            "du Pôle Santé",
            "de l'Observatoire",
            "du Canal",
            "de l'Écluse",
            "de la Digue",
            "du Vieux Port",
            "du Nouveau Port",
            "du Port de Plaisance",
            "du Bassin",
            "de la Jetée",
            "de la Corniche",
            "du Front de Mer",
            "des Quatre Chemins",
            "des Trois Fontaines",
            "des Deux Ponts",
            "du Carrefour",
            "du Rond-Point",
            "Olympe de Gouges",
            "Simone de Beauvoir",
            "Joséphine Baker",
            "Germaine Tillion",
            "Geneviève de Gaulle-Anthonioz",
            "Lucie Aubrac",
            "Gisèle Halimi",
            "Françoise Dolto",
            "Marguerite Yourcenar",
            "Marguerite Duras",
            "Berthe Morisot",
            "Rosa Bonheur",
            "Édith Piaf",
            "Suzanne Lenglen",
            "Alice Milliat",
            "Hélène Boucher",
            "Jacqueline Auriol",
            "André Malraux",
            "Marcel Pagnol",
            "Guy de Maupassant",
            "Stendhal",
            "Charles Baudelaire",
            "Antoine Lavoisier",
            "Henri Becquerel",
            "Denis Diderot",
            "Jean le Rond d'Alembert",
            "Claude Bernard",
            "Paul Éluard",
            "Louis Aragon",
            "Aimé Césaire",
            "Léopold Sédar Senghor",
            "Pierre de Ronsard",
            "François Rabelais",
            "Joan Miró",
            "Paul Gauguin",
            "Edgar Degas",
            "Eugène Delacroix",
            "Georges Braque",
            "Marc Chagall",
            "Camille Saint-Saëns",
            "Gabriel Fauré",
            "Erik Satie",
            "Django Reinhardt",
            "Charles Trenet",
            "Georges Brassens",
            "Jacques Brel",
            "Léo Ferré",
            "Amiens",
            "Angers",
            "Annecy",
            "Avignon",
            "Bayonne",
            "Besançon",
            "Brest",
            "Caen",
            "Calais",
            "Cannes",
            "Clermont-Ferrand",
            "Colmar",
            "La Rochelle",
            "Le Havre",
            "Limoges",
            "Metz",
            "Mulhouse",
            "Nancy",
            "Nîmes",
            "Orléans",
            "Pau",
            "Perpignan",
            "Poitiers",
            "Saint-Étienne",
            "Toulon",
            "Versailles",
            "de la Camargue",
            "des Cévennes",
            "du Vercors",
            "du Morvan",
            "des Ardennes",
            "du Massif Central",
            "du Mont-Blanc",
            "de la Saône",
            "de la Moselle",
            "de l'Oise",
            "de la Charente",
            "de la Corse",
            "de l'Occitanie",
            "de la Picardie",
            "des Flandres",
            "du Languedoc",
            "du Roussillon",
            "du Béarn",
            "du Pays Basque",
            "de l'Anjou",
            "du Maine",
            "du Berry",
            "du Limousin",
            "du Poitou"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Rue de la République",
            "Rue de la Liberté",
            "Rue de l'Égalité",
            "Rue de la Fraternité",
            "Rue de la Paix",
            "Rue de la Victoire",
            "Rue de la Résistance",
            "Rue de la Libération",
            "Rue du 8 Mai 1945",
            "Rue du 11 Novembre 1918",
            "Rue du 14 Juillet",
            "Rue du Général de Gaulle",
            "Rue du Général Leclerc",
            "Rue du Maréchal Foch",
            "Rue Georges Clemenceau",
            "Rue Jean Jaurès",
            "Rue Jean Moulin",
            "Rue Jules Ferry",
            "Rue Léon Gambetta",
            "Rue Léon Blum",
            "Rue Simone Veil",
            "Rue Victor Hugo",
            "Rue Émile Zola",
            "Rue Alexandre Dumas",
            "Rue Honoré de Balzac",
            "Rue Gustave Flaubert",
            "Rue Marcel Proust",
            "Rue Jules Verne",
            "Rue Antoine de Saint-Exupéry",
            "Rue Albert Camus",
            "Rue Jean de La Fontaine",
            "Rue Molière",
            "Rue Voltaire",
            "Rue Jean-Jacques Rousseau",
            "Rue Alphonse de Lamartine",
            "Rue Arthur Rimbaud",
            "Rue Paul Verlaine",
            "Rue George Sand",
            "Rue Colette",
            "Rue Louise Michel",
            "Rue Louis Pasteur",
            "Rue Marie Curie",
            "Rue Pierre Curie",
            "Rue Irène Joliot-Curie",
            "Rue André-Marie Ampère",
            "Rue Blaise Pascal",
            "Rue René Descartes",
            "Rue Gustave Eiffel",
            "Rue Louis Blériot",
            "Rue Jean Mermoz",
            "Rue Claude Monet",
            "Rue Auguste Renoir",
            "Rue Paul Cézanne",
            "Rue Henri Matisse",
            "Rue Camille Claudel",
            "Rue Hector Berlioz",
            "Rue Claude Debussy",
            "Rue Maurice Ravel",
            "Rue de l'Hôtel de Ville",
            "Rue de la Mairie",
            "Rue de la Gare",
            "Rue des Écoles",
            "Rue du Collège",
            "Rue du Lycée",
            "Rue de l'Université",
            "Rue de la Bibliothèque",
            "Rue du Musée",
            "Rue du Théâtre",
            "Rue du Marché",
            "Rue des Halles",
            "Rue de l'Hôpital",
            "Rue du Stade",
            "Rue du Port",
            "Rue de la Marine",
            "Rue du Château",
            "Rue de la Citadelle",
            "Rue des Remparts",
            "Rue du Vieux Pont",
            "Rue de la Cathédrale",
            "Rue de l'Église",
            "Rue de l'Industrie",
            "Rue du Commerce",
            "Rue de l'Artisanat",
            "Rue de l'Innovation",
            "Rue de la Science",
            "Rue des Arts",
            "Rue de la Culture",
            "Rue de Paris",
            "Rue de Lyon",
            "Rue de Marseille",
            "Rue de Bordeaux",
            "Rue de Lille",
            "Rue de Toulouse",
            "Rue de Nantes",
            "Rue de Strasbourg",
            "Rue de Nice",
            "Rue de Rennes",
            "Rue de Rouen",
            "Rue de Dijon",
            "Rue de Grenoble",
            "Rue de Montpellier",
            "Rue de Reims",
            "Rue de Tours",
            "Rue d'Orléans",
            "Rue de Nancy",
            "Rue de Metz",
            "Rue de Bretagne",
            "Rue de Normandie",
            "Rue de Provence",
            "Rue d'Alsace",
            "Rue de Lorraine",
            "Rue de Bourgogne",
            "Rue de Champagne",
            "Rue d'Auvergne",
            "Rue de Savoie",
            "Rue des Alpes",
            "Rue des Pyrénées",
            "Rue de la Loire",
            "Rue de la Seine",
            "Rue du Rhône",
            "Rue de la Garonne",
            "Place de la République",
            "Place de la Liberté",
            "Place de la Paix",
            "Place de la Victoire",
            "Place de la Résistance",
            "Place de la Libération",
            "Place du Général de Gaulle",
            "Place Jean Jaurès",
            "Place Victor Hugo",
            "Place Louis Pasteur",
            "Place de l'Hôtel de Ville",
            "Place de la Mairie",
            "Place de la Gare",
            "Place du Marché",
            "Place des Halles",
            "Place de l'Église",
            "Cours de la République",
            "Cours de la Liberté",
            "Cours Jean Jaurès",
            "Cours Victor Hugo",
            "Cours Léon Gambetta",
            "Cours Louis Pasteur",
            "Quai de la Marine",
            "Quai du Port",
            "Quai de la Loire",
            "Quai de la Seine",
            "Quai du Rhône",
            "Quai Victor Hugo",
            "Faubourg Saint-Antoine",
            "Faubourg Saint-Martin",
            "Faubourg de la Gare",
            "Parvis de l'Hôtel de Ville",
            "Parvis de la Cathédrale",
            "Rue du 18 Juin 1940",
            "Rue du 19 Mars 1962",
            "Rue du Souvenir Français",
            "Rue des Anciens Combattants",
            "Rue des Déportés",
            "Rue des Résistants",
            "Rue des Justes",
            "Rue des Héros",
            "Rue des Droits de l'Homme",
            "Rue de la Citoyenneté",
            "Rue de la Démocratie",
            "Rue de la Solidarité",
            "Rue de la Justice",
            "Rue de la Tolérance",
            "Rue de la Laïcité",
            "Rue de la Mémoire",
            "Rue de l'Avenir",
            "Rue du Progrès",
            "Rue de la Renaissance",
            "Rue de la Concorde",
            "Rue de l'Union",
            "Rue de la Médiathèque",
            "Rue du Conservatoire",
            "Rue du Centre Culturel",
            "Rue du Jardin Public",
            "Rue du Palais de Justice",
            "Rue des Pompiers",
            "Rue de la Gendarmerie",
            "Rue du Gymnase",
            "Rue de la Piscine",
            "Rue de l'Hippodrome",
            "Rue de l'Aérodrome",
            "Rue de la Zone Artisanale",
            "Rue du Technopôle",
            "Rue de l'Observatoire",
            "Rue du Canal",
            "Rue de l'Écluse",
            "Rue de la Digue",
            "Rue du Vieux Port",
            "Rue du Port de Plaisance",
            "Rue de la Jetée",
            "Rue de la Corniche",
            "Rue des Quatre Chemins",
            "Rue des Trois Fontaines",
            "Rue Olympe de Gouges",
            "Rue Simone de Beauvoir",
            "Rue Joséphine Baker",
            "Rue Germaine Tillion",
            "Rue Geneviève de Gaulle-Anthonioz",
            "Rue Lucie Aubrac",
            "Rue Gisèle Halimi",
            "Rue Françoise Dolto",
            "Rue Marguerite Yourcenar",
            "Rue Marguerite Duras",
            "Rue Berthe Morisot",
            "Rue Rosa Bonheur",
            "Rue Édith Piaf",
            "Rue Suzanne Lenglen",
            "Rue Alice Milliat",
            "Rue Hélène Boucher",
            "Rue Jacqueline Auriol",
            "Rue André Malraux",
            "Rue Marcel Pagnol",
            "Rue Guy de Maupassant",
            "Rue Stendhal",
            "Rue Charles Baudelaire",
            "Rue Antoine Lavoisier",
            "Rue Henri Becquerel",
            "Rue Denis Diderot",
            "Rue Claude Bernard",
            "Rue Paul Éluard",
            "Rue Louis Aragon",
            "Rue Aimé Césaire",
            "Rue Léopold Sédar Senghor",
            "Rue Pierre de Ronsard",
            "Rue François Rabelais",
            "Rue Paul Gauguin",
            "Rue Edgar Degas",
            "Rue Eugène Delacroix",
            "Rue Georges Braque",
            "Rue Marc Chagall",
            "Rue Camille Saint-Saëns",
            "Rue Georges Bizet",
            "Rue Gabriel Fauré",
            "Rue Erik Satie",
            "Rue Django Reinhardt",
            "Rue Charles Trenet",
            "Rue Georges Brassens",
            "Rue Jacques Brel",
            "Rue Léo Ferré",
            "Rue d'Amiens",
            "Rue d'Angers",
            "Rue d'Annecy",
            "Rue d'Avignon",
            "Rue de Bayonne",
            "Rue de Besançon",
            "Rue de Brest",
            "Rue de Caen",
            "Rue de Calais",
            "Rue de Cannes",
            "Rue de Clermont-Ferrand",
            "Rue de Colmar",
            "Rue de La Rochelle",
            "Rue du Havre",
            "Rue de Limoges",
            "Rue de Mulhouse",
            "Rue de Nîmes",
            "Rue de Pau",
            "Rue de Perpignan",
            "Rue de Poitiers",
            "Rue de Saint-Étienne",
            "Rue de Toulon",
            "Rue de Versailles",
            "Rue de la Camargue",
            "Rue des Cévennes",
            "Rue du Vercors",
            "Rue du Morvan",
            "Rue des Ardennes",
            "Rue du Massif Central",
            "Rue du Mont-Blanc",
            "Rue de la Dordogne",
            "Rue de la Saône",
            "Rue de la Meuse",
            "Rue de la Moselle",
            "Rue de la Marne",
            "Rue de la Somme",
            "Rue de l'Oise",
            "Rue de la Charente",
            "Rue de la Corse",
            "Rue de l'Occitanie",
            "Rue de la Picardie",
            "Rue des Flandres",
            "Rue du Languedoc",
            "Rue du Roussillon",
            "Rue du Dauphiné",
            "Rue du Béarn",
            "Rue du Pays Basque",
            "Rue de l'Anjou",
            "Rue du Maine",
            "Rue du Berry",
            "Rue du Limousin",
            "Rue du Poitou",
            "Route de la Camargue",
            "Route des Cévennes",
            "Route du Vercors",
            "Route du Morvan",
            "Route des Ardennes",
            "Route du Mont-Blanc",
            "Route de la Loire",
            "Route de la Garonne",
            "Route de la Dordogne",
            "Route du Pays Basque",
            "Place Olympe de Gouges",
            "Place Louise Michel",
            "Place Simone de Beauvoir",
            "Place Joséphine Baker",
            "Place Lucie Aubrac",
            "Place Gisèle Halimi",
            "Place Albert Camus",
            "Place Jules Verne",
            "Place Émile Zola",
            "Place Molière",
            "Place des Droits de l'Homme",
            "Place de la Solidarité",
            "Place de la Mémoire",
            "Place de l'Avenir",
            "Cours André Malraux",
            "Cours Albert Camus",
            "Cours Marcel Pagnol",
            "Cours Olympe de Gouges",
            "Cours Joséphine Baker",
            "Cours des Arts",
            "Cours de la Méditerranée",
            "Quai de la Garonne",
            "Quai de la Dordogne",
            "Quai de la Saône",
            "Quai de la Meuse",
            "Quai de la Moselle",
            "Quai de la Marne",
            "Quai de la Somme",
            "Quai de la Charente",
            "Quai des Bateliers",
            "Quai des Pêcheurs",
            "Quai du Vieux Port",
            "Faubourg Saint-Louis",
            "Faubourg Saint-Pierre",
            "Faubourg de la Madeleine",
            "Faubourg des Trois Maisons",
            "Parvis de la Médiathèque",
            "Parvis du Théâtre",
            "Parvis de la Gare",
            "Mail de la République",
            "Mail des Tilleuls",
            "Mail des Arts",
            "Esplanade des Droits de l'Homme",
            "Esplanade de la Mémoire",
            "Promenade du Canal",
            "Promenade de la Digue",
            "Chaussée du Vieux Port"
        };

        internal static readonly string[] AvenuePrefixes =
        {
            "Avenue",
            "Avenue",
            "Avenue",
            "Avenue",
            "Boulevard",
            "Boulevard",
            "Boulevard",
            "Cours",
            "Promenade",
            "Esplanade"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "de la République",
            "de la Liberté",
            "de l'Égalité",
            "de la Fraternité",
            "de la Paix",
            "de la Victoire",
            "de la Résistance",
            "de la Libération",
            "de l'Europe",
            "de France",
            "des Nations",
            "du Général de Gaulle",
            "du Général Leclerc",
            "du Maréchal Foch",
            "Georges Clemenceau",
            "Jean Jaurès",
            "Jean Moulin",
            "Léon Gambetta",
            "Léon Blum",
            "Robert Schuman",
            "Simone Veil",
            "Victor Hugo",
            "Louis Pasteur",
            "Marie Curie",
            "Pierre Curie",
            "Gustave Eiffel",
            "Jean Mermoz",
            "Antoine de Saint-Exupéry",
            "Claude Monet",
            "Auguste Renoir",
            "Maurice Ravel",
            "des Champs-Élysées",
            "des Tilleuls",
            "des Platanes",
            "des Marronniers",
            "des Cèdres",
            "des Pins",
            "des Acacias",
            "des Roses",
            "des Jardins",
            "du Parc",
            "du Bois",
            "du Lac",
            "du Littoral",
            "du Bord de Mer",
            "de la Côte",
            "de la Corniche",
            "de la Gare",
            "du Port",
            "de l'Aéroport",
            "de l'Université",
            "des Sciences",
            "de l'Innovation",
            "de l'Industrie",
            "du Commerce",
            "des Arts",
            "de la Culture",
            "des Sports",
            "de Paris",
            "de Lyon",
            "de Marseille",
            "de Bordeaux",
            "de Lille",
            "de Toulouse",
            "de Nantes",
            "de Strasbourg",
            "de Nice",
            "de Rennes",
            "de Rouen",
            "de Dijon",
            "de Grenoble",
            "de Montpellier",
            "de Reims",
            "de Tours",
            "de Bretagne",
            "de Normandie",
            "de Provence",
            "d'Alsace",
            "de Lorraine",
            "de Bourgogne",
            "de Champagne",
            "d'Auvergne",
            "de Savoie",
            "des Alpes",
            "des Pyrénées",
            "du Jura",
            "des Vosges",
            "de l'Atlantique",
            "de la Méditerranée",
            "du Nord",
            "du Sud",
            "de l'Est",
            "de l'Ouest",
            "du Centre",
            "du 18 Juin 1940",
            "du Souvenir Français",
            "des Anciens Combattants",
            "des Droits de l'Homme",
            "de la Démocratie",
            "de la Solidarité",
            "de la Justice",
            "de la Tolérance",
            "de la Citoyenneté",
            "de l'Avenir",
            "du Progrès",
            "de la Renaissance",
            "de la Concorde",
            "Olympe de Gouges",
            "George Sand",
            "Louise Michel",
            "Simone de Beauvoir",
            "Joséphine Baker",
            "Germaine Tillion",
            "Lucie Aubrac",
            "Gisèle Halimi",
            "Marguerite Yourcenar",
            "Camille Claudel",
            "Berthe Morisot",
            "Rosa Bonheur",
            "Édith Piaf",
            "Suzanne Lenglen",
            "Hélène Boucher",
            "Jacqueline Auriol",
            "André Malraux",
            "Albert Camus",
            "Marcel Pagnol",
            "Jules Verne",
            "Alexandre Dumas",
            "Émile Zola",
            "Molière",
            "René Descartes",
            "Blaise Pascal",
            "André-Marie Ampère",
            "Aimé Césaire",
            "Henri Matisse",
            "Paul Cézanne",
            "Claude Debussy",
            "Hector Berlioz",
            "Gabriel Fauré",
            "Georges Brassens",
            "Jacques Brel",
            "des Chênes",
            "des Érables",
            "des Sorbiers",
            "des Tamaris",
            "des Camélias",
            "des Lavandes",
            "des Oliviers",
            "des Fontaines",
            "des Quatre Saisons",
            "du Bois Fleuri",
            "du Val de Loire",
            "du Val d'Or",
            "de la Belle Vue",
            "du Vieux Port",
            "du Port de Plaisance",
            "du Canal",
            "de la Digue",
            "de la Jetée",
            "du Front de Mer",
            "de la Camargue",
            "des Cévennes",
            "du Vercors",
            "du Morvan",
            "des Ardennes",
            "du Massif Central",
            "du Mont-Blanc",
            "de la Loire",
            "de la Garonne",
            "de la Dordogne",
            "de la Saône",
            "de la Meuse",
            "de la Moselle",
            "de la Marne",
            "de la Somme",
            "de la Charente",
            "de la Corse",
            "de l'Occitanie",
            "des Flandres",
            "du Languedoc",
            "du Roussillon",
            "du Dauphiné",
            "du Béarn",
            "du Pays Basque",
            "de l'Anjou",
            "du Limousin",
            "du Poitou",
            "d'Amiens",
            "d'Angers",
            "d'Annecy",
            "d'Avignon",
            "de Bayonne",
            "de Besançon",
            "de Brest",
            "de Caen",
            "de Calais",
            "de Cannes",
            "de Clermont-Ferrand",
            "de Colmar",
            "de La Rochelle",
            "du Havre",
            "de Limoges",
            "de Metz",
            "de Mulhouse",
            "de Nancy",
            "de Nîmes",
            "d'Orléans",
            "de Pau",
            "de Perpignan",
            "de Poitiers",
            "de Saint-Étienne",
            "de Toulon",
            "de Versailles"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Avenue de la République",
            "Avenue de la Liberté",
            "Avenue de la Paix",
            "Avenue de la Victoire",
            "Avenue de la Résistance",
            "Avenue de la Libération",
            "Avenue de l'Europe",
            "Avenue de France",
            "Avenue des Nations",
            "Avenue du Général de Gaulle",
            "Avenue du Général Leclerc",
            "Avenue du Maréchal Foch",
            "Avenue Georges Clemenceau",
            "Avenue Jean Jaurès",
            "Avenue Jean Moulin",
            "Avenue Léon Gambetta",
            "Avenue Léon Blum",
            "Avenue Robert Schuman",
            "Avenue Simone Veil",
            "Avenue Victor Hugo",
            "Avenue Louis Pasteur",
            "Avenue Marie Curie",
            "Avenue Gustave Eiffel",
            "Avenue Jean Mermoz",
            "Avenue Antoine de Saint-Exupéry",
            "Avenue Claude Monet",
            "Avenue des Champs-Élysées",
            "Avenue des Tilleuls",
            "Avenue des Platanes",
            "Avenue des Marronniers",
            "Avenue des Cèdres",
            "Avenue des Pins",
            "Avenue des Jardins",
            "Avenue du Parc",
            "Avenue du Littoral",
            "Avenue de la Gare",
            "Avenue du Port",
            "Avenue de l'Aéroport",
            "Avenue de l'Université",
            "Avenue des Sciences",
            "Avenue de l'Innovation",
            "Avenue de l'Industrie",
            "Avenue du Commerce",
            "Avenue des Arts",
            "Avenue de la Culture",
            "Avenue des Sports",
            "Avenue de Paris",
            "Avenue de Lyon",
            "Avenue de Marseille",
            "Avenue de Bordeaux",
            "Avenue de Lille",
            "Avenue de Toulouse",
            "Avenue de Nantes",
            "Avenue de Strasbourg",
            "Avenue de Nice",
            "Avenue de Bretagne",
            "Avenue de Normandie",
            "Avenue de Provence",
            "Avenue d'Alsace",
            "Avenue de Lorraine",
            "Avenue de Savoie",
            "Avenue des Alpes",
            "Avenue des Pyrénées",
            "Avenue de l'Atlantique",
            "Avenue de la Méditerranée",
            "Boulevard de la République",
            "Boulevard de la Liberté",
            "Boulevard de la Paix",
            "Boulevard de la Victoire",
            "Boulevard de la Résistance",
            "Boulevard de la Libération",
            "Boulevard de l'Europe",
            "Boulevard de France",
            "Boulevard du Général de Gaulle",
            "Boulevard du Général Leclerc",
            "Boulevard du Maréchal Foch",
            "Boulevard Georges Clemenceau",
            "Boulevard Jean Jaurès",
            "Boulevard Victor Hugo",
            "Boulevard Louis Pasteur",
            "Boulevard des Tilleuls",
            "Boulevard des Platanes",
            "Boulevard du Littoral",
            "Boulevard de la Gare",
            "Boulevard du Port",
            "Boulevard de l'Université",
            "Boulevard de l'Industrie",
            "Boulevard des Arts",
            "Boulevard de Paris",
            "Boulevard de Lyon",
            "Boulevard de Marseille",
            "Boulevard de Bordeaux",
            "Boulevard de Strasbourg",
            "Cours de la République",
            "Cours de la Liberté",
            "Cours Jean Jaurès",
            "Cours Léon Gambetta",
            "Cours Victor Hugo",
            "Cours Louis Pasteur",
            "Promenade des Tilleuls",
            "Promenade des Roses",
            "Promenade du Littoral",
            "Promenade du Lac",
            "Promenade de la Corniche",
            "Promenade des Arts",
            "Esplanade de la République",
            "Esplanade de la Liberté",
            "Esplanade de l'Europe",
            "Esplanade de la Gare",
            "Esplanade des Arts",
            "Avenue du 18 Juin 1940",
            "Avenue du Souvenir Français",
            "Avenue des Anciens Combattants",
            "Avenue des Droits de l'Homme",
            "Avenue de la Démocratie",
            "Avenue de la Solidarité",
            "Avenue de la Justice",
            "Avenue de la Tolérance",
            "Avenue de la Citoyenneté",
            "Avenue de l'Avenir",
            "Avenue du Progrès",
            "Avenue de la Renaissance",
            "Avenue de la Concorde",
            "Avenue Olympe de Gouges",
            "Avenue George Sand",
            "Avenue Louise Michel",
            "Avenue Simone de Beauvoir",
            "Avenue Joséphine Baker",
            "Avenue Germaine Tillion",
            "Avenue Lucie Aubrac",
            "Avenue Gisèle Halimi",
            "Avenue Marguerite Yourcenar",
            "Avenue Camille Claudel",
            "Avenue Berthe Morisot",
            "Avenue Rosa Bonheur",
            "Avenue Édith Piaf",
            "Avenue Suzanne Lenglen",
            "Avenue Hélène Boucher",
            "Avenue Jacqueline Auriol",
            "Avenue André Malraux",
            "Avenue Albert Camus",
            "Avenue Marcel Pagnol",
            "Avenue Jules Verne",
            "Avenue Alexandre Dumas",
            "Avenue Émile Zola",
            "Avenue Molière",
            "Avenue René Descartes",
            "Avenue Blaise Pascal",
            "Avenue André-Marie Ampère",
            "Avenue Aimé Césaire",
            "Avenue Henri Matisse",
            "Avenue Paul Cézanne",
            "Avenue Claude Debussy",
            "Avenue Hector Berlioz",
            "Avenue Gabriel Fauré",
            "Avenue Georges Brassens",
            "Avenue Jacques Brel",
            "Avenue des Acacias",
            "Avenue des Chênes",
            "Avenue des Érables",
            "Avenue des Sorbiers",
            "Avenue des Tamaris",
            "Avenue des Camélias",
            "Avenue des Lavandes",
            "Avenue des Oliviers",
            "Avenue des Fontaines",
            "Avenue des Quatre Saisons",
            "Avenue du Bois Fleuri",
            "Avenue du Val de Loire",
            "Avenue du Val d'Or",
            "Avenue de la Belle Vue",
            "Avenue du Vieux Port",
            "Avenue du Port de Plaisance",
            "Avenue du Canal",
            "Avenue de la Digue",
            "Avenue de la Jetée",
            "Avenue du Front de Mer",
            "Avenue de la Camargue",
            "Avenue des Cévennes",
            "Avenue du Vercors",
            "Avenue du Morvan",
            "Avenue des Ardennes",
            "Avenue du Massif Central",
            "Avenue du Mont-Blanc",
            "Avenue de la Loire",
            "Avenue de la Garonne",
            "Avenue de la Dordogne",
            "Avenue de la Saône",
            "Avenue de la Meuse",
            "Avenue de la Moselle",
            "Avenue de la Marne",
            "Avenue de la Somme",
            "Avenue de la Charente",
            "Avenue de la Corse",
            "Avenue de l'Occitanie",
            "Avenue des Flandres",
            "Avenue du Languedoc",
            "Avenue du Roussillon",
            "Avenue du Dauphiné",
            "Avenue du Béarn",
            "Avenue du Pays Basque",
            "Avenue de l'Anjou",
            "Avenue du Limousin",
            "Avenue du Poitou",
            "Avenue d'Amiens",
            "Avenue d'Angers",
            "Avenue d'Annecy",
            "Avenue d'Avignon",
            "Avenue de Bayonne",
            "Avenue de Besançon",
            "Avenue de Brest",
            "Avenue de Caen",
            "Avenue de Calais",
            "Avenue de Cannes",
            "Avenue de Clermont-Ferrand",
            "Avenue de Colmar",
            "Avenue de La Rochelle",
            "Avenue du Havre",
            "Avenue de Limoges",
            "Avenue de Metz",
            "Avenue de Mulhouse",
            "Avenue de Nancy",
            "Avenue de Nîmes",
            "Avenue d'Orléans",
            "Avenue de Pau",
            "Avenue de Perpignan",
            "Avenue de Poitiers",
            "Avenue de Saint-Étienne",
            "Avenue de Toulon",
            "Avenue de Versailles",
            "Boulevard des Droits de l'Homme",
            "Boulevard de la Démocratie",
            "Boulevard de la Solidarité",
            "Boulevard de la Justice",
            "Boulevard de la Citoyenneté",
            "Boulevard de l'Avenir",
            "Boulevard du Progrès",
            "Boulevard Olympe de Gouges",
            "Boulevard Louise Michel",
            "Boulevard Simone de Beauvoir",
            "Boulevard Joséphine Baker",
            "Boulevard Lucie Aubrac",
            "Boulevard Albert Camus",
            "Boulevard Jules Verne",
            "Boulevard Émile Zola",
            "Boulevard René Descartes",
            "Boulevard des Acacias",
            "Boulevard des Chênes",
            "Boulevard des Fontaines",
            "Boulevard du Vieux Port",
            "Boulevard du Canal",
            "Boulevard de la Digue",
            "Boulevard de la Camargue",
            "Boulevard des Cévennes",
            "Boulevard du Vercors",
            "Boulevard du Mont-Blanc",
            "Boulevard de la Loire",
            "Boulevard de la Garonne",
            "Boulevard de la Corse",
            "Boulevard du Pays Basque",
            "Boulevard d'Amiens",
            "Boulevard d'Angers",
            "Boulevard d'Avignon",
            "Boulevard de Brest",
            "Boulevard de Caen",
            "Boulevard de Nîmes",
            "Boulevard d'Orléans",
            "Boulevard de Toulon",
            "Mail Olympe de Gouges",
            "Mail de la République",
            "Mail de la Liberté",
            "Mail de l'Europe",
            "Mail des Tilleuls",
            "Mail des Arts",
            "Mail du Parc",
            "Corniche du Littoral",
            "Corniche de la Côte",
            "Corniche des Roches",
            "Corniche du Soleil",
            "Corniche des Pins",
            "Rocade de l'Europe",
            "Rocade des Nations",
            "Rocade du Port",
            "Rocade de l'Aéroport",
            "Rocade de l'Université",
            "Voie de la Liberté",
            "Voie de l'Europe",
            "Voie des Arts",
            "Voie du Littoral",
            "Voie du Port",
            "Grande Rue de la République",
            "Grande Rue de la Liberté",
            "Grande Rue du Commerce",
            "Grande Rue Victor Hugo",
            "Grande Rue Jean Jaurès",
            "Promenade des Quatre Saisons",
            "Promenade du Front de Mer",
            "Promenade du Vieux Port",
            "Promenade de la Camargue",
            "Esplanade des Droits de l'Homme",
            "Esplanade de la Solidarité",
            "Esplanade de la Mémoire",
            "Esplanade Olympe de Gouges",
            "Esplanade Joséphine Baker"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Autoroute du Soleil",
            "Autoroute du Nord",
            "Autoroute de l'Est",
            "Autoroute de Normandie",
            "Autoroute de l'Ouest",
            "Autoroute des Estuaires",
            "Autoroute des Deux Mers",
            "Autoroute de l'Océane",
            "Autoroute Blanche",
            "Autoroute des Alpes",
            "Autoroute de la Méditerranée",
            "Autoroute du Littoral",
            "Autoroute des Pyrénées",
            "Autoroute des Vosges",
            "Autoroute de la Loire",
            "Autoroute de la Côte",
            "Autoroute des Vignes",
            "Autoroute des Lacs",
            "Autoroute du Centre",
            "Autoroute du Val de Loire",
            "Périphérique Nord",
            "Périphérique Sud",
            "Périphérique Est",
            "Périphérique Ouest",
            "Boulevard Périphérique",
            "Rocade Nord",
            "Rocade Sud",
            "Rocade Est",
            "Rocade Ouest",
            "Rocade du Centre",
            "Rocade des Alpes",
            "Rocade du Littoral",
            "Voie Express du Nord",
            "Voie Express du Sud",
            "Voie Express de l'Est",
            "Voie Express de l'Ouest",
            "Voie Express du Littoral",
            "Voie Express des Alpes",
            "Route des Alpes",
            "Route des Pyrénées",
            "Route du Littoral",
            "Route des Estuaires",
            "Route des Lacs",
            "Route du Soleil",
            "Route de l'Atlantique",
            "Route de la Méditerranée",
            "Bretelle du Nord",
            "Bretelle du Sud",
            "Bretelle de l'Est",
            "Bretelle de l'Ouest",
            "Bretelle de l'Aéroport",
            "Bretelle du Port",
            "Contournement Nord",
            "Contournement Sud",
            "Contournement Est",
            "Contournement Ouest",
            "Contournement du Centre",
            "Liaison Interurbaine Nord",
            "Liaison Interurbaine Sud",
            "Liaison des Deux Vallées",
            "Autoroute des Anglais",
            "Autoroute des Cigognes",
            "Autoroute des Titans",
            "Autoroute de la Maurienne",
            "Autoroute du Mont-Blanc",
            "Autoroute du Val de Durance",
            "Autoroute du Dauphiné",
            "Autoroute du Pastel",
            "Autoroute de la Côte Basque",
            "Autoroute de la Côte d'Azur",
            "Autoroute de la Camargue",
            "Autoroute des Cévennes",
            "Autoroute du Massif Central",
            "Autoroute du Bourbonnais",
            "Autoroute de la Bresse",
            "Autoroute des Ardennes",
            "Autoroute de la Champagne",
            "Autoroute de la Lorraine",
            "Autoroute de l'Alsace",
            "Autoroute de la Bretagne",
            "Autoroute de l'Anjou",
            "Autoroute du Poitou",
            "Autoroute du Limousin",
            "Autoroute de l'Aquitaine",
            "Autoroute du Languedoc",
            "Autoroute du Roussillon",
            "Autoroute de la Provence",
            "Autoroute de la Côte d'Opale",
            "Autoroute des Trois Frontières",
            "Autoroute des Quatre Vents",
            "Périphérique Intérieur",
            "Périphérique Extérieur",
            "Périphérique des Portes",
            "Périphérique de l'Aéroport",
            "Périphérique du Grand Centre",
            "Rocade Intérieure",
            "Rocade Extérieure",
            "Rocade des Ports",
            "Rocade de l'Aéroport",
            "Rocade de l'Université",
            "Rocade Industrielle",
            "Rocade des Deux Rives",
            "Rocade des Trois Vallées",
            "Voie Express des Estuaires",
            "Voie Express du Val de Loire",
            "Voie Express de la Côte",
            "Voie Express de la Camargue",
            "Voie Express des Cévennes",
            "Voie Express du Mont-Blanc",
            "Voie Express du Pays Basque",
            "Route Européenne de l'Atlantique",
            "Route Européenne de la Méditerranée",
            "Route Européenne des Alpes",
            "Route Européenne des Pyrénées",
            "Route des Trois Vallées",
            "Route des Deux Rives",
            "Route des Quatre Vents",
            "Route des Grands Lacs",
            "Route des Volcans",
            "Route des Châteaux",
            "Route des Vignobles",
            "Route du Val de Loire",
            "Route du Mont-Blanc",
            "Route de la Côte d'Azur",
            "Route de la Côte Basque",
            "Route de la Camargue",
            "Route des Cévennes",
            "Bretelle de la Gare",
            "Bretelle de l'Université",
            "Bretelle de la Zone Industrielle",
            "Bretelle du Centre Hospitalier",
            "Contournement Intérieur",
            "Contournement Extérieur",
            "Contournement de l'Aéroport",
            "Contournement du Port",
            "Contournement de la Zone Industrielle",
            "Contournement des Deux Rives",
            "Liaison Interurbaine Est-Ouest",
            "Liaison Interurbaine Nord-Sud",
            "Liaison du Littoral",
            "Liaison des Grands Lacs",
            "Liaison des Trois Vallées",
            "Axe Nord-Sud",
            "Axe Est-Ouest",
            "Axe du Littoral",
            "Axe des Deux Mers",
            "Axe des Alpes",
            "Axe des Pyrénées"
        };
    }
}
