// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class GermanRoadNames
    {
        internal static readonly string[] DirtBaseNames =
        {
            "Auen",
            "Bach",
            "Berg",
            "Birken",
            "Buchen",
            "Dorf",
            "Eichen",
            "Erlen",
            "Feld",
            "Fichten",
            "Föhren",
            "Forst",
            "Grenz",
            "Heide",
            "Hirten",
            "Höhen",
            "Hohl",
            "Hof",
            "Jagd",
            "Kastanien",
            "Kiefern",
            "Kirch",
            "Koppel",
            "Krähen",
            "Linden",
            "Moor",
            "Mühlen",
            "Obst",
            "Quellen",
            "Rosen",
            "Sand",
            "Schäfer",
            "Sonnen",
            "Stein",
            "Tal",
            "Tannen",
            "Wacholder",
            "Wald",
            "Weinberg",
            "Wiesen"
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Feldweg",
            "Waldweg",
            "Wiesenweg",
            "Forstweg",
            "Mühlenweg",
            "Hohlweg",
            "Kirchsteig",
            "Bergpfad",
            "Talweg",
            "Auweg",
            "Heideweg",
            "Koppelweg",
            "Weinbergweg",
            "Eichenweg",
            "Buchenweg",
            "Birkenweg",
            "Fichtenweg",
            "Kiefernweg",
            "Tannenweg",
            "Am Waldrand",
            "Am Mühlbach",
            "Am Feldrain",
            "Am Weinberg",
            "Durch die Aue",
            "Zur alten Mühle",
            "Zum Forsthaus",
            "Zum Steinbruch",
            "Zum Wiesengrund",
            "Alter Postweg",

            // Weitere ländliche Namen
            "Am alten Forst",
            "Am Auwald",
            "Am Bachlauf",
            "Am Birkengrund",
            "Am Buchenwald",
            "Am Eichenrain",
            "Am Heuweg",
            "Am Hochwald",
            "Am Hohlweg",
            "Am Krähenberg",
            "Am Moosgrund",
            "Am Moor",
            "Am Quellenhang",
            "Am Seegrund",
            "Am Waldbach",
            "An der Trift",
            "Im Auwald",
            "Im Bruch",
            "Im Feldgrund",
            "Im Wiesental",
            "Unter den Eichen",
            "Zur Jagdhütte",
            "Zur Schäferei",
            "Zur Waldhütte",
            "Zum Aussichtspunkt",
            "Zum Gutshof",
            "Zum Hochsitz",
            "Zum Jagdhaus",
            "Zum Moorgrund",
            "Zum Waldsee"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "Adler",
            "Anker",
            "Bäcker",
            "Bad",
            "Brunnen",
            "Burg",
            "Engel",
            "Färber",
            "Fischer",
            "Garten",
            "Gerber",
            "Hinter",
            "Kapellen",
            "Kaufmann",
            "Keller",
            "Kirch",
            "Kloster",
            "Korn",
            "Krämer",
            "Küfer",
            "Leder",
            "Löwen",
            "Markt",
            "Mauer",
            "Mühl",
            "Münz",
            "Pfarr",
            "Rathaus",
            "Rosen",
            "Salz",
            "Sattler",
            "Schloss",
            "Schmied",
            "Schuster",
            "Schwan",
            "Seiler",
            "Sonne",
            "Stern",
            "Töpfer",
            "Tor",
            "Trauben",
            "Turm",
            "Weber",
            "Zehnt",
            "Zoll"
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Kirchgasse",
            "Mühlgasse",
            "Rosengasse",
            "Schustergasse",
            "Fischergasse",
            "Bäckergasse",
            "Pfarrgasse",
            "Marktgasse",
            "Turmgasse",
            "Brunnengasse",
            "Hintergasse",
            "Kleine Gasse",
            "Klostergasse",
            "Burggasse",
            "Rathausgasse",
            "Gerbergasse",
            "Webergasse",
            "Schmiedgasse",
            "Zehntgasse",
            "Badgasse",
            "Kellergasse",
            "Schlossgasse",
            "Mauergasse",
            "Kapellengasse",
            "Färbergasse",
            "Torgasse",
            "Sackgasse",
            "Gartenpassage",
            "Marktpassage",
            "Rathauspassage",

            // Weitere historische und innerstädtische Namen
            "Adlergasse",
            "Alte Gasse",
            "Am Torbogen",
            "Ankergasse",
            "Enge Gasse",
            "Engelgasse",
            "Hinter dem Markt",
            "Hinter dem Rathaus",
            "Kornmarktgasse",
            "Krämergasse",
            "Krumme Gasse",
            "Kupfergasse",
            "Löwengasse",
            "Münzgasse",
            "Neue Gasse",
            "Obere Gasse",
            "Salzgasse",
            "Schwanengasse",
            "Seilergasse",
            "Sternengasse",
            "Töpfergasse",
            "Traubengasse",
            "Untere Gasse",
            "Zollgasse",
            "Zum Alten Tor"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            // Bäume und Pflanzen
            "Ahorn",
            "Akazien",
            "Birken",
            "Buchen",
            "Eichen",
            "Erlen",
            "Fichten",
            "Flieder",
            "Kastanien",
            "Kiefern",
            "Linden",
            "Nelken",
            "Pappel",
            "Rosen",
            "Tannen",
            "Tulpen",
            "Ulmen",
            "Weiden",

            // Vögel und Tiere
            "Amsel",
            "Biber",
            "Bussard",
            "Drossel",
            "Eulen",
            "Falken",
            "Finken",
            "Forellen",
            "Fuchs",
            "Hasen",
            "Hirsch",
            "Kranich",
            "Lerchen",
            "Meisen",
            "Möwen",
            "Reh",
            "Reiher",
            "Rotkehlchen",
            "Schwalben",
            "Staren",

            // Landschaft und Wohngebiet
            "Bach",
            "Berg",
            "Garten",
            "Heide",
            "Höhen",
            "Mühlen",
            "Park",
            "Quellen",
            "See",
            "Sonnen",
            "Tal",
            "Wald",
            "Wiesen"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Ahornweg",
            "Akazienweg",
            "Birkenweg",
            "Buchenweg",
            "Eichenweg",
            "Erlenweg",
            "Fichtenweg",
            "Kastanienweg",
            "Kiefernweg",
            "Lindenweg",
            "Pappelweg",
            "Tannenweg",
            "Ulmenweg",
            "Weidenweg",
            "Rosenweg",
            "Tulpenweg",
            "Nelkenweg",
            "Fliederweg",
            "Sonnenweg",
            "Gartenweg",
            "Amselweg",
            "Drosselweg",
            "Finkenweg",
            "Lerchenweg",
            "Meisenweg",
            "Falkenweg",
            "Am Birkenhain",
            "An der Linde",
            "Im Wiesengrund",
            "Am Stadtpark",
            "Am Sonnenhang",
            "Zum Feldrain",
            "Am Bach",
            "Im Grünen",
            "Am Anger",
            "Am Sportplatz",
            "Am Mühlengraben",
            "Am Eichenhain",
            "Im Rosengarten",
            "Im Talgrund",
            "Auf der Höhe",
            "An den Gärten",
            "Am Waldeck",
            "Am Seeufer",
            "Am Quellenweg",
            "Zum Lindenhof",

            // Weitere Wohngebiets- und Siedlungsnamen
            "Am Buchenhain",
            "Am Dorfanger",
            "Am Fichtenhang",
            "Am Gartenfeld",
            "Am Hasenrain",
            "Am Kastanienhof",
            "Am Mühlenpark",
            "Am Obstgarten",
            "Am Parkrand",
            "Am Rosenhang",
            "Am Tannenhof",
            "Am Waldsaum",
            "An den Linden",
            "Auf dem Berg",
            "Im Amselgrund",
            "Im Eichenhof",
            "Im Erlenhain",
            "Im Finkenpark",
            "Im Gartenhof",
            "Im Lindenpark",
            "Im Mühlenfeld",
            "Im Quellenhof",
            "Im Sonnenfeld",
            "Im Tannenhain",
            "Im Vogelgrund",
            "Im Waldgarten",
            "Im Weidengrund",
            "Unter den Birken",
            "Unter den Linden",
            "Zum Birkenhof",
            "Zum Eichenpark",
            "Zum Rosenhain",
            "Zum Sonnenhof",
            "Zum Waldgarten"
        };

        internal static readonly string[] StandardBaseNames =
        {
            // Orte und Einrichtungen
            "Bahnhof",
            "Berg",
            "Brücken",
            "Dorf",
            "Friedhof",
            "Garten",
            "Hafen",
            "Haupt",
            "Hof",
            "Hospital",
            "Industrie",
            "Kanal",
            "Kirch",
            "Kloster",
            "Markt",
            "Messe",
            "Mittel",
            "Mühlen",
            "Park",
            "Post",
            "Rathaus",
            "Schloss",
            "Schul",
            "See",
            "Tal",
            "Ufer",
            "Wald",
            "Wiesen",

            // Persönlichkeiten und historische Bezeichnungen
            "Alexander",
            "Augusta",
            "Bach",
            "Beethoven",
            "Bismarck",
            "Carl",
            "Dürer",
            "Friedrich",
            "Goethe",
            "Heinrich",
            "Hermann",
            "Johann",
            "Kant",
            "Kaiser",
            "König",
            "Lessing",
            "Luisen",
            "Luther",
            "Mozart",
            "Richard",
            "Robert",
            "Schiller",
            "Viktoria",
            "Wilhelm",

            // Allgemeine Bezeichnungen
            "Einheit",
            "Europa",
            "Freiheit",
            "Frieden",
            "Fürsten",
            "Grafen",
            "Handels",
            "Herzog",
            "Republik",
            "Verfassungs",
            "Werks"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Hauptstraße",
            "Bahnhofstraße",
            "Marktstraße",
            "Kirchstraße",
            "Schulstraße",
            "Gartenstraße",
            "Bergstraße",
            "Talstraße",
            "Waldstraße",
            "Wiesenstraße",
            "Dorfstraße",
            "Rathausstraße",
            "Poststraße",
            "Mühlenstraße",
            "Brückenstraße",
            "Uferstraße",
            "Seestraße",
            "Goethestraße",
            "Schillerstraße",
            "Lessingstraße",
            "Mozartstraße",
            "Beethovenstraße",
            "Bachstraße",
            "Bismarckstraße",
            "Kantstraße",
            "Lutherstraße",
            "Dürerstraße",
            "Friedrichstraße",
            "Wilhelmstraße",
            "Luisenstraße",
            "Augustastraße",
            "Schlossstraße",
            "Klosterstraße",
            "Hospitalstraße",
            "Friedhofstraße",
            "Hofstraße",
            "Mittelstraße",
            "Neue Straße",
            "Alte Straße",
            "Neustädter Straße",
            "Berliner Straße",
            "Hamburger Straße",
            "Münchner Straße",
            "Nürnberger Straße",
            "Leipziger Straße",
            "Dresdner Straße",
            "Kölner Straße",
            "Frankfurter Straße",
            "Bremer Straße",
            "Hannoversche Straße",
            "Stuttgarter Straße",
            "Regensburger Straße",
            "Bamberger Straße",
            "Coburger Straße",

            // Weitere Städte und Regionen
            "Aachener Straße",
            "Augsburger Straße",
            "Bayreuther Straße",
            "Bonner Straße",
            "Braunschweiger Straße",
            "Darmstädter Straße",
            "Dortmunder Straße",
            "Düsseldorfer Straße",
            "Erfurter Straße",
            "Essener Straße",
            "Flensburger Straße",
            "Freiburger Straße",
            "Gießener Straße",
            "Göttinger Straße",
            "Heidelberger Straße",
            "Jenaer Straße",
            "Karlsruher Straße",
            "Kasseler Straße",
            "Kieler Straße",
            "Koblenzer Straße",
            "Konstanzer Straße",
            "Lübecker Straße",
            "Magdeburger Straße",
            "Mainzer Straße",
            "Mannheimer Straße",
            "Oldenburger Straße",
            "Potsdamer Straße",
            "Rostocker Straße",
            "Saarbrücker Straße",
            "Schweriner Straße",
            "Trierer Straße",
            "Weimarer Straße",
            "Wiesbadener Straße",
            "Würzburger Straße",

            // Weitere klassische Straßennamen
            "Amtsstraße",
            "Burgstraße",
            "Fabrikstraße",
            "Feuerwehrstraße",
            "Grenzstraße",
            "Handelsstraße",
            "Kanalstraße",
            "Kreuzstraße",
            "Landwehrstraße",
            "Marienstraße",
            "Museumstraße",
            "Neue Heimat",
            "Oberstraße",
            "Ringstraße",
            "Unterstraße",
            "Werkstraße",
            "Zechenstraße"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "Campus",
            "Donau",
            "Elbe",
            "Europa",
            "Frieden",
            "Hafen",
            "Handels",
            "Industrie",
            "Innovations",
            "Isar",
            "Kaiser",
            "Kastanien",
            "Königs",
            "Kurfürsten",
            "Linden",
            "Main",
            "Messe",
            "Mosel",
            "Neckar",
            "Nord",
            "Ost",
            "Park",
            "Platanen",
            "Rhein",
            "Spree",
            "Stadtpark",
            "Süd",
            "Technologie",
            "Universitäts",
            "West",
            "Weser",
            "Zentral"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Berliner Allee",
            "Münchner Allee",
            "Kaiserallee",
            "Parkallee",
            "Stadtparkallee",
            "Europallee",
            "Friedensallee",
            "Messeallee",
            "Zentralallee",
            "Königsallee",
            "Maximilianstraße",
            "Kaiserstraße",
            "Kurfürstenstraße",
            "Konrad-Adenauer-Straße",
            "Friedrich-Ebert-Straße",
            "Theodor-Heuss-Straße",
            "Willy-Brandt-Straße",
            "Ernst-Reuter-Allee",
            "Geschwister-Scholl-Straße",
            "Sophie-Scholl-Allee",
            "Nordring",
            "Südring",
            "Ostring",
            "Westring",
            "Stadtring",
            "Innenstadtring",
            "Industriestraße",
            "Hafenstraße",
            "Messestraße",
            "Flughafenstraße",
            "Werner-von-Siemens-Straße",
            "Robert-Bosch-Straße",
            "Carl-Zeiss-Straße",
            "Europa-Ring",
            "Friedensring",
            "Stadtpark-Ring",
            "Nordallee",
            "Südallee",
            "Ostallee",
            "Westallee",

            // Weitere repräsentative Namen
            "Albert-Einstein-Allee",
            "Alexander-von-Humboldt-Allee",
            "August-Bebel-Straße",
            "Campusallee",
            "Donaupromenade",
            "Elbpromenade",
            "Erfinderstraße",
            "Europaboulevard",
            "Franz-Josef-Strauß-Allee",
            "Hafencity-Allee",
            "Innovationsallee",
            "Isarpromenade",
            "Karl-Marx-Allee",
            "Ludwig-Erhard-Straße",
            "Mainpromenade",
            "Marie-Curie-Allee",
            "Moselpromenade",
            "Neckarpromenade",
            "Platanenallee",
            "Rheinpromenade",
            "Spreepromenade",
            "Technologieallee",
            "Universitätsallee",
            "Weserpromenade",
            "Wissenschaftsallee",
            "Zentralring"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Nordtangente",
            "Südtangente",
            "Osttangente",
            "Westtangente",
            "Nordosttangente",
            "Nordwesttangente",
            "Südosttangente",
            "Südwesttangente",
            "Nordumfahrung",
            "Südumfahrung",
            "Ostumfahrung",
            "Westumfahrung",
            "Stadtumfahrung",
            "Ringautobahn",
            "Stadtautobahn",
            "Hafenautobahn",
            "Flughafenzubringer",
            "Messezubringer",
            "Industriezubringer",
            "Autobahnzubringer Nord",
            "Autobahnzubringer Süd",
            "Autobahnzubringer Ost",
            "Autobahnzubringer West",
            "Nord-Süd-Verbindung",
            "Ost-West-Verbindung",
            "Rhein-Main-Verbindung",
            "Stadtschnellweg",
            "Messeschnellweg",
            "Hafenschnellweg",
            "Industrieschnellweg",
            "Flughafenschnellstraße",
            "Metropolring",
            "Nordring-Autobahn",
            "Südring-Autobahn",
            "Ostring-Autobahn",
            "Westring-Autobahn",
            "Hafentangente",
            "Messetangente",
            "Umgehungsstraße Nord",
            "Umgehungsstraße Süd",
            "Umgehungsstraße Ost",
            "Umgehungsstraße West"
        };

        internal static readonly string[] DirtSuffixes =
        {
            "weg",
            "weg",
            "weg",
            "pfad",
            "pfad",
            "steig",
            "grund"
        };

        internal static readonly string[] AlleySuffixes =
        {
            "gasse",
            "gasse",
            "gasse",
            "passage",
            "hof",
            "winkel",
            "gang"
        };

        internal static readonly string[] ResidentialSuffixes =
        {
            "weg",
            "weg",
            "weg",
            "straße",
            "straße",
            "ring",
            "bogen",
            "höhe",
            "grund",
            "garten",
            "hain",
            "hof",
            "blick"
        };

        internal static readonly string[] StandardSuffixes =
        {
            "straße",
            "straße",
            "straße",
            "weg",
            "weg",
            "platz",
            "ring",
            "allee"
        };

        internal static readonly string[] AvenueSuffixes =
        {
            "allee",
            "allee",
            "allee",
            "ring",
            "ring",
            "straße",
            "promenade"
        };

    }
}
