// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

using System;
using System.Collections.Generic;

namespace RoadNameGenerator.Naming
{
    internal static class GermanRoadNames
    {
        internal static readonly string[] DirtBaseNames =
        {
            "Acker",
            "Ahorn",
            "Auen",
            "Bach",
            "Berg",
            "Birken",
            "Brombeer",
            "Bruch",
            "Buchen",
            "Damm",
            "Deich",
            "Dorf",
            "Ebereschen",
            "Eichen",
            "Erlen",
            "Eschen",
            "Farn",
            "Feld",
            "Felsen",
            "Fichten",
            "Föhren",
            "Forst",
            "Furt",
            "Ginster",
            "Grenz",
            "Hagebutten",
            "Hafer",
            "Hasel",
            "Hecken",
            "Heide",
            "Hirten",
            "Höhen",
            "Hohl",
            "Hof",
            "Holunder",
            "Hopfen",
            "Jagd",
            "Jagdwiesen",
            "Kastanien",
            "Kiefern",
            "Kirch",
            "Kirsch",
            "Klee",
            "Koppel",
            "Korn",
            "Krähen",
            "Kräuter",
            "Lärchen",
            "Linden",
            "Mohn",
            "Moor",
            "Moos",
            "Mühlen",
            "Nuss",
            "Obst",
            "Pappel",
            "Pflaumen",
            "Pilz",
            "Quellen",
            "Raps",
            "Reben",
            "Reh",
            "Ried",
            "Roggen",
            "Rosen",
            "Sand",
            "Schäfer",
            "Schilf",
            "Schlehen",
            "Schwalben",
            "Sonnen",
            "Stein",
            "Streuobst",
            "Tal",
            "Tannen",
            "Teich",
            "Trift",
            "Ulmen",
            "Wacholder",
            "Wald",
            "Waldmeister",
            "Weiden",
            "Weiher",
            "Weinberg",
            "Weizen",
            "Wiesen",
            "Wild",
            "Wurzel",
            "Zedern"
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Feldweg",
            "Waldweg",
            "Wiesenweg",
            "Forstweg",
            "Mühlenweg",
            "Hohlweg",
            "Kirchsteig",
            "Bergpfad",
            "Talweg",
            "Auweg",
            "Heideweg",
            "Koppelweg",
            "Weinbergweg",
            "Eichenweg",
            "Buchenweg",
            "Birkenweg",
            "Fichtenweg",
            "Kiefernweg",
            "Tannenweg",
            "Am Waldrand",
            "Am Mühlbach",
            "Am Feldrain",
            "Am Weinberg",
            "Durch die Aue",
            "Zur alten Mühle",
            "Zum Forsthaus",
            "Zum Steinbruch",
            "Zum Wiesengrund",
            "Alter Postweg",
            "Am alten Forst",
            "Am Auwald",
            "Am Bachlauf",
            "Am Birkengrund",
            "Am Buchenwald",
            "Am Eichenrain",
            "Am Heuweg",
            "Am Hochwald",
            "Am Hohlweg",
            "Am Krähenberg",
            "Am Moosgrund",
            "Am Moor",
            "Am Quellenhang",
            "Am Seegrund",
            "Am Waldbach",
            "An der Trift",
            "Im Auwald",
            "Im Bruch",
            "Im Feldgrund",
            "Im Wiesental",
            "Unter den Eichen",
            "Zur Jagdhütte",
            "Zur Schäferei",
            "Zur Waldhütte",
            "Zum Aussichtspunkt",
            "Zum Gutshof",
            "Zum Hochsitz",
            "Zum Jagdhaus",
            "Zum Moorgrund",
            "Zum Waldsee",
            "Am Bienenstand",
            "Am Brombeerhang",
            "Am Damm",
            "Am Deich",
            "Am Felsen",
            "Am Furtweg",
            "Am Ginsterhang",
            "Am Haselrain",
            "Am Kirschberg",
            "Am Kleefeld",
            "Am Kornfeld",
            "Am Lärchenwald",
            "Am Mohnfeld",
            "Am Nussberg",
            "Am Pflaumenrain",
            "Am Ried",
            "Am Schilfgürtel",
            "Am Schlehenhang",
            "Am Teich",
            "Am Weiher",
            "Am Weizenfeld",
            "Im Ackergrund",
            "Im Hopfengarten",
            "Im Kräutergarten",
            "Im Rehgrund",
            "Im Streuobst",
            "Im Wildgrund",
            "Zur alten Schäferei",
            "Zur Streuobstwiese",
            "Zum Bienenhaus",
            "Zum Forellenteich",
            "Zum Jagdrevier",
            "Zum Kräuterhof",
            "Zum Rehgehege",
            "Zum Waldmeistergrund"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "Adler",
            "Anker",
            "Apotheker",
            "Bäcker",
            "Bad",
            "Bader",
            "Böttcher",
            "Brauer",
            "Brunnen",
            "Buchbinder",
            "Burg",
            "Bürger",
            "Drechsler",
            "Engel",
            "Färber",
            "Fischer",
            "Fleischer",
            "Garten",
            "Gerber",
            "Glaser",
            "Goldschmied",
            "Hafner",
            "Hinter",
            "Hopfen",
            "Hutmacher",
            "Kapellen",
            "Kaufmann",
            "Keller",
            "Kessel",
            "Kirch",
            "Klöster",
            "Kloster",
            "Korbmacher",
            "Korn",
            "Krämer",
            "Küfer",
            "Kürschner",
            "Leder",
            "Löwen",
            "Maler",
            "Markt",
            "Mauer",
            "Maurer",
            "Metzger",
            "Mühl",
            "Müller",
            "Münz",
            "Pfarr",
            "Rathaus",
            "Rosen",
            "Salz",
            "Sattler",
            "Schloss",
            "Schmied",
            "Schneider",
            "Schreiner",
            "Schuster",
            "Schwan",
            "Seifensieder",
            "Seiler",
            "Sonne",
            "Steinmetz",
            "Stern",
            "Töpfer",
            "Tor",
            "Trauben",
            "Tuchmacher",
            "Turm",
            "Uhrmacher",
            "Wagner",
            "Weber",
            "Zehnt",
            "Zimmerer",
            "Zinngießer",
            "Zoll",
            "Zunft"
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Kirchgasse",
            "Mühlgasse",
            "Rosengasse",
            "Schustergasse",
            "Fischergasse",
            "Bäckergasse",
            "Pfarrgasse",
            "Marktgasse",
            "Turmgasse",
            "Brunnengasse",
            "Hintergasse",
            "Kleine Gasse",
            "Klostergasse",
            "Burggasse",
            "Rathausgasse",
            "Gerbergasse",
            "Webergasse",
            "Schmiedgasse",
            "Zehntgasse",
            "Badgasse",
            "Kellergasse",
            "Schlossgasse",
            "Mauergasse",
            "Kapellengasse",
            "Färbergasse",
            "Torgasse",
            "Sackgasse",
            "Gartenpassage",
            "Marktpassage",
            "Rathauspassage",
            "Adlergasse",
            "Alte Gasse",
            "Am Torbogen",
            "Ankergasse",
            "Enge Gasse",
            "Engelgasse",
            "Hinter dem Markt",
            "Hinter dem Rathaus",
            "Kornmarktgasse",
            "Krämergasse",
            "Krumme Gasse",
            "Kupfergasse",
            "Löwengasse",
            "Münzgasse",
            "Neue Gasse",
            "Obere Gasse",
            "Salzgasse",
            "Schwanengasse",
            "Seilergasse",
            "Sternengasse",
            "Töpfergasse",
            "Traubengasse",
            "Untere Gasse",
            "Zollgasse",
            "Zum Alten Tor",
            "Apothekergasse",
            "Badergasse",
            "Böttchergasse",
            "Braugasse",
            "Buchbindergasse",
            "Drechslergasse",
            "Fleischergasse",
            "Glasergasse",
            "Goldschmiedgasse",
            "Hafnergasse",
            "Hutmacherwinkel",
            "Korbmachergasse",
            "Kürschnergasse",
            "Malergasse",
            "Maurergasse",
            "Metzgergasse",
            "Müllergasse",
            "Schneidergasse",
            "Schreinergasse",
            "Seifensiedergasse",
            "Steinmetzgasse",
            "Tuchmachergasse",
            "Uhrmachergasse",
            "Wagnergasse",
            "Zimmerergasse",
            "Zinngießergasse",
            "Zunftgasse",
            "Alte Zunftpassage",
            "Handwerkerhof",
            "Kleiner Marktgang",
            "Mühlenwinkel",
            "Rathauswinkel",
            "Schlosswinkel",
            "Stadtmauergang"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            "Ahorn",
            "Akazien",
            "Alpen",
            "Amsel",
            "Apfel",
            "Aprikosen",
            "Auen",
            "Azaleen",
            "Bach",
            "Berg",
            "Bergwald",
            "Bergwiesen",
            "Biber",
            "Bienen",
            "Birken",
            "Blumen",
            "Bodensee",
            "Brombeer",
            "Buchen",
            "Bussard",
            "Chiemsee",
            "Dachs",
            "Dahlien",
            "Donau",
            "Dorfanger",
            "Drossel",
            "Ebereschen",
            "Edelweiß",
            "Eichen",
            "Eichhörnchen",
            "Elbe",
            "Elster",
            "Erika",
            "Erlen",
            "Eschen",
            "Falken",
            "Farn",
            "Fasanen",
            "Fichten",
            "Finken",
            "Flieder",
            "Fluss",
            "Forsythien",
            "Föhren",
            "Frankenwald",
            "Gänse",
            "Garten",
            "Gartenstadt",
            "Geranien",
            "Ginster",
            "Glockenblumen",
            "Goldregen",
            "Glyzinien",
            "Habicht",
            "Hagebutten",
            "Hain",
            "Harz",
            "Hasel",
            "Hasen",
            "Heide",
            "Heidelbeer",
            "Heimat",
            "Himmel",
            "Hirsch",
            "Holunder",
            "Horizont",
            "Hortensien",
            "Hügel",
            "Hummeln",
            "Igel",
            "Iris",
            "Jagst",
            "Jasmin",
            "Kalkstein",
            "Kamelien",
            "Kanal",
            "Kastanien",
            "Kiefern",
            "Kirschen",
            "Klee",
            "Kocher",
            "Koppel",
            "Kornblumen",
            "Kranich",
            "Krokus",
            "Lahn",
            "Lärchen",
            "Lavendel",
            "Lech",
            "Lerchen",
            "Libellen",
            "Lilien",
            "Linden",
            "Luchse",
            "Lupinen",
            "Magnolien",
            "Maiglöckchen",
            "Main",
            "Malven",
            "Marder",
            "Margeriten",
            "Meisen",
            "Möwen",
            "Mohn",
            "Mond",
            "Moos",
            "Mosel",
            "Mühlen",
            "Müritz",
            "Nahe",
            "Nachtigallen",
            "Narzissen",
            "Neckar",
            "Nelken",
            "Nordsee",
            "Nuss",
            "Odenwald",
            "Oder",
            "Orchideen",
            "Park",
            "Parkblick",
            "Pappel",
            "Pegnitz",
            "Petunien",
            "Pfauen",
            "Pfingstrosen",
            "Pflaumen",
            "Pirol",
            "Primeln",
            "Quellen",
            "Rain",
            "Rebhuhn",
            "Regnitz",
            "Reh",
            "Reiher",
            "Rhein",
            "Rhododendron",
            "Rhön",
            "Ried",
            "Rosen",
            "Rotkehlchen",
            "Rotmilan",
            "Ruhr",
            "Saale",
            "Saar",
            "Salamander",
            "Salbei",
            "Schafe",
            "Schlehen",
            "Schmetterling",
            "Schneeglöckchen",
            "Schwalben",
            "Schwäne",
            "Schwarzwald",
            "See",
            "Seeblick",
            "Seeufer",
            "Sonnen",
            "Sonnenaufgang",
            "Sonnenblumen",
            "Sonnenuntergang",
            "Spechte",
            "Spessart",
            "Spree",
            "Staren",
            "Steigerwald",
            "Stieglitz",
            "Störche",
            "Tauben",
            "Tal",
            "Talblick",
            "Tannen",
            "Taunus",
            "Thymian",
            "Thüringerwald",
            "Tulpen",
            "Turmfalken",
            "Uhus",
            "Ulmen",
            "Veilchen",
            "Wacholder",
            "Wachteln",
            "Wald",
            "Waldrand",
            "Waldsaum",
            "Waldsee",
            "Waldwiese",
            "Weiden",
            "Weinreben",
            "Weißdorn",
            "Weitblick",
            "Werra",
            "Weser",
            "Wicken",
            "Wiesen",
            "Wiesenrain",
            "Wildenten",
            "Wildgänse",
            "Wildkatzen",
            "Wildschwein",
            "Wiesel",
            "Wolken",
            "Zedern"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Ahornweg",
            "Akazienweg",
            "Birkenweg",
            "Buchenweg",
            "Eichenweg",
            "Erlenweg",
            "Fichtenweg",
            "Kastanienweg",
            "Kiefernweg",
            "Lindenweg",
            "Pappelweg",
            "Tannenweg",
            "Ulmenweg",
            "Weidenweg",
            "Rosenweg",
            "Tulpenweg",
            "Nelkenweg",
            "Fliederweg",
            "Sonnenweg",
            "Gartenweg",
            "Amselweg",
            "Drosselweg",
            "Finkenweg",
            "Lerchenweg",
            "Meisenweg",
            "Falkenweg",
            "Am Birkenhain",
            "An der Linde",
            "Im Wiesengrund",
            "Am Stadtpark",
            "Am Sonnenhang",
            "Zum Feldrain",
            "Am Bach",
            "Im Grünen",
            "Am Anger",
            "Am Sportplatz",
            "Am Mühlengraben",
            "Am Eichenhain",
            "Im Rosengarten",
            "Im Talgrund",
            "Auf der Höhe",
            "An den Gärten",
            "Am Waldeck",
            "Am Seeufer",
            "Am Quellenweg",
            "Zum Lindenhof",
            "Am Buchenhain",
            "Am Dorfanger",
            "Am Fichtenhang",
            "Am Gartenfeld",
            "Am Hasenrain",
            "Am Kastanienhof",
            "Am Mühlenpark",
            "Am Obstgarten",
            "Am Parkrand",
            "Am Rosenhang",
            "Am Tannenhof",
            "Am Waldsaum",
            "An den Linden",
            "Auf dem Berg",
            "Im Amselgrund",
            "Im Eichenhof",
            "Im Erlenhain",
            "Im Finkenpark",
            "Im Gartenhof",
            "Im Lindenpark",
            "Im Mühlenfeld",
            "Im Quellenhof",
            "Im Sonnenfeld",
            "Im Tannenhain",
            "Im Vogelgrund",
            "Im Waldgarten",
            "Im Weidengrund",
            "Unter den Birken",
            "Unter den Linden",
            "Zum Birkenhof",
            "Zum Eichenpark",
            "Zum Rosenhain",
            "Zum Sonnenhof",
            "Zum Waldgarten",
            "Am Alpenblick",
            "Am Bergwald",
            "Am Blumenrain",
            "Am Bodensee",
            "Am Chiemseeblick",
            "Am Donauufer",
            "Am Elbufer",
            "Am Frankenwald",
            "Am Harzblick",
            "Am Mainufer",
            "Am Moselblick",
            "Am Neckarbogen",
            "Am Rheinufer",
            "Am Rhönblick",
            "Am Saaleufer",
            "Am Schwarzwaldrand",
            "Am Spessartblick",
            "Am Taunushang",
            "Am Weserbogen",
            "Im Odenwald",
            "Im Steigerwald",
            "Im Thüringerwald",
            "Zum Seeblick",
            "Zum Talblick",
            "Zum Waldsee"
        };

        internal static readonly string[] StandardBaseNames =
        {
            "Abbe",
            "Adenauer",
            "Alexander",
            "Alfred-Nobel",
            "Alpen",
            "Altstadt",
            "Amts",
            "Arendt",
            "Augusta",
            "Bach",
            "Bahn",
            "Bahnhof",
            "Bamberg",
            "Bayerwald",
            "Bayern",
            "Beethoven",
            "Benz",
            "Berg",
            "Berlin",
            "Bismarck",
            "Bonhoeffer",
            "Bosch",
            "Brecht",
            "Bremen",
            "Braun",
            "Brahms",
            "Brücken",
            "Bunsen",
            "Carl",
            "Clara-Schumann",
            "Coburg",
            "Daimler",
            "Diesel",
            "Dorf",
            "Dresden",
            "Dürer",
            "Einheit",
            "Einstein",
            "Eichendorff",
            "Eifel",
            "Elbe",
            "Erzgebirge",
            "Europa",
            "Fichtelgebirge",
            "Fontane",
            "Franken",
            "Frankenwald",
            "Frankfurt",
            "Fraunhofer",
            "Freiheit",
            "Frieden",
            "Friedrich",
            "Gauß",
            "Geschwister-Scholl",
            "Goethe",
            "Gropius",
            "Grimm",
            "Gutenberg",
            "Hafen",
            "Hahn",
            "Hamburg",
            "Handels",
            "Händel",
            "Hannover",
            "Harz",
            "Haupt",
            "Hauptmann",
            "Hegel",
            "Heine",
            "Heisenberg",
            "Helmholtz",
            "Herder",
            "Herzog",
            "Hesse",
            "Hertz",
            "Hof",
            "Hölderlin",
            "Hospital",
            "Humboldt",
            "Industrie",
            "Johann",
            "Juchacz",
            "Kaiser",
            "Kant",
            "Kästner",
            "Kepler",
            "Kleist",
            "Kloster",
            "Koch",
            "Köln",
            "König",
            "Kopernikus",
            "Leibniz",
            "Leipzig",
            "Lessing",
            "Lilienthal",
            "Linde",
            "Luisen",
            "Luther",
            "Main",
            "Mann",
            "Markt",
            "Maybach",
            "Meitner",
            "Mendelssohn",
            "Messe",
            "Mittel",
            "Mozart",
            "Mühlen",
            "München",
            "Nahe",
            "Neckar",
            "Newton",
            "Nürnberg",
            "Odenwald",
            "Ohm",
            "Otto",
            "Park",
            "Pasteur",
            "Planck",
            "Post",
            "Potsdam",
            "Raabe",
            "Rathaus",
            "Republik",
            "Rhein",
            "Rhön",
            "Rilke",
            "Röntgen",
            "Ruhr",
            "Saale",
            "Saar",
            "Schiller",
            "Schinkel",
            "Schloss",
            "Scholl",
            "Schul",
            "Schumann",
            "Schwarzwald",
            "Schweitzer",
            "Semper",
            "Siemens",
            "Spessart",
            "Spree",
            "Stauffenberg",
            "Steigerwald",
            "Stuttgart",
            "Storm",
            "Taunus",
            "Thomas-Mann",
            "Thüringer",
            "Tucholsky",
            "Ufer",
            "Uhland",
            "Verfassungs",
            "Viktoria",
            "Virchow",
            "Wagner",
            "Wald",
            "Werks",
            "Weser",
            "Wieland",
            "Wilhelm",
            "Zetkin",
            "Zeppelin",
            "Zuse"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Hauptstraße",
            "Bahnhofstraße",
            "Marktstraße",
            "Kirchstraße",
            "Schulstraße",
            "Gartenstraße",
            "Bergstraße",
            "Talstraße",
            "Waldstraße",
            "Wiesenstraße",
            "Dorfstraße",
            "Rathausstraße",
            "Poststraße",
            "Mühlenstraße",
            "Brückenstraße",
            "Uferstraße",
            "Seestraße",
            "Goethestraße",
            "Schillerstraße",
            "Lessingstraße",
            "Mozartstraße",
            "Beethovenstraße",
            "Bachstraße",
            "Bismarckstraße",
            "Kantstraße",
            "Lutherstraße",
            "Dürerstraße",
            "Friedrichstraße",
            "Wilhelmstraße",
            "Luisenstraße",
            "Augustastraße",
            "Schlossstraße",
            "Klosterstraße",
            "Hospitalstraße",
            "Friedhofstraße",
            "Hofstraße",
            "Mittelstraße",
            "Neue Straße",
            "Alte Straße",
            "Neustädter Straße",
            "Berliner Straße",
            "Hamburger Straße",
            "Münchner Straße",
            "Nürnberger Straße",
            "Leipziger Straße",
            "Dresdner Straße",
            "Kölner Straße",
            "Frankfurter Straße",
            "Bremer Straße",
            "Hannoversche Straße",
            "Stuttgarter Straße",
            "Regensburger Straße",
            "Bamberger Straße",
            "Coburger Straße",
            "Aachener Straße",
            "Augsburger Straße",
            "Bayreuther Straße",
            "Bonner Straße",
            "Braunschweiger Straße",
            "Darmstädter Straße",
            "Dortmunder Straße",
            "Düsseldorfer Straße",
            "Erfurter Straße",
            "Essener Straße",
            "Flensburger Straße",
            "Freiburger Straße",
            "Gießener Straße",
            "Göttinger Straße",
            "Heidelberger Straße",
            "Jenaer Straße",
            "Karlsruher Straße",
            "Kasseler Straße",
            "Kieler Straße",
            "Koblenzer Straße",
            "Konstanzer Straße",
            "Lübecker Straße",
            "Magdeburger Straße",
            "Mainzer Straße",
            "Mannheimer Straße",
            "Oldenburger Straße",
            "Potsdamer Straße",
            "Rostocker Straße",
            "Saarbrücker Straße",
            "Schweriner Straße",
            "Trierer Straße",
            "Weimarer Straße",
            "Wiesbadener Straße",
            "Würzburger Straße",
            "Adenauerstraße",
            "Einsteinstraße",
            "Humboldtstraße",
            "Kleiststraße",
            "Fontanestraße",
            "Heinestraße",
            "Hessestraße",
            "Kollwitzstraße",
            "Thomas-Mann-Straße",
            "Brechtstraße",
            "Grimmstraße",
            "Gutenbergstraße",
            "Keplerstraße",
            "Gaußstraße",
            "Röntgenstraße",
            "Planckstraße",
            "Hertzstraße",
            "Dieselstraße",
            "Benzstraße",
            "Daimlerstraße",
            "Boschstraße",
            "Siemensstraße",
            "Zeppelinstraße",
            "Lilienthalstraße",
            "Schweitzerstraße",
            "Bonhoefferstraße",
            "Kästnerstraße",
            "Tucholskystraße",
            "Stormstraße",
            "Eichendorffstraße",
            "Uhlandstraße",
            "Hölderlinstraße",
            "Herderstraße",
            "Rilkestraße",
            "Mendelssohnstraße",
            "Brahmsstraße",
            "Wagnerstraße",
            "Schumannstraße",
            "Clara-Schumann-Straße",
            "Geschwister-Scholl-Straße",
            "Marie-Juchacz-Straße",
            "Stauffenbergstraße",
            "Amtsstraße",
            "Burgstraße",
            "Handelsstraße",
            "Industriestraße",
            "Messestraße",
            "Werkstraße",
            "Europastraße",
            "Freiheitsstraße",
            "Friedensstraße",
            "Republikstraße"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "Adenauer",
            "Ahorn",
            "Akazien",
            "Alpen",
            "Altmühl",
            "Apfel",
            "Azaleen",
            "Bayern",
            "Beethoven",
            "Birken",
            "Bodensee",
            "Brahms",
            "Buchen",
            "Chiemsee",
            "Dahlien",
            "Donau",
            "Eichen",
            "Einstein",
            "Elbe",
            "Erzgebirge",
            "Eschen",
            "Europa",
            "Fichtelgebirge",
            "Fichten",
            "Flieder",
            "Forsythien",
            "Franken",
            "Frankenwald",
            "Freiheit",
            "Ginkgo",
            "Goethe",
            "Harz",
            "Hasel",
            "Havel",
            "Holunder",
            "Hortensien",
            "Humboldt",
            "Inn",
            "Jasmin",
            "Kamelien",
            "Kastanien",
            "Kirsch",
            "Lahn",
            "Lärchen",
            "Lavendel",
            "Lech",
            "Lilien",
            "Linden",
            "Magnolien",
            "Main",
            "Maiglöckchen",
            "Mosel",
            "Müritz",
            "Nahe",
            "Neckar",
            "Nordsee",
            "Odenwald",
            "Oder",
            "Ostsee",
            "Park",
            "Pappel",
            "Pegnitz",
            "Regnitz",
            "Rhein",
            "Rheinland",
            "Rhododendron",
            "Rhön",
            "Robinien",
            "Rosen",
            "Ruhr",
            "Saale",
            "Saar",
            "Sachsen",
            "Schiller",
            "Schumann",
            "Schwarzwald",
            "See",
            "Sonnenblumen",
            "Spessart",
            "Spree",
            "Steigerwald",
            "Taunus",
            "Tannen",
            "Thüringen",
            "Ulmen",
            "Wagner",
            "Weiden",
            "Weißdorn",
            "Weser",
            "Wildrosen",
            "Zedern"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Unter den Linden",
            "Königsallee",
            "Kurfürstendamm",
            "Rheinallee",
            "Moselpromenade",
            "Donaupromenade",
            "Elbpromenade",
            "Mainpromenade",
            "Neckarpromenade",
            "Parkallee",
            "Schlossallee",
            "Bahnhofsallee",
            "Universitätsallee",
            "Messeallee",
            "Europaboulevard",
            "Friedensboulevard",
            "Freiheitsboulevard",
            "Alpenboulevard",
            "Rheinboulevard",
            "Seepromenade",
            "Uferpromenade",
            "Stadtpromenade",
            "Ringpromenade",
            "Goetheallee",
            "Schillerallee",
            "Beethovenallee",
            "Mozartallee",
            "Brahmsallee",
            "Wagnerallee",
            "Humboldtallee",
            "Einsteinallee",
            "Adenauerallee",
            "Alpenallee",
            "Bodenseeallee",
            "Chiemseeallee",
            "Harzallee",
            "Rhönallee",
            "Schwarzwaldallee",
            "Spessartallee",
            "Taunusallee",
            "Frankenallee",
            "Bayernboulevard",
            "Sachsenboulevard",
            "Thüringenboulevard",
            "Nordseepromenade",
            "Ostseepromenade"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Avus",
            "Berliner Ring",
            "Münchner Ring",
            "Frankfurter Kreuz",
            "Kölner Ring",
            "Ruhrschnellweg",
            "Sauerlandlinie",
            "Hansalinie",
            "Eifelautobahn",
            "Moseltalautobahn",
            "Rheintalautobahn",
            "Bodenseeautobahn",
            "Alpenautobahn",
            "Nordseeautobahn",
            "Ostseeautobahn",
            "Elbtalautobahn",
            "Donautalautobahn",
            "Mainfrankenautobahn",
            "Thüringer-Wald-Autobahn",
            "Frankenwaldautobahn",
            "Schwarzwaldautobahn",
            "Harzautobahn",
            "Rhönautobahn",
            "Metropolroute Nord",
            "Metropolroute Süd",
            "Metropolroute Ost",
            "Metropolroute West",
            "Nordkorridor",
            "Südkorridor",
            "Ostkorridor",
            "Westkorridor",
            "Rheinlandtangente",
            "Mainfranken-Schnellweg",
            "Elbtal-Schnellweg",
            "Donautal-Schnellweg",
            "Oberrhein-Schnellweg",
            "Ruhrtal-Schnellweg",
            "Alpenzubringer",
            "Nordseezubringer",
            "Ostseezubringer",
            "Hafenzubringer Nord",
            "Hafenzubringer Süd",
            "Flughafenzubringer Nord",
            "Flughafenzubringer Süd",
            "Messezubringer Nord",
            "Messezubringer Süd",
            "Industriekorridor Nord",
            "Industriekorridor Süd",
            "Stadtring Nord",
            "Stadtring Süd",
            "Stadtring Ost",
            "Stadtring West",
            "Außenring Nord",
            "Außenring Süd",
            "Außenring Ost",
            "Außenring West",
            "Metropolring Nord",
            "Metropolring Süd",
            "Rhein-Main-Korridor",
            "Rhein-Ruhr-Korridor",
            "Elbe-Saale-Korridor",
            "Donau-Isar-Korridor",
            "Neckar-Alb-Korridor",
            "Nord-Süd-Achse",
            "Ost-West-Achse",
            "Mitteldeutsche Achse",
            "Norddeutsche Küstenroute",
            "Süddeutsche Alpenroute",
            "Westdeutsche Rheinschiene",
            "Ostdeutsche Seenroute",
            "Franken-Sachsen-Korridor",
            "Hessen-Thüringen-Korridor",
            "Bayern-Böhmen-Korridor"
        };

        internal static readonly string[] DirtSuffixes =
        {
            "weg", "weg", "weg", "pfad", "steig", "trift"
        };

        internal static readonly string[] AlleySuffixes =
        {
            "gasse", "gasse", "gang", "hof", "winkel", "passage"
        };

        internal static readonly string[] ResidentialSuffixes =
        {
            "weg", "weg", "straße", "straße", "ring", "hof", "bogen",
            "stieg", "pfad", "allee", "garten", "höhe"
        };

        internal static readonly string[] StandardSuffixes =
        {
            "straße", "straße", "weg", "platz", "ring", "damm"
        };

        internal static readonly string[] AvenueSuffixes =
        {
            "allee", "allee", "boulevard", "promenade", "ring"
        };
    }
}
