// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class ItalianRoadNames
    {
        internal static readonly string[] DirtPrefixes =
        {
            "Strada",
            "Strada",
            "Strada Vicinale",
            "Strada Comunale",
            "Sentiero",
            "Sentiero",
            "Cammino",
            "Tratturo",
            "Mulattiera"
        };

        internal static readonly string[] DirtBaseNames =
        {
            "dei Campi",
            "delle Vigne",
            "degli Ulivi",
            "dei Cipressi",
            "dei Castagni",
            "dei Pini",
            "dei Gelsi",
            "dei Noci",
            "dei Faggi",
            "del Bosco",
            "del Poggio",
            "del Colle",
            "del Monte",
            "del Lago",
            "del Torrente",
            "del Mulino",
            "del Castello",
            "del Convento",
            "del Casale",
            "del Fontanile",
            "del Belvedere",
            "della Valle",
            "della Fonte",
            "della Quercia",
            "della Rovere",
            "della Pineta",
            "della Cascina",
            "della Pieve",
            "della Serra",
            "della Montagna",
            "della Campagna",
            "della Costa",
            "della Rocca",
            "delle Colline",
            "delle Fontane",
            "delle Ginestre",
            "delle Rose",
            "delle Acacie",
            "delle Betulle",
            "di Mezzo",
            "di Sopra",
            "di Sotto",
            "della Vecchia Ferrovia",
            "dell'Abbazia",
            "dell'Orto",
            "dell'Olmo",
            "dell'Argine"
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Strada Bianca",
            "Strada dei Poderi",
            "Strada delle Masserie",
            "Strada della Bonifica",
            "Strada del Vigneto",
            "Strada dell'Oliveto",
            "Strada del Frantoio",
            "Strada del Granaio",
            "Strada del Fienile",
            "Strada del Borgo Vecchio",
            "Strada della Tenuta",
            "Strada della Riserva",
            "Strada del Bosco Alto",
            "Strada della Valle Verde",
            "Strada delle Colline",
            "Strada Vicinale dei Mulini",
            "Strada Vicinale delle Vigne",
            "Strada Vicinale della Pieve",
            "Strada Vicinale del Casale",
            "Sentiero degli Ulivi",
            "Sentiero dei Cipressi",
            "Sentiero delle Ginestre",
            "Sentiero del Castagno",
            "Sentiero della Rocca",
            "Cammino di San Luca",
            "Cammino di San Francesco",
            "Cammino della Valle",
            "Tratturo del Piano",
            "Tratturo della Murgia",
            "Mulattiera del Monte"
        };

        internal static readonly string[] AlleyPrefixes =
        {
            "Vicolo",
            "Vicolo",
            "Vicolo",
            "Via",
            "Calle",
            "Calle",
            "Salita",
            "Discesa",
            "Passaggio",
            "Sottoportico"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "dell'Arco",
            "del Campanile",
            "della Torre",
            "del Forno",
            "del Pozzo",
            "del Gallo",
            "del Leone",
            "della Luna",
            "del Sole",
            "della Stella",
            "della Volpe",
            "del Gatto",
            "dei Fabbri",
            "dei Mercanti",
            "dei Pescatori",
            "dei Muratori",
            "dei Tessitori",
            "dei Calderai",
            "dei Vasai",
            "dei Bottai",
            "delle Mura",
            "delle Rose",
            "delle Campane",
            "delle Logge",
            "delle Colonne",
            "delle Botteghe",
            "della Fontana",
            "della Chiesa",
            "della Canonica",
            "della Dogana",
            "della Zecca",
            "del Mercato",
            "del Porto",
            "del Teatro",
            "del Castello",
            "del Palazzo",
            "del Chiostro",
            "del Borgo",
            "San Luca",
            "San Marco",
            "San Pietro",
            "San Paolo",
            "Santa Lucia",
            "Santa Maria",
            "Sant'Antonio",
            "Sant'Anna",
            "della Pace",
            "dell'Olmo",
            "del Gelso",
            "della Quercia"
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Vicolo Stretto",
            "Vicolo Corto",
            "Vicolo del Centro",
            "Vicolo della Porta",
            "Vicolo delle Mura",
            "Vicolo del Campanile",
            "Vicolo della Torre",
            "Vicolo del Forno",
            "Vicolo del Pozzo",
            "Vicolo dei Fabbri",
            "Vicolo dei Mercanti",
            "Vicolo dei Pescatori",
            "Vicolo delle Botteghe",
            "Vicolo del Borgo",
            "Vicolo San Luca",
            "Vicolo Santa Lucia",
            "Calle Lunga",
            "Calle Stretta",
            "Calle del Forno",
            "Calle della Chiesa",
            "Calle dei Mercanti",
            "Calle del Teatro",
            "Calle del Porto",
            "Salita al Castello",
            "Salita alla Rocca",
            "Salita del Campanile",
            "Discesa al Porto",
            "Discesa del Mercato",
            "Passaggio delle Logge",
            "Sottoportico della Torre"
        };

        internal static readonly string[] ResidentialPrefixes =
        {
            "Via",
            "Via",
            "Via",
            "Via",
            "Viale",
            "Vicolo",
            "Piazzetta"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            "dei Gelsi",
            "dei Pini",
            "dei Tigli",
            "dei Pioppi",
            "dei Platani",
            "dei Cedri",
            "dei Larici",
            "dei Noci",
            "dei Castagni",
            "dei Faggi",
            "dei Salici",
            "degli Ulivi",
            "degli Oleandri",
            "degli Aceri",
            "degli Abeti",
            "delle Rose",
            "delle Viole",
            "delle Ginestre",
            "delle Camelie",
            "delle Magnolie",
            "delle Mimose",
            "delle Azalee",
            "delle Orchidee",
            "delle Betulle",
            "delle Acacie",
            "della Quercia",
            "della Rovere",
            "della Pineta",
            "del Glicine",
            "del Biancospino",
            "del Rosmarino",
            "della Lavanda",
            "del Giardino",
            "del Parco",
            "del Sole",
            "della Luna",
            "delle Stelle",
            "dell'Alba",
            "del Tramonto",
            "della Primavera",
            "della Serenità",
            "della Pace",
            "dell'Amicizia",
            "della Concordia",
            "del Belvedere",
            "della Collina",
            "della Valle",
            "del Lago",
            "del Torrente",
            "del Mulino",
            "San Giorgio",
            "San Lorenzo",
            "San Michele",
            "San Rocco",
            "Santa Chiara",
            "Santa Rita",
            "Santa Teresa"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Via dei Gelsi",
            "Via dei Tigli",
            "Via dei Platani",
            "Via dei Cedri",
            "Via dei Castagni",
            "Via degli Ulivi",
            "Via delle Rose",
            "Via delle Viole",
            "Via delle Ginestre",
            "Via delle Magnolie",
            "Via delle Mimose",
            "Via della Quercia",
            "Via della Pineta",
            "Via del Glicine",
            "Via della Lavanda",
            "Via del Giardino",
            "Via del Parco",
            "Via del Sole",
            "Via della Luna",
            "Via delle Stelle",
            "Via dell'Alba",
            "Via del Tramonto",
            "Via della Primavera",
            "Via della Serenità",
            "Via della Pace",
            "Via dell'Amicizia",
            "Via della Concordia",
            "Via del Belvedere",
            "Via della Collina",
            "Via della Valle",
            "Via del Lago",
            "Via del Mulino",
            "Via San Giorgio",
            "Via San Lorenzo",
            "Via San Michele",
            "Via San Rocco",
            "Via Santa Chiara",
            "Via Santa Rita",
            "Viale dei Pini",
            "Viale delle Rose",
            "Viale della Pineta",
            "Piazzetta del Sole",
            "Piazzetta delle Rose"
        };

        internal static readonly string[] StandardPrefixes =
        {
            "Via",
            "Via",
            "Via",
            "Corso",
            "Corso",
            "Piazza",
            "Largo"
        };

        internal static readonly string[] StandardBaseNames =
        {
            "Roma",
            "Italia",
            "Europa",
            "della Repubblica",
            "dell'Unità",
            "della Libertà",
            "della Vittoria",
            "della Costituzione",
            "dell'Indipendenza",
            "della Resistenza",
            "della Pace",
            "del Lavoro",
            "del Popolo",
            "del Comune",
            "del Municipio",
            "della Stazione",
            "del Mercato",
            "del Duomo",
            "della Chiesa",
            "del Teatro",
            "dell'Ospedale",
            "delle Scuole",
            "dell'Università",
            "dell'Industria",
            "dell'Artigianato",
            "del Commercio",
            "del Porto",
            "della Marina",
            "del Castello",
            "della Rocca",
            "delle Mura",
            "della Fontana",
            "del Ponte",
            "del Canale",
            "del Molino",
            "Dante Alighieri",
            "Giuseppe Garibaldi",
            "Giuseppe Mazzini",
            "Camillo Benso di Cavour",
            "Guglielmo Marconi",
            "Alessandro Volta",
            "Galileo Galilei",
            "Leonardo da Vinci",
            "Michelangelo Buonarroti",
            "Raffaello Sanzio",
            "Cristoforo Colombo",
            "Amerigo Vespucci",
            "Marco Polo",
            "Giacomo Leopardi",
            "Alessandro Manzoni",
            "Giovanni Pascoli",
            "Giosuè Carducci",
            "Luigi Pirandello",
            "Enrico Fermi",
            "Antonio Meucci",
            "Giuseppe Verdi",
            "Giacomo Puccini",
            "Gioachino Rossini",
            "Antonio Vivaldi",
            "Vittorio Emanuele II",
            "Umberto I",
            "XX Settembre",
            "IV Novembre",
            "XXV Aprile",
            "I Maggio"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Via Roma",
            "Via Italia",
            "Via della Repubblica",
            "Via dell'Unità",
            "Via della Libertà",
            "Via della Vittoria",
            "Via della Costituzione",
            "Via dell'Indipendenza",
            "Via della Resistenza",
            "Via del Lavoro",
            "Via del Popolo",
            "Via del Comune",
            "Via del Municipio",
            "Via della Stazione",
            "Via del Mercato",
            "Via del Duomo",
            "Via della Chiesa",
            "Via del Teatro",
            "Via dell'Ospedale",
            "Via delle Scuole",
            "Via dell'Università",
            "Via dell'Industria",
            "Via dell'Artigianato",
            "Via del Commercio",
            "Via del Porto",
            "Via della Marina",
            "Via del Castello",
            "Via della Rocca",
            "Via delle Mura",
            "Via della Fontana",
            "Via del Ponte",
            "Via del Canale",
            "Via Dante Alighieri",
            "Via Giuseppe Garibaldi",
            "Via Giuseppe Mazzini",
            "Via Camillo Benso di Cavour",
            "Via Guglielmo Marconi",
            "Via Alessandro Volta",
            "Via Galileo Galilei",
            "Via Leonardo da Vinci",
            "Via Michelangelo Buonarroti",
            "Via Raffaello Sanzio",
            "Via Cristoforo Colombo",
            "Via Alessandro Manzoni",
            "Via Giacomo Leopardi",
            "Via Giuseppe Verdi",
            "Via Giacomo Puccini",
            "Via Antonio Vivaldi",
            "Via XX Settembre",
            "Via IV Novembre",
            "Via XXV Aprile",
            "Via I Maggio",
            "Corso Italia",
            "Corso della Repubblica",
            "Corso Giuseppe Garibaldi",
            "Corso Giuseppe Mazzini",
            "Corso Camillo Benso di Cavour",
            "Corso Vittorio Emanuele II",
            "Piazza della Repubblica",
            "Piazza della Libertà",
            "Piazza della Vittoria",
            "Piazza del Popolo",
            "Piazza del Comune",
            "Piazza del Municipio",
            "Piazza del Duomo",
            "Piazza del Mercato",
            "Piazza Giuseppe Garibaldi",
            "Piazza Giuseppe Mazzini",
            "Largo della Pace",
            "Largo della Stazione"
        };

        internal static readonly string[] AvenuePrefixes =
        {
            "Viale",
            "Viale",
            "Viale",
            "Viale",
            "Corso",
            "Corso"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "Europa",
            "Italia",
            "della Repubblica",
            "della Libertà",
            "della Vittoria",
            "della Costituzione",
            "dell'Unità d'Italia",
            "dell'Indipendenza",
            "della Pace",
            "del Lavoro",
            "delle Nazioni",
            "dei Pini",
            "dei Platani",
            "dei Tigli",
            "dei Cipressi",
            "delle Magnolie",
            "della Pineta",
            "del Parco",
            "della Stazione",
            "del Porto",
            "della Marina",
            "dell'Industria",
            "dell'Innovazione",
            "della Scienza",
            "dell'Università",
            "dello Sport",
            "del Commercio",
            "dell'Artigianato",
            "del Rinascimento",
            "Giuseppe Garibaldi",
            "Giuseppe Mazzini",
            "Camillo Benso di Cavour",
            "Vittorio Emanuele II",
            "Guglielmo Marconi",
            "Leonardo da Vinci",
            "Cristoforo Colombo",
            "Giuseppe Verdi",
            "Giacomo Puccini",
            "Nord",
            "Sud",
            "Est",
            "Ovest",
            "Centrale",
            "del Mare",
            "dei Navigatori",
            "delle Palme"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Viale Europa",
            "Viale Italia",
            "Viale della Repubblica",
            "Viale della Libertà",
            "Viale della Vittoria",
            "Viale della Costituzione",
            "Viale dell'Unità d'Italia",
            "Viale dell'Indipendenza",
            "Viale della Pace",
            "Viale del Lavoro",
            "Viale delle Nazioni",
            "Viale dei Pini",
            "Viale dei Platani",
            "Viale dei Tigli",
            "Viale dei Cipressi",
            "Viale delle Magnolie",
            "Viale della Pineta",
            "Viale del Parco",
            "Viale della Stazione",
            "Viale del Porto",
            "Viale della Marina",
            "Viale dell'Industria",
            "Viale dell'Innovazione",
            "Viale della Scienza",
            "Viale dell'Università",
            "Viale dello Sport",
            "Viale del Commercio",
            "Viale Giuseppe Garibaldi",
            "Viale Giuseppe Mazzini",
            "Viale Camillo Benso di Cavour",
            "Viale Vittorio Emanuele II",
            "Viale Guglielmo Marconi",
            "Viale Leonardo da Vinci",
            "Viale Cristoforo Colombo",
            "Corso Italia",
            "Corso Europa",
            "Corso della Repubblica",
            "Corso della Libertà",
            "Corso della Vittoria",
            "Corso Vittorio Emanuele II",
            "Corso Giuseppe Garibaldi",
            "Corso Giuseppe Mazzini",
            "Lungomare Cristoforo Colombo",
            "Lungomare delle Palme",
            "Lungomare dei Navigatori",
            "Lungomare della Libertà",
            "Lungolago Europa",
            "Lungolago della Pace",
            "Circonvallazione Nord",
            "Circonvallazione Sud",
            "Circonvallazione Est",
            "Circonvallazione Ovest"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Autostrada del Sole",
            "Autostrada dei Laghi",
            "Autostrada Serenissima",
            "Autostrada Adriatica",
            "Autostrada dei Fiori",
            "Autostrada della Cisa",
            "Autostrada del Brennero",
            "Autostrada dei Parchi",
            "Autostrada del Mediterraneo",
            "Autostrada Tirrenica",
            "Autostrada della Val d'Aosta",
            "Autostrada della Valtellina",
            "Tangenziale Nord",
            "Tangenziale Sud",
            "Tangenziale Est",
            "Tangenziale Ovest",
            "Tangenziale Centrale",
            "Grande Raccordo Anulare",
            "Raccordo Autostradale Nord",
            "Raccordo Autostradale Sud",
            "Raccordo Autostradale Est",
            "Raccordo Autostradale Ovest",
            "Superstrada Adriatica",
            "Superstrada del Sempione",
            "Superstrada della Valsugana",
            "Superstrada dei Due Mari",
            "Strada di Grande Comunicazione",
            "Variante di Valico",
            "Asse Mediano",
            "Asse Attrezzato",
            "Pedemontana",
            "Bretella Nord",
            "Bretella Sud",
            "Bretella Est",
            "Bretella Ovest"
        };
    }
}