// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class ItalianRoadNames
    {
        internal static readonly string[] DirtPrefixes =
        {
            "Strada",
            "Strada",
            "Strada Vicinale",
            "Strada Comunale",
            "Sentiero",
            "Sentiero",
            "Cammino",
            "Tratturo",
            "Mulattiera",
            "Strada",
            "Strada Poderale",
            "Strada Interpoderale",
            "Strada Consortile",
            "Strada Forestale",
            "Strada Rurale",
            "Carrareccia",
            "Viottolo",
            "Pista Forestale",
            "Cammino",
            "Tratturo",
            "Mulattiera"
        };

        internal static readonly string[] DirtBaseNames =
        {
            "dei Campi",
            "delle Vigne",
            "degli Ulivi",
            "dei Cipressi",
            "dei Castagni",
            "dei Pini",
            "dei Gelsi",
            "dei Noci",
            "dei Faggi",
            "del Bosco",
            "del Poggio",
            "del Colle",
            "del Monte",
            "del Lago",
            "del Torrente",
            "del Mulino",
            "del Castello",
            "del Convento",
            "del Casale",
            "del Fontanile",
            "del Belvedere",
            "della Valle",
            "della Fonte",
            "della Quercia",
            "della Rovere",
            "della Pineta",
            "della Cascina",
            "della Pieve",
            "della Serra",
            "della Montagna",
            "della Campagna",
            "della Costa",
            "della Rocca",
            "delle Colline",
            "delle Fontane",
            "delle Ginestre",
            "delle Rose",
            "delle Acacie",
            "delle Betulle",
            "di Mezzo",
            "di Sopra",
            "di Sotto",
            "della Vecchia Ferrovia",
            "dell'Abbazia",
            "dell'Orto",
            "dell'Olmo",
            "dell'Argine",
            "dei Prati",
            "dei Pascoli",
            "dei Poderi",
            "dei Casali",
            "dei Frutteti",
            "dei Mandorli",
            "dei Ciliegi",
            "dei Pioppi",
            "dei Salici",
            "dei Lecci",
            "dei Larici",
            "dei Noccioleti",
            "delle Risaie",
            "del Vigneto",
            "dell'Oliveto",
            "del Frantoio",
            "del Granaio",
            "del Fienile",
            "del Torrione",
            "del Santuario",
            "dell'Eremo",
            "del Passo",
            "del Crinale",
            "del Pianoro",
            "del Vallone",
            "del Piano",
            "dell'Altopiano",
            "della Masseria",
            "della Tenuta",
            "della Riserva",
            "della Bonifica",
            "della Fornace",
            "della Sorgente",
            "della Cascata",
            "della Piana",
            "della Murgia",
            "della Brughiera",
            "della Macchia",
            "delle Marcite",
            "degli Armenti"
        };

        internal static readonly string[] DirtSpecialNames =
        {
            "Strada Bianca",
            "Strada dei Poderi",
            "Strada delle Masserie",
            "Strada della Bonifica",
            "Strada del Vigneto",
            "Strada dell'Oliveto",
            "Strada del Frantoio",
            "Strada del Granaio",
            "Strada del Fienile",
            "Strada del Borgo Vecchio",
            "Strada della Tenuta",
            "Strada della Riserva",
            "Strada del Bosco Alto",
            "Strada della Valle Verde",
            "Strada delle Colline",
            "Strada Vicinale dei Mulini",
            "Strada Vicinale delle Vigne",
            "Strada Vicinale della Pieve",
            "Strada Vicinale del Casale",
            "Sentiero degli Ulivi",
            "Sentiero dei Cipressi",
            "Sentiero delle Ginestre",
            "Sentiero del Castagno",
            "Sentiero della Rocca",
            "Cammino di San Luca",
            "Cammino di San Francesco",
            "Cammino della Valle",
            "Tratturo del Piano",
            "Tratturo della Murgia",
            "Mulattiera del Monte",
            "Strada Poderale dei Gelsi",
            "Strada Poderale della Quercia",
            "Strada Poderale del Casale",
            "Strada Interpoderale delle Vigne",
            "Strada Interpoderale degli Ulivi",
            "Strada Consortile dei Campi",
            "Strada Forestale del Monte",
            "Strada Forestale dei Faggi",
            "Strada Forestale della Pineta",
            "Pista Forestale del Crinale",
            "Pista Forestale della Riserva",
            "Carrareccia dei Campi",
            "Carrareccia del Bosco",
            "Carrareccia della Piana",
            "Viottolo della Fonte",
            "Viottolo del Mulino",
            "Viottolo dei Castagni",
            "Sentiero della Cascata",
            "Sentiero del Crinale",
            "Sentiero dell'Eremo",
            "Sentiero del Belvedere",
            "Cammino di San Benedetto",
            "Cammino di Sant'Antonio",
            "Cammino dei Pellegrini",
            "Cammino delle Abbazie",
            "Tratturo degli Armenti",
            "Tratturo della Piana",
            "Tratturo delle Murge",
            "Mulattiera della Rocca",
            "Mulattiera del Passo",
            "Mulattiera dell'Eremo",
            "Strada della Transumanza",
            "Strada delle Risaie",
            "Strada dei Frutteti",
            "Strada della Sorgente"
        };

        internal static readonly string[] AlleyPrefixes =
        {
            "Vicolo",
            "Vicolo",
            "Via",
            "Calle",
            "Calle",
            "Salita",
            "Discesa",
            "Passaggio",
            "Sottoportico",
            "Vicolo",
            "Corte",
            "Ramo",
            "Ruga",
            "Salizada",
            "Fondamenta",
            "Rio Terà",
            "Contrada",
            "Chiasso",
            "Rua",
            "Riva",
            "Scalinata"
        };

        internal static readonly string[] AlleyBaseNames =
        {
            "dell'Arco",
            "del Campanile",
            "della Torre",
            "del Forno",
            "del Pozzo",
            "del Gallo",
            "del Leone",
            "della Luna",
            "del Sole",
            "della Stella",
            "della Volpe",
            "del Gatto",
            "dei Fabbri",
            "dei Mercanti",
            "dei Pescatori",
            "dei Muratori",
            "dei Tessitori",
            "dei Calderai",
            "dei Vasai",
            "dei Bottai",
            "delle Mura",
            "delle Rose",
            "delle Campane",
            "delle Logge",
            "delle Colonne",
            "delle Botteghe",
            "della Fontana",
            "della Chiesa",
            "della Canonica",
            "della Dogana",
            "della Zecca",
            "del Mercato",
            "del Porto",
            "del Teatro",
            "del Castello",
            "del Palazzo",
            "del Chiostro",
            "del Borgo",
            "San Luca",
            "San Marco",
            "San Pietro",
            "San Paolo",
            "Santa Lucia",
            "Santa Maria",
            "Sant'Antonio",
            "Sant'Anna",
            "della Pace",
            "dell'Olmo",
            "del Gelso",
            "della Quercia",
            "del Portico",
            "del Ponte",
            "del Canale",
            "del Monastero",
            "dell'Abbazia",
            "dell'Orologio",
            "del Granaio",
            "del Magazzino",
            "del Fondaco",
            "del Sarto",
            "del Fabbro",
            "del Vetraio",
            "del Fornaio",
            "del Pescatore",
            "dei Tintori",
            "dei Cordai",
            "dei Calzolai",
            "degli Orefici",
            "degli Speziali",
            "delle Carceri",
            "delle Erbe",
            "delle Beccherie",
            "della Porta",
            "della Scala",
            "della Loggia",
            "della Corte",
            "della Riva",
            "della Darsena",
            "della Maddalena",
            "San Giacomo",
            "San Giovanni",
            "San Nicola",
            "San Francesco",
            "San Benedetto",
            "Santa Caterina",
            "Santa Croce",
            "Sant'Agostino",
            "Sant'Alvise"
        };

        internal static readonly string[] AlleySpecialNames =
        {
            "Vicolo Stretto",
            "Vicolo Corto",
            "Vicolo del Centro",
            "Vicolo della Porta",
            "Vicolo delle Mura",
            "Vicolo del Campanile",
            "Vicolo della Torre",
            "Vicolo del Forno",
            "Vicolo del Pozzo",
            "Vicolo dei Fabbri",
            "Vicolo dei Mercanti",
            "Vicolo dei Pescatori",
            "Vicolo delle Botteghe",
            "Vicolo del Borgo",
            "Vicolo San Luca",
            "Vicolo Santa Lucia",
            "Calle Lunga",
            "Calle Stretta",
            "Calle del Forno",
            "Calle della Chiesa",
            "Calle dei Mercanti",
            "Calle del Teatro",
            "Calle del Porto",
            "Salita al Castello",
            "Salita alla Rocca",
            "Salita del Campanile",
            "Discesa al Porto",
            "Discesa del Mercato",
            "Passaggio delle Logge",
            "Sottoportico della Torre",
            "Vicolo dell'Arco",
            "Vicolo del Portico",
            "Vicolo dell'Orologio",
            "Vicolo della Scala",
            "Vicolo della Loggia",
            "Vicolo degli Orefici",
            "Vicolo dei Tintori",
            "Vicolo Santa Caterina",
            "Calle Larga",
            "Calle del Vento",
            "Calle degli Orefici",
            "Calle dei Fabbri",
            "Calle dei Tintori",
            "Calle del Magazzino",
            "Ramo del Forno",
            "Ramo della Tana",
            "Ramo del Ponte",
            "Ruga degli Orefici",
            "Ruga degli Speziali",
            "Ruga dei Mercanti",
            "Salizada San Giovanni",
            "Salizada dei Greci",
            "Fondamenta dei Mori",
            "Fondamenta della Misericordia",
            "Fondamenta del Monastero",
            "Fondamenta delle Zattere",
            "Rio Terà San Leonardo",
            "Rio Terà dei Pensieri",
            "Rio Terà delle Carampane",
            "Campiello del Remer",
            "Campiello dei Fabbri",
            "Campiello del Forno",
            "Campo San Giacomo",
            "Campo Santa Margherita",
            "Corte della Seta",
            "Corte del Forno",
            "Corte del Pozzo",
            "Sottoportico del Ponte",
            "Sottoportico della Chiesa",
            "Sottoportico della Corte",
            "Chiasso degli Armati",
            "Chiasso del Buco",
            "Contrada del Leone",
            "Contrada della Torre",
            "Rua dei Mercanti",
            "Rua delle Stelle",
            "Riva del Ferro",
            "Riva dei Pescatori",
            "Scalinata del Carmine",
            "Scalinata della Chiesa",
            "Salita degli Angeli",
            "Salita al Santuario",
            "Discesa alla Marina",
            "Discesa alla Darsena",
            "Crêuza di San Rocco",
            "Crêuza del Monte"
        };

        internal static readonly string[] ResidentialPrefixes =
        {
            "Via",
            "Via",
            "Via",
            "Viale",
            "Vicolo",
            "Piazzetta",
            "Via",
            "Viale",
            "Strada",
            "Largo",
            "Piazzale"
        };

        internal static readonly string[] ResidentialBaseNames =
        {
            "dei Gelsi",
            "dei Pini",
            "dei Tigli",
            "dei Pioppi",
            "dei Platani",
            "dei Cedri",
            "dei Larici",
            "dei Noci",
            "dei Castagni",
            "dei Faggi",
            "dei Salici",
            "degli Ulivi",
            "degli Oleandri",
            "degli Aceri",
            "degli Abeti",
            "delle Rose",
            "delle Viole",
            "delle Ginestre",
            "delle Camelie",
            "delle Magnolie",
            "delle Mimose",
            "delle Azalee",
            "delle Orchidee",
            "delle Betulle",
            "delle Acacie",
            "della Quercia",
            "della Rovere",
            "della Pineta",
            "del Glicine",
            "del Biancospino",
            "del Rosmarino",
            "della Lavanda",
            "del Giardino",
            "del Parco",
            "del Sole",
            "della Luna",
            "delle Stelle",
            "dell'Alba",
            "del Tramonto",
            "della Primavera",
            "della Serenità",
            "della Pace",
            "dell'Amicizia",
            "della Concordia",
            "del Belvedere",
            "della Collina",
            "della Valle",
            "del Lago",
            "del Torrente",
            "del Mulino",
            "San Giorgio",
            "San Lorenzo",
            "San Michele",
            "San Rocco",
            "Santa Chiara",
            "Santa Rita",
            "Santa Teresa",
            "dei Ciliegi",
            "dei Mandorli",
            "dei Lecci",
            "dei Frassini",
            "dei Carpini",
            "dei Noccioli",
            "dei Melograni",
            "degli Aranci",
            "dei Limoni",
            "degli Allori",
            "dei Girasoli",
            "dei Papaveri",
            "dei Ciclamini",
            "dei Gerani",
            "delle Margherite",
            "delle Peonie",
            "delle Ortensie",
            "del Timo",
            "della Salvia",
            "del Basilico",
            "delle Colline",
            "dei Colli",
            "del Poggio",
            "del Monte",
            "della Piana",
            "della Fonte",
            "della Sorgente",
            "del Ruscello",
            "dell'Arcobaleno",
            "della Gioia",
            "della Speranza",
            "dell'Armonia",
            "del Sorriso",
            "del Borgo",
            "della Cascina",
            "della Masseria",
            "San Giovanni",
            "San Francesco",
            "San Benedetto",
            "San Martino",
            "Sant'Antonio",
            "Sant'Andrea",
            "Santa Lucia",
            "Santa Caterina"
        };

        internal static readonly string[] ResidentialSpecialNames =
        {
            "Via dei Gelsi",
            "Via dei Tigli",
            "Via dei Platani",
            "Via dei Cedri",
            "Via dei Castagni",
            "Via degli Ulivi",
            "Via delle Rose",
            "Via delle Viole",
            "Via delle Ginestre",
            "Via delle Magnolie",
            "Via delle Mimose",
            "Via della Quercia",
            "Via della Pineta",
            "Via del Glicine",
            "Via della Lavanda",
            "Via del Giardino",
            "Via del Parco",
            "Via del Sole",
            "Via della Luna",
            "Via delle Stelle",
            "Via dell'Alba",
            "Via del Tramonto",
            "Via della Primavera",
            "Via della Serenità",
            "Via della Pace",
            "Via dell'Amicizia",
            "Via della Concordia",
            "Via del Belvedere",
            "Via della Collina",
            "Via della Valle",
            "Via del Lago",
            "Via del Mulino",
            "Via San Giorgio",
            "Via San Lorenzo",
            "Via San Michele",
            "Via San Rocco",
            "Via Santa Chiara",
            "Via Santa Rita",
            "Viale dei Pini",
            "Viale delle Rose",
            "Viale della Pineta",
            "Piazzetta del Sole",
            "Piazzetta delle Rose",
            "Via dei Ciliegi",
            "Via dei Mandorli",
            "Via dei Lecci",
            "Via dei Frassini",
            "Via dei Melograni",
            "Via degli Aranci",
            "Via dei Limoni",
            "Via degli Allori",
            "Via dei Girasoli",
            "Via dei Papaveri",
            "Via delle Margherite",
            "Via delle Ortensie",
            "Via del Timo",
            "Via della Salvia",
            "Via delle Colline",
            "Via del Poggio",
            "Via della Fonte",
            "Via della Sorgente",
            "Via del Ruscello",
            "Via dell'Arcobaleno",
            "Via della Gioia",
            "Via della Speranza",
            "Via dell'Armonia",
            "Via San Giovanni",
            "Via San Francesco",
            "Via San Benedetto",
            "Via San Martino",
            "Via Sant'Antonio",
            "Via Sant'Andrea",
            "Via Santa Lucia",
            "Via Santa Caterina",
            "Viale dei Ciliegi",
            "Viale dei Lecci",
            "Viale dei Girasoli",
            "Viale delle Ortensie",
            "Viale del Belvedere",
            "Viale delle Colline",
            "Piazzetta della Fonte",
            "Piazzetta del Borgo",
            "Piazzetta San Giovanni",
            "Largo dei Gelsi",
            "Largo della Quercia",
            "Largo della Pace",
            "Borgo San Rocco",
            "Borgo San Martino",
            "Borgo Santa Lucia",
            "Contrada dei Gelsi",
            "Contrada della Fonte",
            "Contrada del Poggio",
            "Strada della Cascina",
            "Strada della Masseria"
        };

        internal static readonly string[] StandardPrefixes =
        {
            "Via",
            "Via",
            "Via",
            "Corso",
            "Corso",
            "Piazza",
            "Largo",
            "Via",
            "Via",
            "Corso",
            "Piazza",
            "Piazza",
            "Largo",
            "Piazzale",
            "Piazzetta",
            "Viale",
            "Strada"
        };

        internal static readonly string[] StandardBaseNames =
        {
            "Roma",
            "Italia",
            "Europa",
            "della Repubblica",
            "dell'Unità",
            "della Libertà",
            "della Vittoria",
            "della Costituzione",
            "dell'Indipendenza",
            "della Resistenza",
            "della Pace",
            "del Lavoro",
            "del Popolo",
            "del Comune",
            "del Municipio",
            "della Stazione",
            "del Mercato",
            "del Duomo",
            "della Chiesa",
            "del Teatro",
            "dell'Ospedale",
            "delle Scuole",
            "dell'Università",
            "dell'Industria",
            "dell'Artigianato",
            "del Commercio",
            "del Porto",
            "della Marina",
            "del Castello",
            "della Rocca",
            "delle Mura",
            "della Fontana",
            "del Ponte",
            "del Canale",
            "del Molino",
            "Dante Alighieri",
            "Giuseppe Garibaldi",
            "Giuseppe Mazzini",
            "Camillo Benso di Cavour",
            "Guglielmo Marconi",
            "Alessandro Volta",
            "Galileo Galilei",
            "Leonardo da Vinci",
            "Michelangelo Buonarroti",
            "Raffaello Sanzio",
            "Cristoforo Colombo",
            "Amerigo Vespucci",
            "Marco Polo",
            "Giacomo Leopardi",
            "Alessandro Manzoni",
            "Giovanni Pascoli",
            "Giosuè Carducci",
            "Luigi Pirandello",
            "Enrico Fermi",
            "Antonio Meucci",
            "Giuseppe Verdi",
            "Giacomo Puccini",
            "Gioachino Rossini",
            "Antonio Vivaldi",
            "Vittorio Emanuele II",
            "Umberto I",
            "XX Settembre",
            "IV Novembre",
            "XXV Aprile",
            "I Maggio",
            "della Democrazia",
            "della Solidarietà",
            "della Giustizia",
            "della Memoria",
            "della Rinascita",
            "del Risorgimento",
            "dei Caduti",
            "dei Martiri",
            "dei Partigiani",
            "degli Alpini",
            "dei Bersaglieri",
            "dei Marinai d'Italia",
            "dei Lavoratori",
            "degli Artigiani",
            "della Croce Rossa",
            "della Posta",
            "del Tribunale",
            "della Biblioteca",
            "del Museo",
            "dell'Archivio",
            "della Fiera",
            "del Cimitero",
            "del Campo Sportivo",
            "della Darsena",
            "del Faro",
            "della Fortezza",
            "della Cittadella",
            "del Bastione",
            "del Convento",
            "dell'Abbazia",
            "delle Alpi",
            "degli Appennini",
            "delle Dolomiti",
            "del Gran Sasso",
            "del Monte Bianco",
            "del Vesuvio",
            "dell'Etna",
            "del Po",
            "dell'Arno",
            "del Tevere",
            "dell'Adige",
            "del Piave",
            "del Garda",
            "del Mediterraneo",
            "dell'Adriatico",
            "del Tirreno",
            "Milano",
            "Torino",
            "Venezia",
            "Firenze",
            "Bologna",
            "Genova",
            "Napoli",
            "Palermo",
            "Bari",
            "Verona",
            "Trieste",
            "Cagliari",
            "Perugia",
            "Siena",
            "Ravenna",
            "Pisa",
            "Padova",
            "Parma",
            "Modena",
            "Toscana",
            "Lombardia",
            "Piemonte",
            "Veneto",
            "Liguria",
            "Emilia",
            "Romagna",
            "Umbria",
            "Marche",
            "Lazio",
            "Abruzzo",
            "Puglia",
            "Calabria",
            "Sicilia",
            "Sardegna",
            "Francesco Petrarca",
            "Giovanni Boccaccio",
            "Niccolò Machiavelli",
            "Torquato Tasso",
            "Ugo Foscolo",
            "Gabriele D'Annunzio",
            "Carlo Goldoni",
            "Carlo Collodi",
            "Italo Calvino",
            "Primo Levi",
            "Cesare Pavese",
            "Salvatore Quasimodo",
            "Eugenio Montale",
            "Grazia Deledda",
            "Sandro Botticelli",
            "Donatello",
            "Tiziano Vecellio",
            "Caravaggio",
            "Gian Lorenzo Bernini",
            "Antonio Canova",
            "Evangelista Torricelli",
            "Amedeo Avogadro",
            "Ettore Majorana",
            "Rita Levi-Montalcini",
            "Maria Montessori",
            "Antonio Pacinotti",
            "Gaetano Donizetti",
            "Vincenzo Bellini",
            "Pietro Mascagni",
            "Niccolò Paganini",
            "Alcide De Gasperi",
            "Sandro Pertini",
            "Aldo Moro",
            "Nino Bixio",
            "Fratelli Bandiera",
            "II Giugno",
            "VIII Marzo",
            "XXIV Maggio"
        };

        internal static readonly string[] StandardSpecialNames =
        {
            "Via Roma",
            "Via Italia",
            "Via della Repubblica",
            "Via dell'Unità",
            "Via della Libertà",
            "Via della Vittoria",
            "Via della Costituzione",
            "Via dell'Indipendenza",
            "Via della Resistenza",
            "Via del Lavoro",
            "Via del Popolo",
            "Via del Comune",
            "Via del Municipio",
            "Via della Stazione",
            "Via del Mercato",
            "Via del Duomo",
            "Via della Chiesa",
            "Via del Teatro",
            "Via dell'Ospedale",
            "Via delle Scuole",
            "Via dell'Università",
            "Via dell'Industria",
            "Via dell'Artigianato",
            "Via del Commercio",
            "Via del Porto",
            "Via della Marina",
            "Via del Castello",
            "Via della Rocca",
            "Via delle Mura",
            "Via della Fontana",
            "Via del Ponte",
            "Via del Canale",
            "Via Dante Alighieri",
            "Via Giuseppe Garibaldi",
            "Via Giuseppe Mazzini",
            "Via Camillo Benso di Cavour",
            "Via Guglielmo Marconi",
            "Via Alessandro Volta",
            "Via Galileo Galilei",
            "Via Leonardo da Vinci",
            "Via Michelangelo Buonarroti",
            "Via Raffaello Sanzio",
            "Via Cristoforo Colombo",
            "Via Alessandro Manzoni",
            "Via Giacomo Leopardi",
            "Via Giuseppe Verdi",
            "Via Giacomo Puccini",
            "Via Antonio Vivaldi",
            "Via XX Settembre",
            "Via IV Novembre",
            "Via XXV Aprile",
            "Via I Maggio",
            "Corso Italia",
            "Corso della Repubblica",
            "Corso Giuseppe Garibaldi",
            "Corso Giuseppe Mazzini",
            "Corso Camillo Benso di Cavour",
            "Corso Vittorio Emanuele II",
            "Piazza della Repubblica",
            "Piazza della Libertà",
            "Piazza della Vittoria",
            "Piazza del Popolo",
            "Piazza del Comune",
            "Piazza del Municipio",
            "Piazza del Duomo",
            "Piazza del Mercato",
            "Piazza Giuseppe Garibaldi",
            "Piazza Giuseppe Mazzini",
            "Largo della Pace",
            "Largo della Stazione",
            "Via della Democrazia",
            "Via della Solidarietà",
            "Via della Giustizia",
            "Via della Memoria",
            "Via del Risorgimento",
            "Via dei Caduti",
            "Via dei Martiri",
            "Via dei Partigiani",
            "Via degli Alpini",
            "Via dei Bersaglieri",
            "Via dei Marinai d'Italia",
            "Via della Croce Rossa",
            "Via della Biblioteca",
            "Via del Museo",
            "Via della Fiera",
            "Via della Darsena",
            "Via del Faro",
            "Via delle Alpi",
            "Via degli Appennini",
            "Via delle Dolomiti",
            "Via del Gran Sasso",
            "Via del Vesuvio",
            "Via dell'Etna",
            "Via del Po",
            "Via dell'Arno",
            "Via del Tevere",
            "Via dell'Adige",
            "Via del Piave",
            "Via Milano",
            "Via Torino",
            "Via Venezia",
            "Via Firenze",
            "Via Bologna",
            "Via Genova",
            "Via Napoli",
            "Via Palermo",
            "Via Bari",
            "Via Verona",
            "Via Trieste",
            "Via Francesco Petrarca",
            "Via Giovanni Boccaccio",
            "Via Niccolò Machiavelli",
            "Via Torquato Tasso",
            "Via Ugo Foscolo",
            "Via Gabriele D'Annunzio",
            "Via Carlo Goldoni",
            "Via Italo Calvino",
            "Via Primo Levi",
            "Via Eugenio Montale",
            "Via Grazia Deledda",
            "Via Sandro Botticelli",
            "Via Donatello",
            "Via Caravaggio",
            "Via Gian Lorenzo Bernini",
            "Via Antonio Canova",
            "Via Evangelista Torricelli",
            "Via Amedeo Avogadro",
            "Via Ettore Majorana",
            "Via Rita Levi-Montalcini",
            "Via Maria Montessori",
            "Via Gaetano Donizetti",
            "Via Vincenzo Bellini",
            "Via Niccolò Paganini",
            "Via Alcide De Gasperi",
            "Via Sandro Pertini",
            "Via Aldo Moro",
            "Via Nino Bixio",
            "Via Fratelli Bandiera",
            "Via II Giugno",
            "Via VIII Marzo",
            "Via XXIV Maggio",
            "Corso del Risorgimento",
            "Corso della Democrazia",
            "Corso Milano",
            "Corso Torino",
            "Corso Venezia",
            "Corso Firenze",
            "Corso Sandro Pertini",
            "Corso Aldo Moro",
            "Piazza Dante Alighieri",
            "Piazza Camillo Benso di Cavour",
            "Piazza Sandro Pertini",
            "Piazza Aldo Moro",
            "Piazza dei Caduti",
            "Piazza dei Martiri",
            "Piazza del Risorgimento",
            "Piazza II Giugno",
            "Piazza XX Settembre",
            "Piazzale della Stazione",
            "Piazzale del Mercato",
            "Piazzale degli Eroi",
            "Piazzale Michelangelo",
            "Largo dei Caduti",
            "Largo dei Martiri",
            "Largo Sandro Pertini",
            "Largo Aldo Moro",
            "Lungarno della Zecca Vecchia",
            "Lungarno Cristoforo Colombo",
            "Lungotevere della Vittoria",
            "Lungotevere degli Artigiani",
            "Lungopo Europa",
            "Riviera del Brenta",
            "Riviera San Benedetto",
            "Borgo San Giovanni",
            "Borgo Santa Croce"
        };

        internal static readonly string[] AvenuePrefixes =
        {
            "Viale",
            "Viale",
            "Viale",
            "Viale",
            "Corso",
            "Corso",
            "Viale",
            "Viale",
            "Corso"
        };

        internal static readonly string[] AvenueBaseNames =
        {
            "Europa",
            "Italia",
            "della Repubblica",
            "della Libertà",
            "della Vittoria",
            "della Costituzione",
            "dell'Unità d'Italia",
            "dell'Indipendenza",
            "della Pace",
            "del Lavoro",
            "delle Nazioni",
            "dei Pini",
            "dei Platani",
            "dei Tigli",
            "dei Cipressi",
            "delle Magnolie",
            "della Pineta",
            "del Parco",
            "della Stazione",
            "del Porto",
            "della Marina",
            "dell'Industria",
            "dell'Innovazione",
            "della Scienza",
            "dell'Università",
            "dello Sport",
            "del Commercio",
            "dell'Artigianato",
            "del Rinascimento",
            "Giuseppe Garibaldi",
            "Giuseppe Mazzini",
            "Camillo Benso di Cavour",
            "Vittorio Emanuele II",
            "Guglielmo Marconi",
            "Leonardo da Vinci",
            "Cristoforo Colombo",
            "Giuseppe Verdi",
            "Giacomo Puccini",
            "Nord",
            "Sud",
            "Est",
            "Ovest",
            "Centrale",
            "del Mare",
            "dei Navigatori",
            "delle Palme",
            "della Democrazia",
            "della Solidarietà",
            "del Risorgimento",
            "dei Caduti",
            "dei Martiri",
            "degli Alpini",
            "degli Artigiani",
            "delle Alpi",
            "degli Appennini",
            "delle Dolomiti",
            "del Mediterraneo",
            "dell'Adriatico",
            "del Tirreno",
            "del Sole",
            "del Tramonto",
            "dei Giardini",
            "della Fiera",
            "della Darsena",
            "della Tecnologia",
            "della Ricerca",
            "dell'Energia",
            "dell'Ambiente",
            "della Cultura",
            "delle Arti",
            "della Musica",
            "Dante Alighieri",
            "Galileo Galilei",
            "Alessandro Volta",
            "Enrico Fermi",
            "Maria Montessori",
            "Sandro Pertini",
            "Aldo Moro",
            "Milano",
            "Torino",
            "Venezia",
            "Firenze",
            "Bologna",
            "Genova",
            "Napoli",
            "Palermo"
        };

        internal static readonly string[] AvenueSpecialNames =
        {
            "Viale Europa",
            "Viale Italia",
            "Viale della Repubblica",
            "Viale della Libertà",
            "Viale della Vittoria",
            "Viale della Costituzione",
            "Viale dell'Unità d'Italia",
            "Viale dell'Indipendenza",
            "Viale della Pace",
            "Viale del Lavoro",
            "Viale delle Nazioni",
            "Viale dei Pini",
            "Viale dei Platani",
            "Viale dei Tigli",
            "Viale dei Cipressi",
            "Viale delle Magnolie",
            "Viale della Pineta",
            "Viale del Parco",
            "Viale della Stazione",
            "Viale del Porto",
            "Viale della Marina",
            "Viale dell'Industria",
            "Viale dell'Innovazione",
            "Viale della Scienza",
            "Viale dell'Università",
            "Viale dello Sport",
            "Viale del Commercio",
            "Viale Giuseppe Garibaldi",
            "Viale Giuseppe Mazzini",
            "Viale Camillo Benso di Cavour",
            "Viale Vittorio Emanuele II",
            "Viale Guglielmo Marconi",
            "Viale Leonardo da Vinci",
            "Viale Cristoforo Colombo",
            "Corso Italia",
            "Corso Europa",
            "Corso della Repubblica",
            "Corso della Libertà",
            "Corso della Vittoria",
            "Corso Vittorio Emanuele II",
            "Corso Giuseppe Garibaldi",
            "Corso Giuseppe Mazzini",
            "Lungomare Cristoforo Colombo",
            "Lungomare delle Palme",
            "Lungomare dei Navigatori",
            "Lungomare della Libertà",
            "Lungolago Europa",
            "Lungolago della Pace",
            "Circonvallazione Nord",
            "Circonvallazione Sud",
            "Circonvallazione Est",
            "Circonvallazione Ovest",
            "Viale della Democrazia",
            "Viale della Solidarietà",
            "Viale del Risorgimento",
            "Viale dei Caduti",
            "Viale dei Martiri",
            "Viale degli Alpini",
            "Viale delle Alpi",
            "Viale degli Appennini",
            "Viale delle Dolomiti",
            "Viale del Mediterraneo",
            "Viale dell'Adriatico",
            "Viale del Tirreno",
            "Viale del Sole",
            "Viale dei Giardini",
            "Viale della Fiera",
            "Viale della Darsena",
            "Viale della Tecnologia",
            "Viale della Ricerca",
            "Viale dell'Energia",
            "Viale dell'Ambiente",
            "Viale della Cultura",
            "Viale delle Arti",
            "Viale della Musica",
            "Viale Dante Alighieri",
            "Viale Galileo Galilei",
            "Viale Alessandro Volta",
            "Viale Enrico Fermi",
            "Viale Maria Montessori",
            "Viale Sandro Pertini",
            "Viale Aldo Moro",
            "Corso del Risorgimento",
            "Corso della Democrazia",
            "Corso Milano",
            "Corso Torino",
            "Corso Venezia",
            "Corso Firenze",
            "Lungomare della Repubblica",
            "Lungomare del Sole",
            "Lungomare della Vittoria",
            "Lungomare degli Eroi",
            "Lungomare del Mediterraneo",
            "Lungomare Adriatico",
            "Lungomare Tirreno",
            "Lungolago dei Pini",
            "Lungolago del Garda",
            "Lungolago della Libertà",
            "Lungofiume Europa",
            "Lungofiume della Pace",
            "Lungotevere della Vittoria",
            "Lungotevere delle Arti",
            "Lungarno della Repubblica",
            "Lungarno delle Grazie",
            "Lungopo Europa",
            "Lungopo della Libertà",
            "Riviera delle Palme",
            "Riviera del Brenta",
            "Passeggiata del Belvedere",
            "Passeggiata dei Pini",
            "Passeggiata delle Rose",
            "Passeggiata della Marina",
            "Circonvallazione Interna",
            "Circonvallazione Esterna",
            "Circonvallazione dei Colli",
            "Circonvallazione del Centro",
            "Strada Panoramica del Monte",
            "Strada Panoramica del Mare"
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Autostrada del Sole",
            "Autostrada dei Laghi",
            "Autostrada Serenissima",
            "Autostrada Adriatica",
            "Autostrada dei Fiori",
            "Autostrada della Cisa",
            "Autostrada del Brennero",
            "Autostrada dei Parchi",
            "Autostrada del Mediterraneo",
            "Autostrada Tirrenica",
            "Autostrada della Val d'Aosta",
            "Autostrada della Valtellina",
            "Tangenziale Nord",
            "Tangenziale Sud",
            "Tangenziale Est",
            "Tangenziale Ovest",
            "Tangenziale Centrale",
            "Grande Raccordo Anulare",
            "Raccordo Autostradale Nord",
            "Raccordo Autostradale Sud",
            "Raccordo Autostradale Est",
            "Raccordo Autostradale Ovest",
            "Superstrada Adriatica",
            "Superstrada del Sempione",
            "Superstrada della Valsugana",
            "Superstrada dei Due Mari",
            "Strada di Grande Comunicazione",
            "Variante di Valico",
            "Asse Mediano",
            "Asse Attrezzato",
            "Pedemontana",
            "Bretella Nord",
            "Bretella Sud",
            "Bretella Est",
            "Bretella Ovest",
            "Autostrada delle Alpi",
            "Autostrada dei Due Mari",
            "Autostrada della Riviera",
            "Autostrada del Mare",
            "Autostrada dei Trafori",
            "Tangenziale Interna",
            "Tangenziale Esterna",
            "Tangenziale dei Colli",
            "Tangenziale del Porto",
            "Tangenziale dell'Aeroporto",
            "Raccordo Anulare Nord",
            "Raccordo Anulare Sud",
            "Raccordo del Porto",
            "Raccordo dell'Aeroporto",
            "Raccordo Industriale",
            "Superstrada del Mare",
            "Superstrada dei Laghi",
            "Superstrada delle Valli",
            "Superstrada delle Dolomiti",
            "Strada dei Parchi",
            "Strada delle Dolomiti",
            "Strada del Gran Sasso",
            "Variante Nord",
            "Variante Sud",
            "Variante Est",
            "Variante Ovest",
            "Variante del Centro",
            "Asse Nord-Sud",
            "Asse Est-Ovest",
            "Asse di Scorrimento",
            "Asse del Porto",
            "Bretella del Porto",
            "Bretella dell'Aeroporto",
            "Bretella Industriale",
            "Pedemontana Veneta",
            "Pedemontana Lombarda"
        };
    }
}