// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class PolishRoadNames
    {
        internal static readonly string[] DirtNames =
        {
            "Droga Akacjowa",
            "Droga Bagienna",
            "Droga Beskidzka",
            "Droga Białowieska",
            "Droga Bieszczadzka",
            "Droga Bobrowa",
            "Droga Bociania",
            "Droga Borowa",
            "Droga Borówkowa",
            "Droga Brzeziny",
            "Droga Brzozowa",
            "Droga Bukowa",
            "Droga Bukowego Lasu",
            "Droga Bursztynowa",
            "Droga Cichego Lasu",
            "Droga Cisowa",
            "Droga Do Folwarku",
            "Droga Do Jeziora",
            "Droga Do Leśniczówki",
            "Droga Do Młyna",
            "Droga Do Przystani",
            "Droga Dojazdowa",
            "Droga Dolinna",
            "Droga Dębiny",
            "Droga Dębowa",
            "Droga Folwarczna",
            "Droga Gajowa",
            "Droga Grabowa",
            "Droga Graniczna",
            "Droga Grzybowa",
            "Droga Górska",
            "Droga Głogowa",
            "Droga Jagodowa",
            "Droga Jarzębinowa",
            "Droga Jałowcowa",
            "Droga Jaśminowa",
            "Droga Jelenia",
            "Droga Jesionowa",
            "Droga Jeżowa",
            "Droga Jeżynowa",
            "Droga Jodłowa",
            "Droga Jodłowego Lasu",
            "Droga Jurajska",
            "Droga Kamienna",
            "Droga Kampinoska",
            "Droga Karkonoska",
            "Droga Kasztanowa",
            "Droga Kaszubska",
            "Droga Klonowa",
            "Droga Klonowego Gaju",
            "Droga Konwaliowa",
            "Droga Kujawska",
            "Droga Lawendowa",
            "Droga Leszczynowa",
            "Droga Leśna",
            "Droga Leśna Polana",
            "Droga Leśnego Potoku",
            "Droga Leśników",
            "Droga Lipowa",
            "Droga Lipowego Gaju",
            "Droga Lisia",
            "Droga Lubelska",
            "Droga Malinowa",
            "Droga Mazowiecka",
            "Droga Mazurska",
            "Droga Małopolska",
            "Droga Modrzewiowa",
            "Droga Mostowa",
            "Droga Myśliwska",
            "Droga Młyńska",
            "Droga Nad Jeziorem",
            "Droga Nad Kanałem",
            "Droga Nad Rzeką",
            "Droga Nad Stawem",
            "Droga Nadjeziorna",
            "Droga Nadleśna",
            "Droga Nadmorska",
            "Droga Nadodrzańska",
            "Droga Nadwiślańska",
            "Droga Nowa",
            "Droga Olchowa",
            "Droga Orla",
            "Droga Pagórkowa",
            "Droga Paprociowa",
            "Droga Pasieczna",
            "Droga Piaszczysta",
            "Droga Pienińska",
            "Droga Pod Górą",
            "Droga Pod Lasem",
            "Droga Podhalańska",
            "Droga Podlaska",
            "Droga Pojezierna",
            "Droga Polna",
            "Droga Pomorska",
            "Droga Poziomkowa",
            "Droga Przez Pola",
            "Droga Przez Wydmy",
            "Droga Przez Łąki",
            "Droga Pszczela",
            "Droga Puszczańska",
            "Droga Puszczykowa",
            "Droga Rolna",
            "Droga Roztoczańska",
            "Droga Rybaków",
            "Droga Rzeczna",
            "Droga Równinna",
            "Droga Sadowa",
            "Droga Sarnia",
            "Droga Skalna",
            "Droga Sokoła",
            "Droga Sosnowa",
            "Droga Sosnowego Boru",
            "Droga Spacerowa",
            "Droga Spokojna",
            "Droga Stara",
            "Droga Starego Kamieniołomu",
            "Droga Starego Traktu",
            "Droga Stawowa",
            "Droga Sudecka",
            "Droga Słoneczna",
            "Droga Tarninowa",
            "Droga Tatrzańska",
            "Droga Topolowa",
            "Droga Torfowa",
            "Droga Uroczyskowa",
            "Droga Warmińska",
            "Droga Widokowa",
            "Droga Wielkopolska",
            "Droga Wierzbiny",
            "Droga Wierzbowa",
            "Droga Wilcza",
            "Droga Wodna",
            "Droga Wrzosowa",
            "Droga Wrzosowego Wzgórza",
            "Droga Wydmowa",
            "Droga Wąwozowa",
            "Droga Zaciszna",
            "Droga Zielona",
            "Droga Zielonej Doliny",
            "Droga Łąkowa",
            "Droga Łęgowa",
            "Droga Śląska",
            "Droga Świerkowa",
            "Droga Świerkowego Boru",
            "Droga Źródlana",
            "Droga Żurawia",
            "Droga Żurawinowa"
        };

        internal static readonly string[] AlleyNames =
        {
            "ul. Aptekarska",
            "ul. Arkadowa",
            "ul. Basztowa",
            "ul. Bednarska",
            "ul. Białej Wieży",
            "ul. Białoskórnicza",
            "ul. Boczna",
            "ul. Bożego Ciała",
            "ul. Bracka",
            "ul. Bramowa",
            "ul. Browarna",
            "ul. Brzozowa",
            "ul. Ceglana",
            "ul. Celna",
            "ul. Chmielna",
            "ul. Cicha",
            "ul. Ciemna",
            "ul. Ciesielska",
            "ul. Cmentarna",
            "ul. Czarnej Wieży",
            "ul. Czerwonej Bramy",
            "ul. Dawna",
            "ul. Dolny Zaułek",
            "ul. Dominikańska",
            "ul. Drukarska",
            "ul. Długa",
            "ul. Estery",
            "ul. Farbiarska",
            "ul. Floriańska",
            "ul. Franciszkańska",
            "ul. Freta",
            "ul. Furmańska",
            "ul. Garbarska",
            "ul. Garbary",
            "ul. Garncarska",
            "ul. Giserska",
            "ul. Gołębia",
            "ul. Grobla",
            "ul. Grodzka",
            "ul. Grzebiennicza",
            "ul. Górny Zaułek",
            "ul. Introligatorska",
            "ul. Jezuicka",
            "ul. Józefa",
            "ul. Kamieniczna",
            "ul. Kamienne Schodki",
            "ul. Kanonia",
            "ul. Kanonicza",
            "ul. Kapitulna",
            "ul. Katedralna",
            "ul. Katedralny Zaułek",
            "ul. Klasztorna",
            "ul. Klasztorny Zaułek",
            "ul. Kotlarska",
            "ul. Kowalska",
            "ul. Kozia",
            "ul. Kościelna",
            "ul. Kramarska",
            "ul. Krótka",
            "ul. Kręta",
            "ul. Kupa",
            "ul. Kupiecka",
            "ul. Kuśnierska",
            "ul. Ludwisarska",
            "ul. Mariacka",
            "ul. Mała",
            "ul. Mały Rynek",
            "ul. Mennicza",
            "ul. Miodowa",
            "ul. Mostowa",
            "ul. Mostowy Zaułek",
            "ul. Murarska",
            "ul. Młyńska",
            "ul. Młyński Zaułek",
            "ul. Nad Fosą",
            "ul. Nowomiejska",
            "ul. Nożownicza",
            "ul. Piekarska",
            "ul. Piwna",
            "ul. Pocztowa",
            "ul. Pod Basztą",
            "ul. Pod Bramą",
            "ul. Pod Katedrą",
            "ul. Pod Ratuszem",
            "ul. Pod Zamkiem",
            "ul. Podcieniowa",
            "ul. Podmurze",
            "ul. Podwale",
            "ul. Portowy Zaułek",
            "ul. Poselska",
            "ul. Powroźnicza",
            "ul. Przesmyk",
            "ul. Przy Murach",
            "ul. Przy Targu",
            "ul. Przyrynek",
            "ul. Rabina Meiselsa",
            "ul. Ratuszowa",
            "ul. Ratuszowy Zaułek",
            "ul. Rybacka",
            "ul. Rybna",
            "ul. Rymarska",
            "ul. Rzeźnicza",
            "ul. Schodkowa",
            "ul. Senatorska",
            "ul. Sienna",
            "ul. Siodlarska",
            "ul. Srebrnej Bramy",
            "ul. Starego Młyna",
            "ul. Starej Studni",
            "ul. Staromiejska",
            "ul. Stary Zaułek",
            "ul. Stolarska",
            "ul. Sukiennicza",
            "ul. Szeroka",
            "ul. Szewska",
            "ul. Targowa",
            "ul. Targowy Zaułek",
            "ul. Tkacka",
            "ul. Tylna",
            "ul. Wiślna",
            "ul. Woźna",
            "ul. Wroniecka",
            "ul. Wspólna",
            "ul. Wąska",
            "ul. Za Kościołem",
            "ul. Za Ratuszem",
            "ul. Zakręt",
            "ul. Zamkowa",
            "ul. Zamkowy Zaułek",
            "ul. Zaułek",
            "ul. Zduńska",
            "ul. Zielonej Bramy",
            "ul. Złotej Bramy",
            "ul. Złotnicza",
            "ul. Ślusarska",
            "ul. Świętojańska",
            "ul. Żydowska"
        };

        internal static readonly string[] ResidentialNames =
        {
            "ul. Agrestowa",
            "ul. Akacjowa",
            "ul. Akacjowa Dolina",
            "ul. Akacjowa Oaza",
            "ul. Akacjowa Polana",
            "ul. Akacjowa Przystań",
            "ul. Akacjowa Zatoka",
            "ul. Akacjowa Łąka",
            "ul. Akacjowe Osiedle",
            "ul. Akacjowe Pole",
            "ul. Akacjowe Przedmieście",
            "ul. Akacjowe Uroczysko",
            "ul. Akacjowe Wzgórze",
            "ul. Akacjowe Zacisze",
            "ul. Akacjowy Brzeg",
            "ul. Akacjowy Gaj",
            "ul. Akacjowy Most",
            "ul. Akacjowy Ogród",
            "ul. Akacjowy Stok",
            "ul. Akacjowy Szlak",
            "ul. Akacjowy Zakątek",
            "ul. Akacjowy Zaułek",
            "ul. Ametystowa",
            "ul. Azaliowa",
            "ul. Begoniowa",
            "ul. Bobrowa",
            "ul. Bociania",
            "ul. Borsucza",
            "ul. Borówkowa",
            "ul. Bratkowa",
            "ul. Brzoskwiniowa",
            "ul. Brzozowa",
            "ul. Brzozowa Dolina",
            "ul. Brzozowa Oaza",
            "ul. Brzozowa Polana",
            "ul. Brzozowa Przystań",
            "ul. Brzozowa Zatoka",
            "ul. Brzozowa Łąka",
            "ul. Brzozowe Osiedle",
            "ul. Brzozowe Pole",
            "ul. Brzozowe Przedmieście",
            "ul. Brzozowe Uroczysko",
            "ul. Brzozowe Wzgórze",
            "ul. Brzozowe Zacisze",
            "ul. Brzozowy Brzeg",
            "ul. Brzozowy Gaj",
            "ul. Brzozowy Most",
            "ul. Brzozowy Ogród",
            "ul. Brzozowy Stok",
            "ul. Brzozowy Szlak",
            "ul. Brzozowy Zakątek",
            "ul. Brzozowy Zaułek",
            "ul. Bukowa",
            "ul. Bukowa Dolina",
            "ul. Bukowa Oaza",
            "ul. Bukowa Polana",
            "ul. Bukowa Przystań",
            "ul. Bukowa Zatoka",
            "ul. Bukowa Łąka",
            "ul. Bukowe Osiedle",
            "ul. Bukowe Pole",
            "ul. Bukowe Przedmieście",
            "ul. Bukowe Uroczysko",
            "ul. Bukowe Wzgórze",
            "ul. Bukowe Zacisze",
            "ul. Bukowy Brzeg",
            "ul. Bukowy Gaj",
            "ul. Bukowy Most",
            "ul. Bukowy Ogród",
            "ul. Bukowy Stok",
            "ul. Bukowy Szlak",
            "ul. Bukowy Zakątek",
            "ul. Bukowy Zaułek",
            "ul. Bursztynowa",
            "ul. Bursztynowy Brzeg",
            "ul. Bursztynowy Gaj",
            "ul. Bursztynowy Most",
            "ul. Bursztynowy Ogród",
            "ul. Bursztynowy Stok",
            "ul. Bursztynowy Szlak",
            "ul. Bursztynowy Zakątek",
            "ul. Bursztynowy Zaułek",
            "ul. Bzowa",
            "ul. Błękitna",
            "ul. Chabrowa",
            "ul. Cicha",
            "ul. Cicha Dolina",
            "ul. Cicha Oaza",
            "ul. Cicha Polana",
            "ul. Cicha Przystań",
            "ul. Cicha Zatoka",
            "ul. Cicha Łąka",
            "ul. Ciche Osiedle",
            "ul. Ciche Pole",
            "ul. Ciche Przedmieście",
            "ul. Ciche Uroczysko",
            "ul. Ciche Wzgórze",
            "ul. Ciche Zacisze",
            "ul. Cichy Brzeg",
            "ul. Cichy Gaj",
            "ul. Cichy Most",
            "ul. Cichy Ogród",
            "ul. Cichy Stok",
            "ul. Cichy Szlak",
            "ul. Cichy Zakątek",
            "ul. Cichy Zaułek",
            "ul. Cisowa",
            "ul. Czereśniowa",
            "ul. Daliowa",
            "ul. Dolna",
            "ul. Dzięcioła",
            "ul. Dębowa",
            "ul. Dębowa Dolina",
            "ul. Dębowa Oaza",
            "ul. Dębowa Polana",
            "ul. Dębowa Przystań",
            "ul. Dębowa Zatoka",
            "ul. Dębowa Łąka",
            "ul. Dębowe Osiedle",
            "ul. Dębowe Pole",
            "ul. Dębowe Przedmieście",
            "ul. Dębowe Uroczysko",
            "ul. Dębowe Wzgórze",
            "ul. Dębowe Zacisze",
            "ul. Dębowy Brzeg",
            "ul. Dębowy Gaj",
            "ul. Dębowy Most",
            "ul. Dębowy Ogród",
            "ul. Dębowy Stok",
            "ul. Dębowy Szlak",
            "ul. Dębowy Zakątek",
            "ul. Dębowy Zaułek",
            "ul. Fiołkowa",
            "ul. Frezjowa",
            "ul. Grabowa",
            "ul. Gruszkowa",
            "ul. Górna",
            "ul. Górski Brzeg",
            "ul. Górski Gaj",
            "ul. Górski Most",
            "ul. Górski Ogród",
            "ul. Górski Stok",
            "ul. Górski Szlak",
            "ul. Górski Zakątek",
            "ul. Górski Zaułek",
            "ul. Górskie Osiedle",
            "ul. Górskie Pole",
            "ul. Górskie Przedmieście",
            "ul. Górskie Uroczysko",
            "ul. Górskie Wzgórze",
            "ul. Górskie Zacisze",
            "ul. Głogowa",
            "ul. Hiacyntowa",
            "ul. Hortensjowa",
            "ul. Irysowa",
            "ul. Jabłoniowa",
            "ul. Jabłoniowa Dolina",
            "ul. Jabłoniowa Oaza",
            "ul. Jabłoniowa Polana",
            "ul. Jabłoniowa Przystań",
            "ul. Jabłoniowa Zatoka",
            "ul. Jabłoniowa Łąka",
            "ul. Jagodowa",
            "ul. Jagodowa Dolina",
            "ul. Jagodowa Oaza",
            "ul. Jagodowa Polana",
            "ul. Jagodowa Przystań",
            "ul. Jagodowa Zatoka",
            "ul. Jagodowa Łąka",
            "ul. Jarzębinowa",
            "ul. Jarzębinowa Dolina",
            "ul. Jarzębinowa Oaza",
            "ul. Jarzębinowa Polana",
            "ul. Jarzębinowa Przystań",
            "ul. Jarzębinowa Zatoka",
            "ul. Jarzębinowa Łąka",
            "ul. Jaskółcza",
            "ul. Jasna",
            "ul. Jasna Dolina",
            "ul. Jasna Oaza",
            "ul. Jasna Polana",
            "ul. Jasna Przystań",
            "ul. Jasna Zatoka",
            "ul. Jasna Łąka",
            "ul. Jasne Osiedle",
            "ul. Jasne Pole",
            "ul. Jasne Przedmieście",
            "ul. Jasne Uroczysko",
            "ul. Jasne Wzgórze",
            "ul. Jasne Zacisze",
            "ul. Jasny Brzeg",
            "ul. Jasny Gaj",
            "ul. Jasny Most",
            "ul. Jasny Ogród",
            "ul. Jasny Stok",
            "ul. Jasny Szlak",
            "ul. Jasny Zakątek",
            "ul. Jasny Zaułek",
            "ul. Jaśminowa",
            "ul. Jelenia",
            "ul. Jesienna",
            "ul. Jesienna Dolina",
            "ul. Jesienna Oaza",
            "ul. Jesienna Polana",
            "ul. Jesienna Przystań",
            "ul. Jesienna Zatoka",
            "ul. Jesienna Łąka",
            "ul. Jesionowa",
            "ul. Jeziorna",
            "ul. Jeziorna Dolina",
            "ul. Jeziorna Oaza",
            "ul. Jeziorna Polana",
            "ul. Jeziorna Przystań",
            "ul. Jeziorna Zatoka",
            "ul. Jeziorna Łąka",
            "ul. Jeziorne Osiedle",
            "ul. Jeziorne Pole",
            "ul. Jeziorne Przedmieście",
            "ul. Jeziorne Uroczysko",
            "ul. Jeziorne Wzgórze",
            "ul. Jeziorne Zacisze",
            "ul. Jeżynowa",
            "ul. Jodłowa",
            "ul. Jodłowa Dolina",
            "ul. Jodłowa Oaza",
            "ul. Jodłowa Polana",
            "ul. Jodłowa Przystań",
            "ul. Jodłowa Zatoka",
            "ul. Jodłowa Łąka",
            "ul. Jodłowe Osiedle",
            "ul. Jodłowe Pole",
            "ul. Jodłowe Przedmieście",
            "ul. Jodłowe Uroczysko",
            "ul. Jodłowe Wzgórze",
            "ul. Jodłowe Zacisze",
            "ul. Jodłowy Brzeg",
            "ul. Jodłowy Gaj",
            "ul. Jodłowy Most",
            "ul. Jodłowy Ogród",
            "ul. Jodłowy Stok",
            "ul. Jodłowy Szlak",
            "ul. Jodłowy Zakątek",
            "ul. Jodłowy Zaułek",
            "ul. Kacza",
            "ul. Kamienna",
            "ul. Kamienny Brzeg",
            "ul. Kamienny Gaj",
            "ul. Kamienny Most",
            "ul. Kamienny Ogród",
            "ul. Kamienny Stok",
            "ul. Kamienny Szlak",
            "ul. Kamienny Zakątek",
            "ul. Kamienny Zaułek",
            "ul. Kasztanowa",
            "ul. Kasztanowa Dolina",
            "ul. Kasztanowa Oaza",
            "ul. Kasztanowa Polana",
            "ul. Kasztanowa Przystań",
            "ul. Kasztanowa Zatoka",
            "ul. Kasztanowa Łąka",
            "ul. Kasztanowe Osiedle",
            "ul. Kasztanowe Pole",
            "ul. Kasztanowe Przedmieście",
            "ul. Kasztanowe Uroczysko",
            "ul. Kasztanowe Wzgórze",
            "ul. Kasztanowe Zacisze",
            "ul. Kasztanowy Brzeg",
            "ul. Kasztanowy Gaj",
            "ul. Kasztanowy Most",
            "ul. Kasztanowy Ogród",
            "ul. Kasztanowy Stok",
            "ul. Kasztanowy Szlak",
            "ul. Kasztanowy Zakątek",
            "ul. Kasztanowy Zaułek",
            "ul. Klonowa",
            "ul. Klonowa Dolina",
            "ul. Klonowa Oaza",
            "ul. Klonowa Polana",
            "ul. Klonowa Przystań",
            "ul. Klonowa Zatoka",
            "ul. Klonowa Łąka",
            "ul. Klonowe Osiedle",
            "ul. Klonowe Pole",
            "ul. Klonowe Przedmieście",
            "ul. Klonowe Uroczysko",
            "ul. Klonowe Wzgórze",
            "ul. Klonowe Zacisze",
            "ul. Klonowy Brzeg",
            "ul. Klonowy Gaj",
            "ul. Klonowy Most",
            "ul. Klonowy Ogród",
            "ul. Klonowy Stok",
            "ul. Klonowy Szlak",
            "ul. Klonowy Zakątek",
            "ul. Klonowy Zaułek",
            "ul. Konwaliowa",
            "ul. Koralowa",
            "ul. Krokusowa",
            "ul. Kryształowa",
            "ul. Kryształowy Brzeg",
            "ul. Kryształowy Gaj",
            "ul. Kryształowy Most",
            "ul. Kryształowy Ogród",
            "ul. Kryształowy Stok",
            "ul. Kryształowy Szlak",
            "ul. Kryształowy Zakątek",
            "ul. Kryształowy Zaułek",
            "ul. Kukułcza",
            "ul. Kwiatowa",
            "ul. Kwiatowa Dolina",
            "ul. Kwiatowa Oaza",
            "ul. Kwiatowa Polana",
            "ul. Kwiatowa Przystań",
            "ul. Kwiatowa Zatoka",
            "ul. Kwiatowa Łąka",
            "ul. Kwiatowe Osiedle",
            "ul. Kwiatowe Pole",
            "ul. Kwiatowe Przedmieście",
            "ul. Kwiatowe Uroczysko",
            "ul. Kwiatowe Wzgórze",
            "ul. Kwiatowe Zacisze",
            "ul. Kwiatowy Brzeg",
            "ul. Kwiatowy Gaj",
            "ul. Kwiatowy Most",
            "ul. Kwiatowy Ogród",
            "ul. Kwiatowy Stok",
            "ul. Kwiatowy Szlak",
            "ul. Kwiatowy Zakątek",
            "ul. Kwiatowy Zaułek",
            "ul. Lawendowa",
            "ul. Lawendowa Dolina",
            "ul. Lawendowa Oaza",
            "ul. Lawendowa Polana",
            "ul. Lawendowa Przystań",
            "ul. Lawendowa Zatoka",
            "ul. Lawendowa Łąka",
            "ul. Leszczynowa",
            "ul. Letnia",
            "ul. Letnia Dolina",
            "ul. Letnia Oaza",
            "ul. Letnia Polana",
            "ul. Letnia Przystań",
            "ul. Letnia Zatoka",
            "ul. Letnia Łąka",
            "ul. Leśna",
            "ul. Leśna Dolina",
            "ul. Leśna Oaza",
            "ul. Leśna Polana",
            "ul. Leśna Przystań",
            "ul. Leśna Zatoka",
            "ul. Leśna Łąka",
            "ul. Leśne Osiedle",
            "ul. Leśne Pole",
            "ul. Leśne Przedmieście",
            "ul. Leśne Uroczysko",
            "ul. Leśne Wzgórze",
            "ul. Leśne Zacisze",
            "ul. Leśny Brzeg",
            "ul. Leśny Gaj",
            "ul. Leśny Most",
            "ul. Leśny Ogród",
            "ul. Leśny Stok",
            "ul. Leśny Szlak",
            "ul. Leśny Zakątek",
            "ul. Leśny Zaułek",
            "ul. Lipowa",
            "ul. Lipowa Dolina",
            "ul. Lipowa Oaza",
            "ul. Lipowa Polana",
            "ul. Lipowa Przystań",
            "ul. Lipowa Zatoka",
            "ul. Lipowa Łąka",
            "ul. Lipowe Osiedle",
            "ul. Lipowe Pole",
            "ul. Lipowe Przedmieście",
            "ul. Lipowe Uroczysko",
            "ul. Lipowe Wzgórze",
            "ul. Lipowe Zacisze",
            "ul. Lipowy Brzeg",
            "ul. Lipowy Gaj",
            "ul. Lipowy Most",
            "ul. Lipowy Ogród",
            "ul. Lipowy Stok",
            "ul. Lipowy Szlak",
            "ul. Lipowy Zakątek",
            "ul. Lipowy Zaułek",
            "ul. Lisia",
            "ul. Magnoliowa",
            "ul. Makowa",
            "ul. Malinowa",
            "ul. Malinowa Dolina",
            "ul. Malinowa Oaza",
            "ul. Malinowa Polana",
            "ul. Malinowa Przystań",
            "ul. Malinowa Zatoka",
            "ul. Malinowa Łąka",
            "ul. Malwowa",
            "ul. Mewia",
            "ul. Migdałowa",
            "ul. Modrzewiowa",
            "ul. Morelowa",
            "ul. Motylowa",
            "ul. Nadbrzeżna",
            "ul. Nadbrzeżna Dolina",
            "ul. Nadbrzeżna Oaza",
            "ul. Nadbrzeżna Polana",
            "ul. Nadbrzeżna Przystań",
            "ul. Nadbrzeżna Zatoka",
            "ul. Nadbrzeżna Łąka",
            "ul. Nadmorska",
            "ul. Nadmorski Brzeg",
            "ul. Nadmorski Gaj",
            "ul. Nadmorski Most",
            "ul. Nadmorski Ogród",
            "ul. Nadmorski Stok",
            "ul. Nadmorski Szlak",
            "ul. Nadmorski Zakątek",
            "ul. Nadmorski Zaułek",
            "ul. Nadmorskie Osiedle",
            "ul. Nadmorskie Pole",
            "ul. Nadmorskie Przedmieście",
            "ul. Nadmorskie Uroczysko",
            "ul. Nadmorskie Wzgórze",
            "ul. Nadmorskie Zacisze",
            "ul. Narcyzowa",
            "ul. Niedźwiedzia",
            "ul. Ogrodowa",
            "ul. Ogrodowa Dolina",
            "ul. Ogrodowa Oaza",
            "ul. Ogrodowa Polana",
            "ul. Ogrodowa Przystań",
            "ul. Ogrodowa Zatoka",
            "ul. Ogrodowa Łąka",
            "ul. Ogrodowe Osiedle",
            "ul. Ogrodowe Pole",
            "ul. Ogrodowe Przedmieście",
            "ul. Ogrodowe Uroczysko",
            "ul. Ogrodowe Wzgórze",
            "ul. Ogrodowe Zacisze",
            "ul. Ogrodowy Brzeg",
            "ul. Ogrodowy Gaj",
            "ul. Ogrodowy Most",
            "ul. Ogrodowy Ogród",
            "ul. Ogrodowy Stok",
            "ul. Ogrodowy Szlak",
            "ul. Ogrodowy Zakątek",
            "ul. Ogrodowy Zaułek",
            "ul. Olchowa",
            "ul. Orla",
            "ul. Orzechowa",
            "ul. Osiedlowa",
            "ul. Parkowa",
            "ul. Parkowa Dolina",
            "ul. Parkowa Oaza",
            "ul. Parkowa Polana",
            "ul. Parkowa Przystań",
            "ul. Parkowa Zatoka",
            "ul. Parkowa Łąka",
            "ul. Parkowe Osiedle",
            "ul. Parkowe Pole",
            "ul. Parkowe Przedmieście",
            "ul. Parkowe Uroczysko",
            "ul. Parkowe Wzgórze",
            "ul. Parkowe Zacisze",
            "ul. Parkowy Brzeg",
            "ul. Parkowy Gaj",
            "ul. Parkowy Most",
            "ul. Parkowy Ogród",
            "ul. Parkowy Stok",
            "ul. Parkowy Szlak",
            "ul. Parkowy Zakątek",
            "ul. Parkowy Zaułek",
            "ul. Perłowa",
            "ul. Piaskowa",
            "ul. Piwoniowa",
            "ul. Pogodna",
            "ul. Pogodna Dolina",
            "ul. Pogodna Oaza",
            "ul. Pogodna Polana",
            "ul. Pogodna Przystań",
            "ul. Pogodna Zatoka",
            "ul. Pogodna Łąka",
            "ul. Pogodne Osiedle",
            "ul. Pogodne Pole",
            "ul. Pogodne Przedmieście",
            "ul. Pogodne Uroczysko",
            "ul. Pogodne Wzgórze",
            "ul. Pogodne Zacisze",
            "ul. Pogodny Brzeg",
            "ul. Pogodny Gaj",
            "ul. Pogodny Most",
            "ul. Pogodny Ogród",
            "ul. Pogodny Stok",
            "ul. Pogodny Szlak",
            "ul. Pogodny Zakątek",
            "ul. Pogodny Zaułek",
            "ul. Polna",
            "ul. Polna Dolina",
            "ul. Polna Oaza",
            "ul. Polna Polana",
            "ul. Polna Przystań",
            "ul. Polna Zatoka",
            "ul. Polna Łąka",
            "ul. Polne Osiedle",
            "ul. Polne Pole",
            "ul. Polne Przedmieście",
            "ul. Polne Uroczysko",
            "ul. Polne Wzgórze",
            "ul. Polne Zacisze",
            "ul. Polny Brzeg",
            "ul. Polny Gaj",
            "ul. Polny Most",
            "ul. Polny Ogród",
            "ul. Polny Stok",
            "ul. Polny Szlak",
            "ul. Polny Zakątek",
            "ul. Polny Zaułek",
            "ul. Portowa",
            "ul. Porzeczkowa",
            "ul. Poziomkowa",
            "ul. Przyjazna",
            "ul. Przystaniowa",
            "ul. Pszczela",
            "ul. Puszczykowa",
            "ul. Radosna",
            "ul. Rododendronowa",
            "ul. Rodzinna",
            "ul. Rubinowa",
            "ul. Rubinowy Brzeg",
            "ul. Rubinowy Gaj",
            "ul. Rubinowy Most",
            "ul. Rubinowy Ogród",
            "ul. Rubinowy Stok",
            "ul. Rubinowy Szlak",
            "ul. Rubinowy Zakątek",
            "ul. Rubinowy Zaułek",
            "ul. Rzeczna",
            "ul. Rzeczna Dolina",
            "ul. Rzeczna Oaza",
            "ul. Rzeczna Polana",
            "ul. Rzeczna Przystań",
            "ul. Rzeczna Zatoka",
            "ul. Rzeczna Łąka",
            "ul. Rzeczne Osiedle",
            "ul. Rzeczne Pole",
            "ul. Rzeczne Przedmieście",
            "ul. Rzeczne Uroczysko",
            "ul. Rzeczne Wzgórze",
            "ul. Rzeczne Zacisze",
            "ul. Rzeczny Brzeg",
            "ul. Rzeczny Gaj",
            "ul. Rzeczny Most",
            "ul. Rzeczny Ogród",
            "ul. Rzeczny Stok",
            "ul. Rzeczny Szlak",
            "ul. Rzeczny Zakątek",
            "ul. Rzeczny Zaułek",
            "ul. Różana",
            "ul. Różana Dolina",
            "ul. Różana Oaza",
            "ul. Różana Polana",
            "ul. Różana Przystań",
            "ul. Różana Zatoka",
            "ul. Różana Łąka",
            "ul. Sadowa",
            "ul. Sarnia",
            "ul. Sikorkowa",
            "ul. Skowronkowa",
            "ul. Sokola",
            "ul. Sosnowa",
            "ul. Sosnowa Dolina",
            "ul. Sosnowa Oaza",
            "ul. Sosnowa Polana",
            "ul. Sosnowa Przystań",
            "ul. Sosnowa Zatoka",
            "ul. Sosnowa Łąka",
            "ul. Sosnowe Osiedle",
            "ul. Sosnowe Pole",
            "ul. Sosnowe Przedmieście",
            "ul. Sosnowe Uroczysko",
            "ul. Sosnowe Wzgórze",
            "ul. Sosnowe Zacisze",
            "ul. Sosnowy Brzeg",
            "ul. Sosnowy Gaj",
            "ul. Sosnowy Most",
            "ul. Sosnowy Ogród",
            "ul. Sosnowy Stok",
            "ul. Sosnowy Szlak",
            "ul. Sosnowy Zakątek",
            "ul. Sosnowy Zaułek",
            "ul. Spacerowa",
            "ul. Spokojna",
            "ul. Spokojna Dolina",
            "ul. Spokojna Oaza",
            "ul. Spokojna Polana",
            "ul. Spokojna Przystań",
            "ul. Spokojna Zatoka",
            "ul. Spokojna Łąka",
            "ul. Spokojne Osiedle",
            "ul. Spokojne Pole",
            "ul. Spokojne Przedmieście",
            "ul. Spokojne Uroczysko",
            "ul. Spokojne Wzgórze",
            "ul. Spokojne Zacisze",
            "ul. Spokojny Brzeg",
            "ul. Spokojny Gaj",
            "ul. Spokojny Most",
            "ul. Spokojny Ogród",
            "ul. Spokojny Stok",
            "ul. Spokojny Szlak",
            "ul. Spokojny Zakątek",
            "ul. Spokojny Zaułek",
            "ul. Sportowa",
            "ul. Srebrna",
            "ul. Srebrny Brzeg",
            "ul. Srebrny Gaj",
            "ul. Srebrny Most",
            "ul. Srebrny Ogród",
            "ul. Srebrny Stok",
            "ul. Srebrny Szlak",
            "ul. Srebrny Zakątek",
            "ul. Srebrny Zaułek",
            "ul. Stawowa",
            "ul. Stokrotkowa",
            "ul. Szkolna",
            "ul. Szmaragdowa",
            "ul. Szmaragdowy Brzeg",
            "ul. Szmaragdowy Gaj",
            "ul. Szmaragdowy Most",
            "ul. Szmaragdowy Ogród",
            "ul. Szmaragdowy Stok",
            "ul. Szmaragdowy Szlak",
            "ul. Szmaragdowy Zakątek",
            "ul. Szmaragdowy Zaułek",
            "ul. Sąsiedzka",
            "ul. Słoneczna",
            "ul. Słoneczna Dolina",
            "ul. Słoneczna Oaza",
            "ul. Słoneczna Polana",
            "ul. Słoneczna Przystań",
            "ul. Słoneczna Zatoka",
            "ul. Słoneczna Łąka",
            "ul. Słoneczne Osiedle",
            "ul. Słoneczne Pole",
            "ul. Słoneczne Przedmieście",
            "ul. Słoneczne Uroczysko",
            "ul. Słoneczne Wzgórze",
            "ul. Słoneczne Zacisze",
            "ul. Słonecznikowa",
            "ul. Słoneczny Brzeg",
            "ul. Słoneczny Gaj",
            "ul. Słoneczny Most",
            "ul. Słoneczny Ogród",
            "ul. Słoneczny Stok",
            "ul. Słoneczny Szlak",
            "ul. Słoneczny Zakątek",
            "ul. Słoneczny Zaułek",
            "ul. Słowicza",
            "ul. Tarninowa",
            "ul. Topolowa",
            "ul. Tulipanowa",
            "ul. Turkusowa",
            "ul. Tęczowa",
            "ul. Ważkowa",
            "ul. Wesoła",
            "ul. Widokowa",
            "ul. Widokowa Dolina",
            "ul. Widokowa Oaza",
            "ul. Widokowa Polana",
            "ul. Widokowa Przystań",
            "ul. Widokowa Zatoka",
            "ul. Widokowa Łąka",
            "ul. Widokowe Osiedle",
            "ul. Widokowe Pole",
            "ul. Widokowe Przedmieście",
            "ul. Widokowe Uroczysko",
            "ul. Widokowe Wzgórze",
            "ul. Widokowe Zacisze",
            "ul. Widokowy Brzeg",
            "ul. Widokowy Gaj",
            "ul. Widokowy Most",
            "ul. Widokowy Ogród",
            "ul. Widokowy Stok",
            "ul. Widokowy Szlak",
            "ul. Widokowy Zakątek",
            "ul. Widokowy Zaułek",
            "ul. Wierzbowa",
            "ul. Wierzbowa Dolina",
            "ul. Wierzbowa Oaza",
            "ul. Wierzbowa Polana",
            "ul. Wierzbowa Przystań",
            "ul. Wierzbowa Zatoka",
            "ul. Wierzbowa Łąka",
            "ul. Wiewiórcza",
            "ul. Wilcza",
            "ul. Winogronowa",
            "ul. Wiosenna",
            "ul. Wiosenna Dolina",
            "ul. Wiosenna Oaza",
            "ul. Wiosenna Polana",
            "ul. Wiosenna Przystań",
            "ul. Wiosenna Zatoka",
            "ul. Wiosenna Łąka",
            "ul. Wiosenne Osiedle",
            "ul. Wiosenne Pole",
            "ul. Wiosenne Przedmieście",
            "ul. Wiosenne Uroczysko",
            "ul. Wiosenne Wzgórze",
            "ul. Wiosenne Zacisze",
            "ul. Wiosenny Brzeg",
            "ul. Wiosenny Gaj",
            "ul. Wiosenny Most",
            "ul. Wiosenny Ogród",
            "ul. Wiosenny Stok",
            "ul. Wiosenny Szlak",
            "ul. Wiosenny Zakątek",
            "ul. Wiosenny Zaułek",
            "ul. Wiśniowa",
            "ul. Wiśniowa Dolina",
            "ul. Wiśniowa Oaza",
            "ul. Wiśniowa Polana",
            "ul. Wiśniowa Przystań",
            "ul. Wiśniowa Zatoka",
            "ul. Wiśniowa Łąka",
            "ul. Wrzosowa",
            "ul. Wrzosowa Dolina",
            "ul. Wrzosowa Oaza",
            "ul. Wrzosowa Polana",
            "ul. Wrzosowa Przystań",
            "ul. Wrzosowa Zatoka",
            "ul. Wrzosowa Łąka",
            "ul. Wrzosowe Osiedle",
            "ul. Wrzosowe Pole",
            "ul. Wrzosowe Przedmieście",
            "ul. Wrzosowe Uroczysko",
            "ul. Wrzosowe Wzgórze",
            "ul. Wrzosowe Zacisze",
            "ul. Wrzosowy Brzeg",
            "ul. Wrzosowy Gaj",
            "ul. Wrzosowy Most",
            "ul. Wrzosowy Ogród",
            "ul. Wrzosowy Stok",
            "ul. Wrzosowy Szlak",
            "ul. Wrzosowy Zakątek",
            "ul. Wrzosowy Zaułek",
            "ul. Wydmowa",
            "ul. Wydrowa",
            "ul. Zaciszna",
            "ul. Zajęcza",
            "ul. Zielona",
            "ul. Zielona Dolina",
            "ul. Zielona Oaza",
            "ul. Zielona Polana",
            "ul. Zielona Przystań",
            "ul. Zielona Zatoka",
            "ul. Zielona Łąka",
            "ul. Zielone Osiedle",
            "ul. Zielone Pole",
            "ul. Zielone Przedmieście",
            "ul. Zielone Uroczysko",
            "ul. Zielone Wzgórze",
            "ul. Zielone Zacisze",
            "ul. Zielony Brzeg",
            "ul. Zielony Gaj",
            "ul. Zielony Most",
            "ul. Zielony Ogród",
            "ul. Zielony Stok",
            "ul. Zielony Szlak",
            "ul. Zielony Zakątek",
            "ul. Zielony Zaułek",
            "ul. Zimowa",
            "ul. Zimowa Dolina",
            "ul. Zimowa Oaza",
            "ul. Zimowa Polana",
            "ul. Zimowa Przystań",
            "ul. Zimowa Zatoka",
            "ul. Zimowa Łąka",
            "ul. Złota",
            "ul. Złoty Brzeg",
            "ul. Złoty Gaj",
            "ul. Złoty Most",
            "ul. Złoty Ogród",
            "ul. Złoty Stok",
            "ul. Złoty Szlak",
            "ul. Złoty Zakątek",
            "ul. Złoty Zaułek",
            "ul. Łabędzia",
            "ul. Łąkowa",
            "ul. Łąkowa Dolina",
            "ul. Łąkowa Oaza",
            "ul. Łąkowa Polana",
            "ul. Łąkowa Przystań",
            "ul. Łąkowa Zatoka",
            "ul. Łąkowa Łąka",
            "ul. Śliwkowa",
            "ul. Świerkowa",
            "ul. Świerkowa Dolina",
            "ul. Świerkowa Oaza",
            "ul. Świerkowa Polana",
            "ul. Świerkowa Przystań",
            "ul. Świerkowa Zatoka",
            "ul. Świerkowa Łąka",
            "ul. Świerkowe Osiedle",
            "ul. Świerkowe Pole",
            "ul. Świerkowe Przedmieście",
            "ul. Świerkowe Uroczysko",
            "ul. Świerkowe Wzgórze",
            "ul. Świerkowe Zacisze",
            "ul. Świerkowy Brzeg",
            "ul. Świerkowy Gaj",
            "ul. Świerkowy Most",
            "ul. Świerkowy Ogród",
            "ul. Świerkowy Stok",
            "ul. Świerkowy Szlak",
            "ul. Świerkowy Zakątek",
            "ul. Świerkowy Zaułek",
            "ul. Źródlana",
            "ul. Źródlana Dolina",
            "ul. Źródlana Oaza",
            "ul. Źródlana Polana",
            "ul. Źródlana Przystań",
            "ul. Źródlana Zatoka",
            "ul. Źródlana Łąka",
            "ul. Żabia",
            "ul. Żeglarska",
            "ul. Żurawia",
            "ul. Żurawinowa"
        };

        internal static readonly string[] StandardNames =
        {
            "ul. Adama Mickiewicza",
            "ul. Akademicka",
            "ul. Andrzeja Wajdy",
            "ul. Archiwalna",
            "ul. Artura Grottgera",
            "ul. Badawcza",
            "ul. Białostocka",
            "ul. Biblioteczna",
            "ul. Bohaterów Monte Cassino",
            "ul. Bolesława Chrobrego",
            "ul. Bolesława Prusa",
            "ul. Bydgoska",
            "ul. Centralna",
            "ul. Centrum Logistycznego",
            "ul. Centrum Nauki",
            "ul. Chmielna",
            "ul. Cypriana Kamila Norwida",
            "ul. Czesława Miłosza",
            "ul. Dietla",
            "ul. Dworca Autobusowego",
            "ul. Dworcowa",
            "ul. Długa",
            "ul. Elizy Orzeszkowej",
            "ul. Energetyczna",
            "ul. Ernesta Malinowskiego",
            "ul. Eugeniusza Kwiatkowskiego",
            "ul. Europejska",
            "ul. Fabryczna",
            "ul. Filharmonii",
            "ul. Floriańska",
            "ul. Freta",
            "ul. Fryderyka Chopina",
            "ul. Galerii Sztuki",
            "ul. Gdańska",
            "ul. Gdyńska",
            "ul. Grażyny Bacewicz",
            "ul. Grodzka",
            "ul. Górnicza",
            "ul. Główna",
            "ul. Hali Widowiskowej",
            "ul. Handlowa",
            "ul. Henryka Sienkiewicza",
            "ul. Henryka Wieniawskiego",
            "ul. Hoża",
            "ul. Hugo Steinhausa",
            "ul. Hutnicza",
            "ul. Ignacego Paderewskiego",
            "ul. Ignacego Łukasiewicza",
            "ul. Ireny Sendlerowej",
            "ul. Jana Czochralskiego",
            "ul. Jana Heweliusza",
            "ul. Jana III Sobieskiego",
            "ul. Jana Kilińskiego",
            "ul. Jana Kochanowskiego",
            "ul. Jana Matejki",
            "ul. Janusza Korczaka",
            "ul. Jarosława Iwaszkiewicza",
            "ul. Jedności",
            "ul. Juliusza Słowackiego",
            "ul. Józefa Piłsudskiego",
            "ul. Karmelicka",
            "ul. Karola Olszewskiego",
            "ul. Karola Szymanowskiego",
            "ul. Kaszubska",
            "ul. Katowicka",
            "ul. Kazimierza Funka",
            "ul. Kazimierza Wielkiego",
            "ul. Kielecka",
            "ul. Kolejowa",
            "ul. Konstruktorów",
            "ul. Konstytucji",
            "ul. Kornela Makuszyńskiego",
            "ul. Kościelna",
            "ul. Krakowska",
            "ul. Krakowskie Przedmieście",
            "ul. Krucza",
            "ul. Krzysztofa Kieślowskiego",
            "ul. Krzysztofa Pendereckiego",
            "ul. Kujawska",
            "ul. Laboratoryjna",
            "ul. Lotnicza",
            "ul. Lotników",
            "ul. Lubelska",
            "ul. Marii Dąbrowskiej",
            "ul. Marii Skłodowskiej-Curie",
            "ul. Marszałkowska",
            "ul. Marynarzy",
            "ul. Mazowiecka",
            "ul. Mazurska",
            "ul. Małopolska",
            "ul. Medialna",
            "ul. Mieszka I",
            "ul. Mikołaja Kopernika",
            "ul. Mikołaja Reja",
            "ul. Miodowa",
            "ul. Mokotowska",
            "ul. Mostowa",
            "ul. Muzealna",
            "ul. Nadbrzeżna",
            "ul. Niepodległości",
            "ul. Nowy Świat",
            "ul. Olgi Boznańskiej",
            "ul. Olsztyńska",
            "ul. Operowa",
            "ul. Opolska",
            "ul. Oskara Kolberga",
            "ul. Oławska",
            "ul. Parku Technologicznego",
            "ul. Piotrkowska",
            "ul. Pocztowa",
            "ul. Podlaska",
            "ul. Pokoju",
            "ul. Pomorska",
            "ul. Portowa",
            "ul. Portu Lotniczego",
            "ul. Poznańska",
            "ul. Południowa",
            "ul. Programistów",
            "ul. Przemysłowa",
            "ul. Puławska",
            "ul. Północna",
            "ul. Półwiejska",
            "ul. Radomska",
            "ul. Ratuszowa",
            "ul. Robotnicza",
            "ul. Robotyków",
            "ul. Romualda Traugutta",
            "ul. Rudolfa Modrzejewskiego",
            "ul. Ruska",
            "ul. Ryszarda Kapuścińskiego",
            "ul. Rzeszowska",
            "ul. Senatorska",
            "ul. Solidarności",
            "ul. Sopocka",
            "ul. Stanisława Lema",
            "ul. Stanisława Moniuszki",
            "ul. Stanisława Staszica",
            "ul. Stanisława Ulama",
            "ul. Stanisława Wyspiańskiego",
            "ul. Starowiślna",
            "ul. Stefana Banacha",
            "ul. Stefana Batorego",
            "ul. Stefana Żeromskiego",
            "ul. Szczecińska",
            "ul. Szeroka",
            "ul. Szewska",
            "ul. Szkolna",
            "ul. Tadeusza Kościuszki",
            "ul. Tadeusza Różewicza",
            "ul. Tamary Łempickiej",
            "ul. Tamka",
            "ul. Targowa",
            "ul. Targów Miejskich",
            "ul. Teatralna",
            "ul. Techniczna",
            "ul. Toruńska",
            "ul. Uniwersytecka",
            "ul. Wacława Sierpińskiego",
            "ul. Warmińska",
            "ul. Warszawska",
            "ul. Wielkopolska",
            "ul. Wilcza",
            "ul. Wisławy Szymborskiej",
            "ul. Witolda Lutosławskiego",
            "ul. Witolda Pileckiego",
            "ul. Wojciecha Kilara",
            "ul. Wolności",
            "ul. Wrocławska",
            "ul. Wschodnia",
            "ul. Wspólna",
            "ul. Władysława Jagiełły",
            "ul. Władysława Reymonta",
            "ul. Zachodnia",
            "ul. Zakopiańska",
            "ul. Zbigniewa Herberta",
            "ul. Zielonogórska",
            "ul. Zofii Nałkowskiej",
            "ul. Zwierzyniecka",
            "ul. Zwycięstwa",
            "ul. Zygmunta Wróblewskiego",
            "ul. Łódzka",
            "ul. Śląska",
            "ul. Świdnicka",
            "ul. Świętokrzyska"
        };

        internal static readonly string[] AvenueNames =
        {
            "al. Armii Krajowej",
            "al. Banacha",
            "al. Beskidzka",
            "al. Biebrzańska",
            "al. Bieszczadzka",
            "al. Brzozowa",
            "al. Bug",
            "al. Bursztynowa",
            "al. Chopina",
            "al. Demokracji",
            "al. Dunajec",
            "al. Dworcowa",
            "al. Dębowa",
            "al. Europejska",
            "al. Europejska Południowa",
            "al. Europejska Północna",
            "al. Grunwaldzka",
            "al. Hallera",
            "al. Handlu",
            "al. Heweliusza",
            "al. Innowacji",
            "al. Jana III Sobieskiego",
            "al. Jana Pawła II",
            "al. Jerozolimskie",
            "al. Jurajska",
            "al. Karkonoska",
            "al. Kasztanowa",
            "al. Kaszubska",
            "al. Kolejowa",
            "al. Komisji Edukacji Narodowej",
            "al. Konstytucji 3 Maja",
            "al. Kopernika",
            "al. Kościuszki",
            "al. Krakowska",
            "al. Kwiatowa",
            "al. Legionów",
            "al. Lema",
            "al. Lipowa",
            "al. Lipowa Południowa",
            "al. Lipowa Północna",
            "al. Lotnicza",
            "al. Magnoliowa",
            "al. Marszałka Józefa Piłsudskiego",
            "al. Mazowiecka",
            "al. Mazurska",
            "al. Mickiewicza",
            "al. Miłosza",
            "al. Monte Cassino",
            "al. Młodzieży",
            "al. Nadbałtycka",
            "al. Nadmorska",
            "al. Nadodrzańska",
            "al. Nadwiślańska",
            "al. Narew",
            "al. Nauki",
            "al. Niepodległości",
            "al. Odrodzenia",
            "al. Odrzańska",
            "al. Ogrodowa",
            "al. Parkowa",
            "al. Parkowa Południowa",
            "al. Parkowa Północna",
            "al. Perłowa",
            "al. Piastów",
            "al. Piłsudskiego",
            "al. Podhalańska",
            "al. Pokoju",
            "al. Pomorska",
            "al. Porozumienia",
            "al. Portowa",
            "al. Powstańców Warszawy",
            "al. Powstańców Śląskich",
            "al. Praw Człowieka",
            "al. Prymasa Tysiąclecia",
            "al. Przemysłu",
            "al. Przyjaźni",
            "al. Reymonta",
            "al. Roztoczańska",
            "al. Rubinowa",
            "al. Rzeczypospolitej",
            "al. Róż",
            "al. San",
            "al. Sienkiewicza",
            "al. Skłodowskiej-Curie",
            "al. Solidarności",
            "al. Spacerowa",
            "al. Sportowa",
            "al. Stanów Zjednoczonych",
            "al. Sudecka",
            "al. Szmaragdowa",
            "al. Szymborskiej",
            "al. Słoneczna",
            "al. Słowackiego",
            "al. Tatrzańska",
            "al. Technologii",
            "al. Tysiąclecia",
            "al. Uniwersytecka",
            "al. Warta",
            "al. Waszyngtona",
            "al. Wiedzy",
            "al. Wielkopolska",
            "al. Wilanowska",
            "al. Wiślana",
            "al. Wojska Polskiego",
            "al. Wolnej Polski",
            "al. Wolności",
            "al. Wspólnoty",
            "al. Władysława Reymonta",
            "al. Zwycięstwa",
            "al. Śląska"
        };

        internal static readonly string[] HighwayRouteNames =
        {
            "A1",
            "A18",
            "A2",
            "A4",
            "A6",
            "A8",
            "DK 1",
            "DK 10",
            "DK 11",
            "DK 12",
            "DK 15",
            "DK 16",
            "DK 17",
            "DK 19",
            "DK 2",
            "DK 20",
            "DK 22",
            "DK 24",
            "DK 25",
            "DK 28",
            "DK 3",
            "DK 32",
            "DK 35",
            "DK 36",
            "DK 39",
            "DK 42",
            "DK 44",
            "DK 45",
            "DK 46",
            "DK 47",
            "DK 48",
            "DK 5",
            "DK 50",
            "DK 51",
            "DK 53",
            "DK 55",
            "DK 57",
            "DK 58",
            "DK 60",
            "DK 61",
            "DK 62",
            "DK 63",
            "DK 65",
            "DK 67",
            "DK 7",
            "DK 73",
            "DK 74",
            "DK 75",
            "DK 77",
            "DK 78",
            "DK 79",
            "DK 8",
            "DK 81",
            "DK 82",
            "DK 84",
            "DK 9",
            "Obwodnica Trójmiasta",
            "Południowa Obwodnica Warszawy",
            "Północna Obwodnica Krakowa",
            "S1",
            "S10",
            "S11",
            "S12",
            "S14",
            "S16",
            "S17",
            "S19",
            "S2",
            "S22",
            "S3",
            "S5",
            "S50",
            "S51",
            "S52",
            "S6",
            "S61",
            "S7",
            "S74",
            "S8",
            "S86",
            "Trasa Bursztynowa",
            "Trasa Karkonoska",
            "Trasa Kaszubska",
            "Trasa Mostu Północnego",
            "Trasa Nadodrzańska",
            "Trasa Nadwiślańska",
            "Trasa Siekierkowska",
            "Trasa Toruńska",
            "Trasa Łazienkowska",
            "Wisłostrada",
            "Wschodnia Obwodnica Wrocławia",
            "Zachodnia Obwodnica Poznania"
        };
    }
}
