// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class PolishRoadNames
    {
        internal static readonly string[] DirtNames =
        {
            "Droga Leśna",
            "Droga Polna",
            "Droga Łąkowa",
            "Droga Brzozowa",
            "Droga Dębowa",
            "Droga Sosnowa",
            "Droga Bukowa",
            "Droga Modrzewiowa",
            "Droga Wierzbowa",
            "Droga Lipowa",
            "Droga Kasztanowa",
            "Droga Świerkowa",
            "Droga Jodłowa",
            "Droga Jałowcowa",
            "Droga Górska",
            "Droga Dolinna",
            "Droga Nadleśna",
            "Droga Nadjeziorna",
            "Droga Nadwiślańska",
            "Droga Nadodrzańska",
            "Droga Wrzosowa",
            "Droga Kamienna",
            "Droga Piaszczysta",
            "Droga Graniczna",
            "Droga Myśliwska",
            "Droga Rolna",
            "Droga Folwarczna",
            "Droga Młyńska",
            "Droga Rzeczna",
            "Droga Stawowa",
            "Droga Bagienna",
            "Droga Źródlana",
            "Droga Leśników",
            "Droga Rybaków",
            "Droga Gajowa",
            "Droga Borowa",
            "Droga Puszczańska",
            "Droga Kaszubska",
            "Droga Mazurska",
            "Droga Bieszczadzka",
            "Droga Tatrzańska",
            "Droga Sudecka",
            "Droga Beskidzka",
            "Droga Jurajska",
            "Droga Kampinoska",
            "Droga Białowieska",
            "Droga Pienińska",
            "Droga Roztoczańska",
            "Droga Podhalańska",
            "Droga Lubelska",
            "Droga Mazowiecka",
            "Droga Podlaska",
            "Droga Wielkopolska",
            "Droga Pomorska",
            "Droga Kujawska",
            "Droga Śląska",
            "Droga Małopolska",
            "Droga Warmińska",
            "Droga Karkonoska",
            "Droga Słoneczna",
            "Droga Spacerowa",
            "Droga Cisowa",
            "Droga Klonowa",
            "Droga Jarzębinowa",
            "Droga Akacjowa",
            "Droga Topolowa",
            "Droga Leszczynowa",
            "Droga Malinowa",
            "Droga Jagodowa",
            "Droga Grzybowa",
            "Droga Leśna Polana",
            "Droga Zielona",
            "Droga Zaciszna",
            "Droga Spokojna",
            "Droga Widokowa",
            "Droga Dojazdowa",
            "Droga Wodna",
            "Droga Mostowa",
            "Droga Stara",
            "Droga Nowa"
        };

        internal static readonly string[] AlleyNames =
        {
            "ul. Krótka",
            "ul. Cicha",
            "ul. Wąska",
            "ul. Mała",
            "ul. Tylna",
            "ul. Boczna",
            "ul. Zaułek",
            "ul. Podwale",
            "ul. Podmurze",
            "ul. Przyrynek",
            "ul. Ratuszowa",
            "ul. Kościelna",
            "ul. Klasztorna",
            "ul. Młyńska",
            "ul. Browarna",
            "ul. Piwna",
            "ul. Szewska",
            "ul. Garncarska",
            "ul. Tkacka",
            "ul. Bednarska",
            "ul. Rzeźnicza",
            "ul. Piekarska",
            "ul. Rybacka",
            "ul. Mennicza",
            "ul. Grodzka",
            "ul. Zamkowa",
            "ul. Basztowa",
            "ul. Bramowa",
            "ul. Furmańska",
            "ul. Kupiecka",
            "ul. Targowa",
            "ul. Pocztowa",
            "ul. Sienna",
            "ul. Wspólna",
            "ul. Chmielna",
            "ul. Miodowa",
            "ul. Długa",
            "ul. Freta",
            "ul. Kanonia",
            "ul. Brzozowa",
            "ul. Kamienne Schodki",
            "ul. Mostowa",
            "ul. Jezuicka",
            "ul. Świętojańska",
            "ul. Senatorska",
            "ul. Kapitulna",
            "ul. Rybna",
            "ul. Celna",
            "ul. Dawna",
            "ul. Nowomiejska",
            "ul. Staromiejska",
            "ul. Mariacka",
            "ul. Dominikańska",
            "ul. Franciszkańska",
            "ul. Floriańska",
            "ul. Poselska",
            "ul. Stolarska",
            "ul. Gołębia",
            "ul. Bracka",
            "ul. Wiślna",
            "ul. Kanonicza",
            "ul. Józefa",
            "ul. Szeroka",
            "ul. Ciemna",
            "ul. Estery",
            "ul. Kupa",
            "ul. Rabina Meiselsa",
            "ul. Bożego Ciała",
            "ul. Grobla",
            "ul. Garbary",
            "ul. Kramarska",
            "ul. Woźna",
            "ul. Żydowska",
            "ul. Wroniecka",
            "ul. Kozia",
            "ul. Ślusarska",
            "ul. Katedralna"
        };

        internal static readonly string[] ResidentialNames =
        {
            "ul. Leśna",
            "ul. Polna",
            "ul. Ogrodowa",
            "ul. Parkowa",
            "ul. Lipowa",
            "ul. Brzozowa",
            "ul. Dębowa",
            "ul. Klonowa",
            "ul. Sosnowa",
            "ul. Wierzbowa",
            "ul. Kasztanowa",
            "ul. Akacjowa",
            "ul. Topolowa",
            "ul. Bukowa",
            "ul. Modrzewiowa",
            "ul. Świerkowa",
            "ul. Jodłowa",
            "ul. Jaśminowa",
            "ul. Różana",
            "ul. Tulipanowa",
            "ul. Kwiatowa",
            "ul. Fiołkowa",
            "ul. Lawendowa",
            "ul. Konwaliowa",
            "ul. Malwowa",
            "ul. Wrzosowa",
            "ul. Słoneczna",
            "ul. Spacerowa",
            "ul. Spokojna",
            "ul. Zaciszna",
            "ul. Cicha",
            "ul. Pogodna",
            "ul. Wiosenna",
            "ul. Letnia",
            "ul. Jesienna",
            "ul. Zimowa",
            "ul. Tęczowa",
            "ul. Zielona",
            "ul. Błękitna",
            "ul. Jasna",
            "ul. Widokowa",
            "ul. Wzgórze",
            "ul. Łąkowa",
            "ul. Dolna",
            "ul. Górna",
            "ul. Źródlana",
            "ul. Rzeczna",
            "ul. Stawowa",
            "ul. Jeziorna",
            "ul. Nadbrzeżna",
            "ul. Piaskowa",
            "ul. Kamienna",
            "ul. Szkolna",
            "ul. Sportowa",
            "ul. Ogrodnicza",
            "ul. Rolnicza",
            "ul. Sadowa",
            "ul. Morelowa",
            "ul. Wiśniowa",
            "ul. Czereśniowa",
            "ul. Jabłoniowa",
            "ul. Gruszkowa",
            "ul. Malinowa",
            "ul. Poziomkowa",
            "ul. Jagodowa",
            "ul. Żurawinowa",
            "ul. Słowicza",
            "ul. Jaskółcza",
            "ul. Sokola",
            "ul. Orla",
            "ul. Bociania",
            "ul. Kukułcza",
            "ul. Zajęcza",
            "ul. Lisia",
            "ul. Sarnia",
            "ul. Jelenia",
            "ul. Wiewiórcza",
            "ul. Borsucza",
            "ul. Niedźwiedzia",
            "ul. Królicza",
            "ul. Przyjazna",
            "ul. Rodzinna",
            "ul. Sąsiedzka",
            "ul. Osiedlowa",
            "ul. Domowa",
            "ul. Zacisze",
            "ul. Dobra",
            "ul. Miła",
            "ul. Radosna",
            "ul. Wesoła",
            "ul. Szczęśliwa",

            "ul. Leśna Polana",
            "ul. Leśna Dolina",
            "ul. Leśna Łąka",
            "ul. Leśna Przystań",
            "ul. Leśna Oaza",
            "ul. Leśna Zatoka",
            "ul. Słoneczna Polana",
            "ul. Słoneczna Dolina",
            "ul. Słoneczna Łąka",
            "ul. Słoneczna Przystań",
            "ul. Słoneczna Oaza",
            "ul. Słoneczna Zatoka",
            "ul. Zielona Polana",
            "ul. Zielona Dolina",
            "ul. Zielona Łąka",
            "ul. Zielona Przystań",
            "ul. Zielona Oaza",
            "ul. Zielona Zatoka",
            "ul. Cicha Polana",
            "ul. Cicha Dolina",
            "ul. Cicha Łąka",
            "ul. Cicha Przystań",
            "ul. Cicha Oaza",
            "ul. Cicha Zatoka",
            "ul. Spokojna Polana",
            "ul. Spokojna Dolina",
            "ul. Spokojna Łąka",
            "ul. Spokojna Przystań",
            "ul. Spokojna Oaza",
            "ul. Spokojna Zatoka",
            "ul. Jasna Polana",
            "ul. Jasna Dolina",
            "ul. Jasna Łąka",
            "ul. Jasna Przystań",
            "ul. Jasna Oaza",
            "ul. Jasna Zatoka",
            "ul. Pogodna Polana",
            "ul. Pogodna Dolina",
            "ul. Pogodna Łąka",
            "ul. Pogodna Przystań",
            "ul. Pogodna Oaza",
            "ul. Pogodna Zatoka",
            "ul. Wiosenna Polana",
            "ul. Wiosenna Dolina",
            "ul. Wiosenna Łąka",
            "ul. Wiosenna Przystań",
            "ul. Wiosenna Oaza",
            "ul. Wiosenna Zatoka",
            "ul. Letnia Polana",
            "ul. Letnia Dolina",
            "ul. Letnia Łąka",
            "ul. Letnia Przystań",
            "ul. Letnia Oaza",
            "ul. Letnia Zatoka",
            "ul. Jesienna Polana",
            "ul. Jesienna Dolina",
            "ul. Jesienna Łąka",
            "ul. Jesienna Przystań",
            "ul. Jesienna Oaza",
            "ul. Jesienna Zatoka",
            "ul. Zimowa Polana",
            "ul. Zimowa Dolina",
            "ul. Zimowa Łąka",
            "ul. Zimowa Przystań",
            "ul. Zimowa Oaza",
            "ul. Zimowa Zatoka",
            "ul. Kwiatowa Polana",
            "ul. Kwiatowa Dolina",
            "ul. Kwiatowa Łąka",
            "ul. Kwiatowa Przystań",
            "ul. Kwiatowa Oaza",
            "ul. Kwiatowa Zatoka",
            "ul. Różana Polana",
            "ul. Różana Dolina",
            "ul. Różana Łąka",
            "ul. Różana Przystań",
            "ul. Różana Oaza",
            "ul. Różana Zatoka",
            "ul. Lipowa Polana",
            "ul. Lipowa Dolina",
            "ul. Lipowa Łąka",
            "ul. Lipowa Przystań",
            "ul. Lipowa Oaza",
            "ul. Lipowa Zatoka",
            "ul. Brzozowa Polana",
            "ul. Brzozowa Dolina",
            "ul. Brzozowa Łąka",
            "ul. Brzozowa Przystań",
            "ul. Brzozowa Oaza",
            "ul. Brzozowa Zatoka",
            "ul. Dębowa Polana",
            "ul. Dębowa Dolina",
            "ul. Dębowa Łąka",
            "ul. Dębowa Przystań",
            "ul. Dębowa Oaza",
            "ul. Dębowa Zatoka",
            "ul. Klonowa Polana",
            "ul. Klonowa Dolina",
            "ul. Klonowa Łąka",
            "ul. Klonowa Przystań",
            "ul. Klonowa Oaza",
            "ul. Klonowa Zatoka",
            "ul. Sosnowa Polana",
            "ul. Sosnowa Dolina",
            "ul. Sosnowa Łąka",
            "ul. Sosnowa Przystań",
            "ul. Sosnowa Oaza",
            "ul. Sosnowa Zatoka",
            "ul. Wierzbowa Polana",
            "ul. Wierzbowa Dolina",
            "ul. Wierzbowa Łąka",
            "ul. Wierzbowa Przystań",
            "ul. Wierzbowa Oaza",
            "ul. Wierzbowa Zatoka",
            "ul. Kasztanowa Polana",
            "ul. Kasztanowa Dolina",
            "ul. Kasztanowa Łąka",
            "ul. Kasztanowa Przystań",
            "ul. Kasztanowa Oaza",
            "ul. Kasztanowa Zatoka",
            "ul. Akacjowa Polana",
            "ul. Akacjowa Dolina",
            "ul. Akacjowa Łąka",
            "ul. Akacjowa Przystań",
            "ul. Akacjowa Oaza",
            "ul. Akacjowa Zatoka",
            "ul. Bukowa Polana",
            "ul. Bukowa Dolina",
            "ul. Bukowa Łąka",
            "ul. Bukowa Przystań",
            "ul. Bukowa Oaza",
            "ul. Bukowa Zatoka",
            "ul. Świerkowa Polana",
            "ul. Świerkowa Dolina",
            "ul. Świerkowa Łąka",
            "ul. Świerkowa Przystań",
            "ul. Świerkowa Oaza",
            "ul. Świerkowa Zatoka",
            "ul. Jodłowa Polana",
            "ul. Jodłowa Dolina",
            "ul. Jodłowa Łąka",
            "ul. Jodłowa Przystań",
            "ul. Jodłowa Oaza",
            "ul. Jodłowa Zatoka",
            "ul. Łąkowa Polana",
            "ul. Łąkowa Dolina",
            "ul. Łąkowa Łąka",
            "ul. Łąkowa Przystań",
            "ul. Łąkowa Oaza",
            "ul. Łąkowa Zatoka",
            "ul. Polna Polana",
            "ul. Polna Dolina",
            "ul. Polna Łąka",
            "ul. Polna Przystań",
            "ul. Polna Oaza",
            "ul. Polna Zatoka",
            "ul. Parkowa Polana",
            "ul. Parkowa Dolina",
            "ul. Parkowa Łąka",
            "ul. Parkowa Przystań",
            "ul. Parkowa Oaza",
            "ul. Parkowa Zatoka",
            "ul. Ogrodowa Polana",
            "ul. Ogrodowa Dolina",
            "ul. Ogrodowa Łąka",
            "ul. Ogrodowa Przystań",
            "ul. Ogrodowa Oaza",
            "ul. Ogrodowa Zatoka",
            "ul. Rzeczna Polana",
            "ul. Rzeczna Dolina",
            "ul. Rzeczna Łąka",
            "ul. Rzeczna Przystań",
            "ul. Rzeczna Oaza",
            "ul. Rzeczna Zatoka",
            "ul. Jeziorna Polana",
            "ul. Jeziorna Dolina",
            "ul. Jeziorna Łąka",
            "ul. Jeziorna Przystań",
            "ul. Jeziorna Oaza",
            "ul. Jeziorna Zatoka",
            "ul. Nadbrzeżna Polana",
            "ul. Nadbrzeżna Dolina",
            "ul. Nadbrzeżna Łąka",
            "ul. Nadbrzeżna Przystań",
            "ul. Nadbrzeżna Oaza",
            "ul. Nadbrzeżna Zatoka",
            "ul. Źródlana Polana",
            "ul. Źródlana Dolina",
            "ul. Źródlana Łąka",
            "ul. Źródlana Przystań",
            "ul. Źródlana Oaza",
            "ul. Źródlana Zatoka",
            "ul. Widokowa Polana",
            "ul. Widokowa Dolina",
            "ul. Widokowa Łąka",
            "ul. Widokowa Przystań",
            "ul. Widokowa Oaza",
            "ul. Widokowa Zatoka",
            "ul. Malinowa Polana",
            "ul. Malinowa Dolina",
            "ul. Malinowa Łąka",
            "ul. Malinowa Przystań",
            "ul. Malinowa Oaza",
            "ul. Malinowa Zatoka",
            "ul. Jagodowa Polana",
            "ul. Jagodowa Dolina",
            "ul. Jagodowa Łąka",
            "ul. Jagodowa Przystań",
            "ul. Jagodowa Oaza",
            "ul. Jagodowa Zatoka",
            "ul. Wiśniowa Polana",
            "ul. Wiśniowa Dolina",
            "ul. Wiśniowa Łąka",
            "ul. Wiśniowa Przystań",
            "ul. Wiśniowa Oaza",
            "ul. Wiśniowa Zatoka",
            "ul. Jabłoniowa Polana",
            "ul. Jabłoniowa Dolina",
            "ul. Jabłoniowa Łąka",
            "ul. Jabłoniowa Przystań",
            "ul. Jabłoniowa Oaza",
            "ul. Jabłoniowa Zatoka",
            "ul. Lawendowa Polana",
            "ul. Lawendowa Dolina",
            "ul. Lawendowa Łąka",
            "ul. Lawendowa Przystań",
            "ul. Lawendowa Oaza",
            "ul. Lawendowa Zatoka",
            "ul. Wrzosowa Polana",
            "ul. Wrzosowa Dolina",
            "ul. Wrzosowa Łąka",
            "ul. Wrzosowa Przystań",
            "ul. Wrzosowa Oaza",
            "ul. Wrzosowa Zatoka",
            "ul. Jarzębinowa Polana",
            "ul. Jarzębinowa Dolina",
            "ul. Jarzębinowa Łąka",
            "ul. Jarzębinowa Przystań",
            "ul. Jarzębinowa Oaza",
            "ul. Jarzębinowa Zatoka",
            "ul. Leśny Zakątek",
            "ul. Leśny Stok",
            "ul. Leśny Gaj",
            "ul. Leśny Brzeg",
            "ul. Leśny Most",
            "ul. Leśny Szlak",
            "ul. Leśny Ogród",
            "ul. Leśny Zaułek",
            "ul. Słoneczny Zakątek",
            "ul. Słoneczny Stok",
            "ul. Słoneczny Gaj",
            "ul. Słoneczny Brzeg",
            "ul. Słoneczny Most",
            "ul. Słoneczny Szlak",
            "ul. Słoneczny Ogród",
            "ul. Słoneczny Zaułek",
            "ul. Zielony Zakątek",
            "ul. Zielony Stok",
            "ul. Zielony Gaj",
            "ul. Zielony Brzeg",
            "ul. Zielony Most",
            "ul. Zielony Szlak",
            "ul. Zielony Ogród",
            "ul. Zielony Zaułek",
            "ul. Cichy Zakątek",
            "ul. Cichy Stok",
            "ul. Cichy Gaj",
            "ul. Cichy Brzeg",
            "ul. Cichy Most",
            "ul. Cichy Szlak",
            "ul. Cichy Ogród",
            "ul. Cichy Zaułek",
            "ul. Spokojny Zakątek",
            "ul. Spokojny Stok",
            "ul. Spokojny Gaj",
            "ul. Spokojny Brzeg",
            "ul. Spokojny Most",
            "ul. Spokojny Szlak",
            "ul. Spokojny Ogród",
            "ul. Spokojny Zaułek",
            "ul. Jasny Zakątek",
            "ul. Jasny Stok",
            "ul. Jasny Gaj",
            "ul. Jasny Brzeg",
            "ul. Jasny Most",
            "ul. Jasny Szlak",
            "ul. Jasny Ogród",
            "ul. Jasny Zaułek",
            "ul. Pogodny Zakątek",
            "ul. Pogodny Stok",
            "ul. Pogodny Gaj",
            "ul. Pogodny Brzeg",
            "ul. Pogodny Most",
            "ul. Pogodny Szlak",
            "ul. Pogodny Ogród",
            "ul. Pogodny Zaułek",
            "ul. Wiosenny Zakątek",
            "ul. Wiosenny Stok",
            "ul. Wiosenny Gaj",
            "ul. Wiosenny Brzeg",
            "ul. Wiosenny Most",
            "ul. Wiosenny Szlak",
            "ul. Wiosenny Ogród",
            "ul. Wiosenny Zaułek",
            "ul. Kwiatowy Zakątek",
            "ul. Kwiatowy Stok",
            "ul. Kwiatowy Gaj",
            "ul. Kwiatowy Brzeg",
            "ul. Kwiatowy Most",
            "ul. Kwiatowy Szlak",
            "ul. Kwiatowy Ogród",
            "ul. Kwiatowy Zaułek",
            "ul. Lipowy Zakątek",
            "ul. Lipowy Stok",
            "ul. Lipowy Gaj",
            "ul. Lipowy Brzeg",
            "ul. Lipowy Most",
            "ul. Lipowy Szlak",
            "ul. Lipowy Ogród",
            "ul. Lipowy Zaułek",
            "ul. Brzozowy Zakątek",
            "ul. Brzozowy Stok",
            "ul. Brzozowy Gaj",
            "ul. Brzozowy Brzeg",
            "ul. Brzozowy Most",
            "ul. Brzozowy Szlak",
            "ul. Brzozowy Ogród",
            "ul. Brzozowy Zaułek",
            "ul. Dębowy Zakątek",
            "ul. Dębowy Stok",
            "ul. Dębowy Gaj",
            "ul. Dębowy Brzeg",
            "ul. Dębowy Most",
            "ul. Dębowy Szlak",
            "ul. Dębowy Ogród",
            "ul. Dębowy Zaułek",
            "ul. Klonowy Zakątek",
            "ul. Klonowy Stok",
            "ul. Klonowy Gaj",
            "ul. Klonowy Brzeg",
            "ul. Klonowy Most",
            "ul. Klonowy Szlak",
            "ul. Klonowy Ogród",
            "ul. Klonowy Zaułek",
            "ul. Sosnowy Zakątek",
            "ul. Sosnowy Stok",
            "ul. Sosnowy Gaj",
            "ul. Sosnowy Brzeg",
            "ul. Sosnowy Most",
            "ul. Sosnowy Szlak",
            "ul. Sosnowy Ogród",
            "ul. Sosnowy Zaułek",
            "ul. Kasztanowy Zakątek",
            "ul. Kasztanowy Stok",
            "ul. Kasztanowy Gaj",
            "ul. Kasztanowy Brzeg",
            "ul. Kasztanowy Most",
            "ul. Kasztanowy Szlak",
            "ul. Kasztanowy Ogród",
            "ul. Kasztanowy Zaułek",
            "ul. Akacjowy Zakątek",
            "ul. Akacjowy Stok",
            "ul. Akacjowy Gaj",
            "ul. Akacjowy Brzeg",
            "ul. Akacjowy Most",
            "ul. Akacjowy Szlak",
            "ul. Akacjowy Ogród",
            "ul. Akacjowy Zaułek",
            "ul. Bukowy Zakątek",
            "ul. Bukowy Stok",
            "ul. Bukowy Gaj",
            "ul. Bukowy Brzeg",
            "ul. Bukowy Most",
            "ul. Bukowy Szlak",
            "ul. Bukowy Ogród",
            "ul. Bukowy Zaułek",
            "ul. Świerkowy Zakątek",
            "ul. Świerkowy Stok",
            "ul. Świerkowy Gaj",
            "ul. Świerkowy Brzeg",
            "ul. Świerkowy Most",
            "ul. Świerkowy Szlak",
            "ul. Świerkowy Ogród",
            "ul. Świerkowy Zaułek",
            "ul. Jodłowy Zakątek",
            "ul. Jodłowy Stok",
            "ul. Jodłowy Gaj",
            "ul. Jodłowy Brzeg",
            "ul. Jodłowy Most",
            "ul. Jodłowy Szlak",
            "ul. Jodłowy Ogród",
            "ul. Jodłowy Zaułek",
            "ul. Parkowy Zakątek",
            "ul. Parkowy Stok",
            "ul. Parkowy Gaj",
            "ul. Parkowy Brzeg",
            "ul. Parkowy Most",
            "ul. Parkowy Szlak",
            "ul. Parkowy Ogród",
            "ul. Parkowy Zaułek",
            "ul. Ogrodowy Zakątek",
            "ul. Ogrodowy Stok",
            "ul. Ogrodowy Gaj",
            "ul. Ogrodowy Brzeg",
            "ul. Ogrodowy Most",
            "ul. Ogrodowy Szlak",
            "ul. Ogrodowy Ogród",
            "ul. Ogrodowy Zaułek",
            "ul. Rzeczny Zakątek",
            "ul. Rzeczny Stok",
            "ul. Rzeczny Gaj",
            "ul. Rzeczny Brzeg",
            "ul. Rzeczny Most",
            "ul. Rzeczny Szlak",
            "ul. Rzeczny Ogród",
            "ul. Rzeczny Zaułek",
            "ul. Widokowy Zakątek",
            "ul. Widokowy Stok",
            "ul. Widokowy Gaj",
            "ul. Widokowy Brzeg",
            "ul. Widokowy Most",
            "ul. Widokowy Szlak",
            "ul. Widokowy Ogród",
            "ul. Widokowy Zaułek",
            "ul. Wrzosowy Zakątek",
            "ul. Wrzosowy Stok",
            "ul. Wrzosowy Gaj",
            "ul. Wrzosowy Brzeg",
            "ul. Wrzosowy Most",
            "ul. Wrzosowy Szlak",
            "ul. Wrzosowy Ogród",
            "ul. Wrzosowy Zaułek",
            "ul. Kamienny Zakątek",
            "ul. Kamienny Stok",
            "ul. Kamienny Gaj",
            "ul. Kamienny Brzeg",
            "ul. Kamienny Most",
            "ul. Kamienny Szlak",
            "ul. Kamienny Ogród",
            "ul. Kamienny Zaułek",
            "ul. Górski Zakątek",
            "ul. Górski Stok",
            "ul. Górski Gaj",
            "ul. Górski Brzeg",
            "ul. Górski Most",
            "ul. Górski Szlak",
            "ul. Górski Ogród",
            "ul. Górski Zaułek",
            "ul. Polny Zakątek",
            "ul. Polny Stok",
            "ul. Polny Gaj",
            "ul. Polny Brzeg",
            "ul. Polny Most",
            "ul. Polny Szlak",
            "ul. Polny Ogród",
            "ul. Polny Zaułek",
            "ul. Nadmorski Zakątek",
            "ul. Nadmorski Stok",
            "ul. Nadmorski Gaj",
            "ul. Nadmorski Brzeg",
            "ul. Nadmorski Most",
            "ul. Nadmorski Szlak",
            "ul. Nadmorski Ogród",
            "ul. Nadmorski Zaułek",
            "ul. Leśne Wzgórze",
            "ul. Leśne Zacisze",
            "ul. Leśne Pole",
            "ul. Leśne Uroczysko",
            "ul. Leśne Osiedle",
            "ul. Leśne Przedmieście",
            "ul. Słoneczne Wzgórze",
            "ul. Słoneczne Zacisze",
            "ul. Słoneczne Pole",
            "ul. Słoneczne Uroczysko",
            "ul. Słoneczne Osiedle",
            "ul. Słoneczne Przedmieście",
            "ul. Zielone Wzgórze",
            "ul. Zielone Zacisze",
            "ul. Zielone Pole",
            "ul. Zielone Uroczysko",
            "ul. Zielone Osiedle",
            "ul. Zielone Przedmieście",
            "ul. Ciche Wzgórze",
            "ul. Ciche Zacisze",
            "ul. Ciche Pole",
            "ul. Ciche Uroczysko",
            "ul. Ciche Osiedle",
            "ul. Ciche Przedmieście",
            "ul. Spokojne Wzgórze",
            "ul. Spokojne Zacisze",
            "ul. Spokojne Pole",
            "ul. Spokojne Uroczysko",
            "ul. Spokojne Osiedle",
            "ul. Spokojne Przedmieście",
            "ul. Jasne Wzgórze",
            "ul. Jasne Zacisze",
            "ul. Jasne Pole",
            "ul. Jasne Uroczysko",
            "ul. Jasne Osiedle",
            "ul. Jasne Przedmieście",
            "ul. Pogodne Wzgórze",
            "ul. Pogodne Zacisze",
            "ul. Pogodne Pole",
            "ul. Pogodne Uroczysko",
            "ul. Pogodne Osiedle",
            "ul. Pogodne Przedmieście",
            "ul. Wiosenne Wzgórze",
            "ul. Wiosenne Zacisze",
            "ul. Wiosenne Pole",
            "ul. Wiosenne Uroczysko",
            "ul. Wiosenne Osiedle",
            "ul. Wiosenne Przedmieście",
            "ul. Kwiatowe Wzgórze",
            "ul. Kwiatowe Zacisze",
            "ul. Kwiatowe Pole",
            "ul. Kwiatowe Uroczysko",
            "ul. Kwiatowe Osiedle",
            "ul. Kwiatowe Przedmieście",
            "ul. Lipowe Wzgórze",
            "ul. Lipowe Zacisze",
            "ul. Lipowe Pole",
            "ul. Lipowe Uroczysko",
            "ul. Lipowe Osiedle",
            "ul. Lipowe Przedmieście",
            "ul. Brzozowe Wzgórze",
            "ul. Brzozowe Zacisze",
            "ul. Brzozowe Pole",
            "ul. Brzozowe Uroczysko",
            "ul. Brzozowe Osiedle",
            "ul. Brzozowe Przedmieście",
            "ul. Dębowe Wzgórze",
            "ul. Dębowe Zacisze",
            "ul. Dębowe Pole",
            "ul. Dębowe Uroczysko",
            "ul. Dębowe Osiedle",
            "ul. Dębowe Przedmieście",
            "ul. Klonowe Wzgórze",
            "ul. Klonowe Zacisze",
            "ul. Klonowe Pole",
            "ul. Klonowe Uroczysko",
            "ul. Klonowe Osiedle",
            "ul. Klonowe Przedmieście",
            "ul. Sosnowe Wzgórze",
            "ul. Sosnowe Zacisze",
            "ul. Sosnowe Pole",
            "ul. Sosnowe Uroczysko",
            "ul. Sosnowe Osiedle",
            "ul. Sosnowe Przedmieście",
            "ul. Kasztanowe Wzgórze",
            "ul. Kasztanowe Zacisze",
            "ul. Kasztanowe Pole",
            "ul. Kasztanowe Uroczysko",
            "ul. Kasztanowe Osiedle",
            "ul. Kasztanowe Przedmieście",
            "ul. Akacjowe Wzgórze",
            "ul. Akacjowe Zacisze",
            "ul. Akacjowe Pole",
            "ul. Akacjowe Uroczysko",
            "ul. Akacjowe Osiedle",
            "ul. Akacjowe Przedmieście",
            "ul. Bukowe Wzgórze",
            "ul. Bukowe Zacisze",
            "ul. Bukowe Pole",
            "ul. Bukowe Uroczysko",
            "ul. Bukowe Osiedle",
            "ul. Bukowe Przedmieście",
            "ul. Świerkowe Wzgórze",
            "ul. Świerkowe Zacisze",
            "ul. Świerkowe Pole",
            "ul. Świerkowe Uroczysko",
            "ul. Świerkowe Osiedle",
            "ul. Świerkowe Przedmieście",
            "ul. Jodłowe Wzgórze",
            "ul. Jodłowe Zacisze",
            "ul. Jodłowe Pole",
            "ul. Jodłowe Uroczysko",
            "ul. Jodłowe Osiedle",
            "ul. Jodłowe Przedmieście",
            "ul. Parkowe Wzgórze",
            "ul. Parkowe Zacisze",
            "ul. Parkowe Pole",
            "ul. Parkowe Uroczysko",
            "ul. Parkowe Osiedle",
            "ul. Parkowe Przedmieście",
            "ul. Ogrodowe Wzgórze",
            "ul. Ogrodowe Zacisze",
            "ul. Ogrodowe Pole",
            "ul. Ogrodowe Uroczysko",
            "ul. Ogrodowe Osiedle",
            "ul. Ogrodowe Przedmieście",
            "ul. Rzeczne Wzgórze",
            "ul. Rzeczne Zacisze",
            "ul. Rzeczne Pole",
            "ul. Rzeczne Uroczysko",
            "ul. Rzeczne Osiedle",
            "ul. Rzeczne Przedmieście",
            "ul. Jeziorne Wzgórze",
            "ul. Jeziorne Zacisze",
            "ul. Jeziorne Pole",
            "ul. Jeziorne Uroczysko",
            "ul. Jeziorne Osiedle",
            "ul. Jeziorne Przedmieście",
            "ul. Widokowe Wzgórze",
            "ul. Widokowe Zacisze",
            "ul. Widokowe Pole",
            "ul. Widokowe Uroczysko",
            "ul. Widokowe Osiedle",
            "ul. Widokowe Przedmieście",
            "ul. Wrzosowe Wzgórze",
            "ul. Wrzosowe Zacisze",
            "ul. Wrzosowe Pole",
            "ul. Wrzosowe Uroczysko",
            "ul. Wrzosowe Osiedle",
            "ul. Wrzosowe Przedmieście",
            "ul. Górskie Wzgórze",
            "ul. Górskie Zacisze",
            "ul. Górskie Pole",
            "ul. Górskie Uroczysko",
            "ul. Górskie Osiedle",
            "ul. Górskie Przedmieście",
            "ul. Polne Wzgórze",
            "ul. Polne Zacisze",
            "ul. Polne Pole",
            "ul. Polne Uroczysko",
            "ul. Polne Osiedle",
            "ul. Polne Przedmieście",
            "ul. Nadmorskie Wzgórze",
            "ul. Nadmorskie Zacisze",
            "ul. Nadmorskie Pole",
            "ul. Nadmorskie Uroczysko",
            "ul. Nadmorskie Osiedle",
            "ul. Nadmorskie Przedmieście",
        };

        internal static readonly string[] StandardNames =
        {
           
            "ul. Marszałkowska",
            "ul. Nowy Świat",
            "ul. Krakowskie Przedmieście",
            "ul. Świętokrzyska",
            "ul. Chmielna",
            "ul. Mokotowska",
            "ul. Puławska",
            "ul. Wilcza",
            "ul. Hoża",
            "ul. Krucza",
            "ul. Wspólna",
            "ul. Tamka",
            "ul. Długa",
            "ul. Miodowa",
            "ul. Senatorska",
            "ul. Freta",
            "ul. Floriańska",
            "ul. Grodzka",
            "ul. Szewska",
            "ul. Starowiślna",
            "ul. Dietla",
            "ul. Karmelicka",
            "ul. Zwierzyniecka",
            "ul. Szeroka",
            "ul. Świdnicka",
            "ul. Oławska",
            "ul. Ruska",
            "ul. Piotrkowska",
            "ul. Półwiejska",
            "ul. Długa",
            "ul. Bohaterów Monte Cassino",

            // Persönlichkeiten.
            "ul. Adama Mickiewicza",
            "ul. Juliusza Słowackiego",
            "ul. Fryderyka Chopina",
            "ul. Mikołaja Kopernika",
            "ul. Marii Skłodowskiej-Curie",
            "ul. Henryka Sienkiewicza",
            "ul. Tadeusza Kościuszki",
            "ul. Józefa Piłsudskiego",
            "ul. Ignacego Paderewskiego",
            "ul. Jana Matejki",
            "ul. Stanisława Moniuszki",
            "ul. Stefana Żeromskiego",
            "ul. Bolesława Prusa",
            "ul. Cypriana Kamila Norwida",
            "ul. Elizy Orzeszkowej",
            "ul. Władysława Reymonta",
            "ul. Czesława Miłosza",
            "ul. Wisławy Szymborskiej",
            "ul. Jana Kochanowskiego",
            "ul. Mikołaja Reja",
            "ul. Stanisława Wyspiańskiego",
            "ul. Artura Grottgera",
            "ul. Jana Kilińskiego",
            "ul. Romualda Traugutta",
            "ul. Stefana Batorego",
            "ul. Jana III Sobieskiego",
            "ul. Kazimierza Wielkiego",
            "ul. Władysława Jagiełły",
            "ul. Bolesława Chrobrego",
            "ul. Mieszka I",
            "ul. Lecha Wałęsy",

            // Städte, Regionen und Himmelsrichtungen.
            "ul. Warszawska",
            "ul. Krakowska",
            "ul. Gdańska",
            "ul. Poznańska",
            "ul. Wrocławska",
            "ul. Łódzka",
            "ul. Szczecińska",
            "ul. Lubelska",
            "ul. Toruńska",
            "ul. Katowicka",
            "ul. Opolska",
            "ul. Bydgoska",
            "ul. Rzeszowska",
            "ul. Białostocka",
            "ul. Olsztyńska",
            "ul. Kielecka",
            "ul. Zielonogórska",
            "ul. Radomska",
            "ul. Gdyńska",
            "ul. Sopocka",
            "ul. Zakopiańska",
            "ul. Mazowiecka",
            "ul. Śląska",
            "ul. Pomorska",
            "ul. Wielkopolska",
            "ul. Małopolska",
            "ul. Podlaska",
            "ul. Kujawska",
            "ul. Kaszubska",
            "ul. Warmińska",
            "ul. Mazurska",
            "ul. Północna",
            "ul. Południowa",
            "ul. Wschodnia",
            "ul. Zachodnia",

            // Klassische städtische Namen.
            "ul. Główna",
            "ul. Centralna",
            "ul. Dworcowa",
            "ul. Kolejowa",
            "ul. Pocztowa",
            "ul. Szkolna",
            "ul. Kościelna",
            "ul. Ratuszowa",
            "ul. Targowa",
            "ul. Handlowa",
            "ul. Przemysłowa",
            "ul. Fabryczna",
            "ul. Portowa",
            "ul. Mostowa",
            "ul. Nadbrzeżna",
            "ul. Żeglarska",
            "ul. Lotnicza",
            "ul. Robotnicza",
            "ul. Hutnicza",
            "ul. Górnicza",
            "ul. Energetyczna",
            "ul. Techniczna",
            "ul. Uniwersytecka",
            "ul. Akademicka",
            "ul. Teatralna",
            "ul. Muzealna",
            "ul. Wolności",
            "ul. Niepodległości",
            "ul. Solidarności",
            "ul. Konstytucji",
            "ul. Zwycięstwa",
            "ul. Pokoju",
            "ul. Jedności",
            "ul. Republiki",
            "ul. Europejska",

            "ul. Bielska",
            "ul. Częstochowska",
            "ul. Elbląska",
            "ul. Gorzowska",
            "ul. Koszalińska",
            "ul. Legnicka",
            "ul. Płocka",
            "ul. Tarnowska",
            "ul. Wałbrzyska",
            "ul. Zamojska",
            "ul. Suwalska",
            "ul. Siedlecka",
            "ul. Kaliska",
            "ul. Konińska",
            "ul. Leszczyńska",
            "ul. Gnieźnieńska",
            "ul. Inowrocławska",
            "ul. Grudziądzka",
            "ul. Włocławska",
            "ul. Przemyska",
            "ul. Krośnieńska",
            "ul. Nowosądecka",
            "ul. Jeleniogórska",
            "ul. Skierniewicka",
            "ul. Ostrołęcka",
            "ul. Łomżyńska",
            "ul. Chełmska",
            "ul. Zabrzańska",
            "ul. Gliwicka",
            "ul. Bytomska",
            "ul. Chorzowska",
            "ul. Sosnowiecka",
            "ul. Rybnicka",
            "ul. Tyska",
            "ul. Pilska",
            "ul. Słupska",
            "ul. Kołobrzeska",
            "ul. Raciborska",
            "ul. Opoczyńska",
            "ul. Sanocka",
            "ul. Jarosławska",
            "ul. Łowicka",
            "ul. Kutnowska",
            "ul. Pułtuska",
            "ul. Ciechanowska",
            "ul. Giżycka",
            "ul. Ełcka",
            "ul. Mrągowska",
            "ul. Malborska",
            "ul. Tczewska",
            "ul. Starogardzka",
            "ul. Wejherowska",
            "ul. Pucka",
            "ul. Lęborska",
            "ul. Chojnicka",
            "ul. Kwidzyńska",
            "ul. Ostródzka",
            "ul. Iławska",
            "ul. Brodnicka",
            "ul. Świecka",
            "ul. Nakielska",
            "ul. Żnińska",
            "ul. Rawicka",
            "ul. Gostyńska",
            "ul. Kościańska",
            "ul. Wolsztyńska",
            "ul. Nowotomyska",
            "ul. Międzychodzka",
            "ul. Szamotulska",
            "ul. Wrzesińska",
            "ul. Średzka",
            "ul. Obornicka",
            "ul. Trzebnicka",
            "ul. Oleśnicka",
            "ul. Strzelińska",
            "ul. Nyska",
            "ul. Brzeska",
            "ul. Kluczborska",
            "ul. Lubliniecka",
            "ul. Cieszyńska",
            "ul. Żywiecka",
            "ul. Oświęcimska",
            "ul. Wadowicka",
            "ul. Myślenicka",
            "ul. Bocheńska",
            "ul. Wielicka",
            "ul. Nowotarska",
            "ul. Gorlicka",
            "ul. Jasielska",
            "ul. Dębicka",
            "ul. Mielecka",
            "ul. Tarnobrzeska",
            "ul. Stalowowolska",
            "ul. Kraśnicka",
            "ul. Zamojska",
            "ul. Hrubieszowska",
            "ul. Bialska",
            "ul. Łukowska",
            "ul. Radzyńska",
            "ul. Parczewska",
            "ul. Augustowska",
            "ul. Sokólska",
        };

        internal static readonly string[] AvenueNames =
        {
            "al. Jerozolimskie",
            "al. Jana Pawła II",
            "al. Niepodległości",
            "al. Solidarności",
            "al. Armii Krajowej",
            "al. Wojska Polskiego",
            "al. Zwycięstwa",
            "al. Grunwaldzka",
            "al. Krakowska",
            "al. Piastów",
            "al. Mickiewicza",
            "al. Słowackiego",
            "al. Kościuszki",
            "al. Piłsudskiego",
            "al. Rzeczypospolitej",
            "al. Komisji Edukacji Narodowej",
            "al. Prymasa Tysiąclecia",
            "al. Stanów Zjednoczonych",
            "al. Waszyngtona",
            "al. Wilanowska",
            "al. Władysława Reymonta",
            "al. Powstańców Warszawy",
            "al. Powstańców Śląskich",
            "al. Hallera",
            "al. Jana III Sobieskiego",
            "al. Tysiąclecia",
            "al. Pokoju",
            "al. Wolności",
            "al. Marszałka Józefa Piłsudskiego",
            "al. Legionów",
            "al. Monte Cassino",
            "al. Wielkopolska",
            "al. Pomorska",
            "al. Śląska",
            "al. Mazowiecka",
            "al. Nadwiślańska",
            "al. Nadmorska",
            "al. Parkowa",
            "al. Lipowa",
            "al. Kasztanowa",
            "al. Dębowa",
            "al. Brzozowa",
            "al. Róż",
            "al. Kwiatowa",
            "al. Spacerowa",
            "al. Słoneczna",
            "al. Młodzieży",
            "al. Sportowa",
            "al. Uniwersytecka",
            "al. Europejska"
        };

        internal static readonly string[] HighwayRouteNames =
        {
            // Polnische Autobahnen.
            "A1",
            "A2",
            "A4",
            "A6",
            "A8",
            "A18",

            // Polnische Schnellstraßen.
            "S1",
            "S2",
            "S3",
            "S5",
            "S6",
            "S7",
            "S8",
            "S10",
            "S11",
            "S12",
            "S14",
            "S16",
            "S17",
            "S19",
            "S22",
            "S50",
            "S51",
            "S52",
            "S61",
            "S74",
            "S86"
        };
    }
}
