// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

namespace RoadNameGenerator.Naming
{
    internal static class SpanishRoadNames
    {
        internal static readonly string[] DirtNames =
        {
            "Camino del Bosque",
            "Camino de los Pinos",
            "Camino de las Encinas",
            "Camino de los Olivos",
            "Camino de los Viñedos",
            "Camino del Molino",
            "Camino de la Fuente",
            "Camino del Arroyo",
            "Camino del Valle",
            "Camino de la Sierra",
            "Camino de la Dehesa",
            "Camino de los Prados",
            "Camino de las Huertas",
            "Camino de la Ermita",
            "Camino del Cortijo",
            "Camino de la Vega",
            "Camino de los Almendros",
            "Camino de los Naranjos",
            "Camino de los Cipreses",
            "Camino de las Acacias",
            "Senda del Monte",
            "Senda de la Laguna",
            "Senda del Río",
            "Senda del Barranco",
            "Senda de la Cañada",
            "Vereda Real",
            "Vereda del Pastor",
            "Vereda de la Finca",
            "Vereda de la Colina",
            "Vereda de los Robles",
            "Carril de la Estación",
            "Carril del Olivar",
            "Carril del Pinar",
            "Carril de la Granja",
            "Carril de la Cantera",
            "Pista Forestal Norte",
            "Pista Forestal Sur",
            "Camino Viejo",
            "Camino Nuevo",
            "Camino Rural del Este",
            "Camino Rural del Oeste",
            "Camino de la Frontera",
            "Camino de la Atalaya",
            "Camino del Mirador",
            "Camino de las Flores",
            "Camino de la Luna",
            "Camino del Sol",
            "Camino de las Estrellas",
            "Camino de los Castaños",
            "Camino de los Eucaliptos",
            "Camino de los Chopos",
            "Camino de los Nogales",
            "Camino de las Higueras",
            "Camino de los Laureles",
            "Camino del Romero",
            "Camino del Tomillo",
            "Camino de la Jara",
            "Camino de la Retama",
            "Camino de la Acequia",
            "Camino del Pozo",
            "Camino del Manantial",
            "Camino de la Cascada",
            "Camino del Embalse",
            "Camino de la Garganta",
            "Camino del Páramo",
            "Camino de la Campiña",
            "Camino del Secano",
            "Camino de la Alquería",
            "Camino de la Masía",
            "Camino del Caserío",
            "Camino de la Majada",
            "Camino del Colmenar",
            "Camino de las Eras",
            "Camino del Trigal",
            "Camino del Maizal",
            "Camino del Castañar",
            "Senda de los Pastores",
            "Senda del Águila",
            "Senda del Ciervo",
            "Senda del Lobo",
            "Senda de la Umbría",
            "Senda de la Solana",
            "Vereda de la Cumbre",
            "Vereda del Pinar",
            "Vereda del Arroyo",
            "Vereda de los Molinos",
            "Carril de las Viñas",
            "Carril de la Acequia",
            "Carril del Cortijo",
            "Carril de los Hornos",
            "Pista Forestal de la Sierra",
            "Pista Forestal del Valle",
            "Camino de la Romería",
            "Camino de la Trashumancia",
            "Camino de la Ribera",
            "Camino del Prado Alto",
            "Camino del Prado Bajo",
            "Camino de la Cruz",

            // Additional names for version 1.4.2
            "Camino del Encinar",
            "Camino del Robledal",
            "Camino del Alcornocal",
            "Camino del Sabinar",
            "Camino del Hayedo",
            "Camino del Abedular",
            "Camino del Fresnedal",
            "Camino del Quejigar",
            "Camino del Enebral",
            "Camino del Brezal",
            "Camino de los Madroños",
            "Camino de los Acebos",
            "Camino de los Tejos",
            "Camino de los Alcornoques",
            "Camino de las Sabinas",
            "Camino de los Fresnos",
            "Camino de los Abedules",
            "Camino de los Avellanos",
            "Camino de los Granados",
            "Camino de las Moreras",
            "Senda del Tejar",
            "Senda de la Umbría Alta",
            "Senda de la Umbría Baja",
            "Senda de la Loma",
            "Senda del Collado",
            "Senda del Puerto Viejo",
            "Senda del Peñón",
            "Senda de las Peñas",
            "Senda de la Hoz",
            "Senda del Cañón",
            "Vereda de los Arrieros",
            "Vereda de los Ganaderos",
            "Vereda de los Labradores",
            "Vereda de la Cañada Real",
            "Vereda del Abrevadero",
            "Vereda de la Era Alta",
            "Vereda de la Era Baja",
            "Vereda del Soto",
            "Vereda de la Ribera Alta",
            "Vereda de la Ribera Baja",
            "Carril del Castañar",
            "Carril de los Almendros",
            "Carril de las Palmeras",
            "Carril del Barranco",
            "Carril del Manantial",
            "Carril del Embalse",
            "Carril de la Dehesa",
            "Carril de la Vega",
            "Carril de la Huerta Vieja",
            "Carril de la Finca Nueva",
            "Pista Forestal del Pinar Alto",
            "Pista Forestal del Pinar Bajo",
            "Pista Forestal del Monte Alto",
            "Pista Forestal del Monte Bajo",
            "Pista Forestal de la Cumbre Norte",
            "Pista Forestal de la Cumbre Sur",
            "Pista Forestal del Robledal",
            "Pista Forestal del Encinar",
            "Pista Forestal de la Dehesa",
            "Pista Forestal del Cortafuegos",
            "Camino de la Piedra Blanca",
            "Camino de la Piedra Roja",
            "Camino de la Fuente Nueva",
            "Camino de la Fuente Vieja",
            "Camino del Puente de Madera",
        };

        internal static readonly string[] AlleyNames =
        {
            "Callejón del Gato",
            "Callejón de la Luna",
            "Callejón del Arco",
            "Callejón del Agua",
            "Callejón de las Flores",
            "Callejón de la Iglesia",
            "Callejón del Mercado",
            "Callejón del Molino",
            "Callejón de la Fuente",
            "Callejón del Olivo",
            "Pasaje del Sol",
            "Pasaje de la Estrella",
            "Pasaje de la Paz",
            "Pasaje de la Música",
            "Pasaje de los Artesanos",
            "Pasaje del Teatro",
            "Pasaje del Jardín",
            "Pasaje de la Alameda",
            "Pasaje del Puerto",
            "Pasaje de la Estación",
            "Travesía Mayor",
            "Travesía de San Juan",
            "Travesía de Santa Ana",
            "Travesía del Carmen",
            "Travesía de la Plaza",
            "Rincón del Poeta",
            "Rincón del Pintor",
            "Rincón de la Muralla",
            "Rincón del Castillo",
            "Rincón de la Fuente",
            "Cuesta del Reloj",
            "Cuesta de la Iglesia",
            "Cuesta del Mercado",
            "Cuesta del Mirador",
            "Cuesta de los Almendros",
            "Corralillo del Rey",
            "Corralillo de la Reina",
            "Calleja del Horno",
            "Calleja de la Rosa",
            "Calleja del Laurel",
            "Calleja del Puente",
            "Calleja de los Naranjos",
            "Calleja de la Seda",
            "Calleja del Cobre",
            "Calleja de la Plata",
            "Callejón Oscuro",
            "Callejón Nuevo",
            "Callejón del Centro",
            "Callejón de la Campana",
            "Callejón de los Faroles",
            "Callejón del Relojero",
            "Callejón del Alfarero",
            "Callejón del Herrero",
            "Callejón del Pan",
            "Callejón del Vino",
            "Callejón del Laurel",
            "Callejón del Jazmín",
            "Callejón de la Higuera",
            "Callejón de la Parra",
            "Callejón de los Nardos",
            "Callejón del Silencio",
            "Callejón de la Sombra",
            "Callejón de la Luz",
            "Callejón del Alba",
            "Callejón del Beso",
            "Callejón de la Muralla",
            "Callejón del Castillo",
            "Callejón de la Catedral",
            "Pasaje de la Luna",
            "Pasaje de la Fuente",
            "Pasaje del Comercio",
            "Pasaje de los Olivos",
            "Pasaje de la Biblioteca",
            "Pasaje de la Muralla",
            "Pasaje del Arco",
            "Pasaje de la Catedral",
            "Pasaje de la Concordia",
            "Pasaje de la Amistad",
            "Travesía de San Pedro",
            "Travesía de San Miguel",
            "Travesía de Santiago",
            "Travesía de la Fuente",
            "Travesía del Mercado",
            "Rincón de la Luna",
            "Rincón del Sol",
            "Rincón de los Olivos",
            "Rincón del Laurel",
            "Rincón del Campanario",
            "Cuesta del Castillo",
            "Cuesta de la Muralla",
            "Cuesta del Convento",
            "Cuesta de la Fuente Vieja",
            "Cuesta del Puerto",
            "Calleja de la Luna",
            "Calleja del Agua",
            "Calleja del Jazmín",
            "Calleja de la Campana",
            "Calleja del Mercado",

            // Additional names for version 1.4.2
            "Callejón del Candil",
            "Callejón de la Vela",
            "Callejón del Azahar",
            "Callejón del Naranjo",
            "Callejón del Limonero",
            "Callejón del Ciprés",
            "Callejón del Almendro",
            "Callejón del Castaño",
            "Callejón del Roble",
            "Callejón del Sauce",
            "Callejón de la Herradura",
            "Callejón de la Escalera",
            "Callejón de la Reja",
            "Callejón del Balcón",
            "Callejón del Portal",
            "Callejón del Empedrado",
            "Callejón del Aljibe",
            "Callejón de la Acequia",
            "Callejón del Pozo Viejo",
            "Callejón de la Torre",
            "Pasaje del Azahar",
            "Pasaje de los Naranjos",
            "Pasaje de las Palmeras",
            "Pasaje de los Jazmines",
            "Pasaje de las Rosas",
            "Pasaje de los Gremios",
            "Pasaje de la Imprenta",
            "Pasaje del Cine",
            "Pasaje del Museo",
            "Pasaje del Reloj",
            "Travesía de San Andrés",
            "Travesía de San Mateo",
            "Travesía de San Marcos",
            "Travesía de Santa Lucía",
            "Travesía de Santa Isabel",
            "Travesía de Santa Teresa",
            "Travesía del Rosario",
            "Travesía de la Cruz",
            "Travesía del Puente",
            "Travesía del Río",
            "Rincón del Azahar",
            "Rincón del Naranjo",
            "Rincón del Ciprés",
            "Rincón de la Higuera",
            "Rincón del Almendro",
            "Rincón de la Parra Vieja",
            "Rincón de los Geranios",
            "Rincón de la Cal",
            "Rincón de la Piedra",
            "Rincón del Agua Clara",
            "Cuesta de la Torre",
            "Cuesta del Alcázar",
            "Cuesta de la Alcazaba",
            "Cuesta del Calvario",
            "Cuesta de la Ermita",
            "Cuesta del Molino Viejo",
            "Cuesta de la Atalaya",
            "Cuesta de la Judería",
            "Cuesta del Arrabal",
            "Cuesta de la Alhambra",
            "Calleja del Candil",
            "Calleja del Azahar",
            "Calleja del Olivo Viejo",
            "Calleja del Empedrado",
            "Calleja de la Estrella",
        };

        internal static readonly string[] ResidentialNames =
        {
            "Calle de los Olmos",
            "Calle de los Pinos",
            "Calle de las Encinas",
            "Calle de los Robles",
            "Calle de los Álamos",
            "Calle de los Tilos",
            "Calle de las Acacias",
            "Calle de los Almendros",
            "Calle de los Naranjos",
            "Calle de los Limoneros",
            "Calle de las Rosas",
            "Calle de los Claveles",
            "Calle de los Jazmines",
            "Calle de las Violetas",
            "Calle de los Girasoles",
            "Calle de la Primavera",
            "Calle del Verano",
            "Calle del Otoño",
            "Calle del Invierno",
            "Calle del Amanecer",
            "Calle del Atardecer",
            "Calle de la Luna",
            "Calle del Sol",
            "Calle de las Estrellas",
            "Calle del Arcoíris",
            "Calle de la Paz",
            "Calle de la Amistad",
            "Calle de la Esperanza",
            "Calle de la Libertad",
            "Calle de la Alegría",
            "Calle del Parque",
            "Calle del Jardín",
            "Calle de la Fuente",
            "Calle del Lago",
            "Calle del Río",
            "Calle del Arroyo",
            "Calle del Valle",
            "Calle de la Sierra",
            "Calle del Mirador",
            "Calle de la Colina",
            "Calle de la Escuela",
            "Calle del Colegio",
            "Calle del Deporte",
            "Calle de la Biblioteca",
            "Calle del Centro Cívico",
            "Calle de la Iglesia",
            "Calle de la Ermita",
            "Calle del Molino",
            "Calle del Mercado",
            "Calle de la Estación",
            "Calle de Goya",
            "Calle de Velázquez",
            "Calle de Cervantes",
            "Calle de Lorca",
            "Calle de Machado",
            "Calle de Rosalía de Castro",
            "Calle de Emilia Pardo Bazán",
            "Calle de Clara Campoamor",
            "Calle de María Zambrano",
            "Calle de Concepción Arenal",
            "Calle de Santiago Ramón y Cajal",
            "Calle de Isaac Peral",
            "Calle de Severo Ochoa",
            "Calle de Margarita Salas",
            "Calle de Juan de la Cierva",
            "Calle del Mar",
            "Calle de la Montaña",
            "Calle del Bosque",
            "Calle de la Vega",
            "Calle de la Alameda",
            "Calle de la Arboleda",
            "Calle de la Plazuela",
            "Calle de los Castaños",
            "Calle de los Nogales",
            "Calle de las Palmeras",
            "Calle de los Abetos",
            "Calle de los Cedros",
            "Calle de los Sauces",
            "Calle de los Eucaliptos",
            "Calle de los Laureles",
            "Calle de las Magnolias",
            "Calle de las Azucenas",
            "Calle de las Camelias",
            "Calle de las Dalias",
            "Calle de las Amapolas",
            "Calle de las Petunias",
            "Calle de las Hortensias",
            "Calle de las Orquídeas",
            "Calle de las Mimosas",
            "Calle del Romero",
            "Calle del Tomillo",
            "Calle de la Lavanda",
            "Calle de las Golondrinas",
            "Calle de los Gorriones",
            "Calle de los Jilgueros",
            "Calle de los Ruiseñores",
            "Calle de las Cigüeñas",
            "Calle de las Garzas",
            "Calle de las Águilas",
            "Calle de los Halcones",
            "Calle de las Mariposas",
            "Calle de las Abejas",
            "Calle de la Bahía",
            "Calle de la Costa",
            "Calle de la Ribera",
            "Calle de la Cascada",
            "Calle del Manantial",
            "Calle de la Cumbre",
            "Calle de la Pradera",
            "Calle de la Campiña",
            "Calle del Prado",
            "Calle del Pinar",
            "Calle del Olivar",
            "Calle del Viñedo",
            "Calle de la Armonía",
            "Calle de la Solidaridad",
            "Calle de la Igualdad",
            "Calle del Encuentro",
            "Calle de la Convivencia",
            "Calle de los Sueños",
            "Calle del Recuerdo",
            "Calle de la Ilusión",
            "Calle de Miguel de Unamuno",
            "Calle de Antonio Machado",
            "Calle de Federico García Lorca",
            "Calle de Benito Pérez Galdós",
            "Calle de Camilo José Cela",
            "Calle de Carmen Laforet",
            "Calle de María Moliner",
            "Calle de María de Maeztu",
            "Calle de Victoria Kent",
            "Calle de Ángeles Alvariño",
            "Calle de María Blasco",
            "Calle de Leonardo Torres Quevedo",
            "Calle de Gregorio Marañón",
            "Calle de Blas Cabrera",
            "Calle de Julio Rey Pastor",
            "Calle de Antoni Gaudí",
            "Calle de Joaquín Sorolla",
            "Calle de Pablo Picasso",
            "Calle de Joan Miró",
            "Calle de Salvador Dalí",
            "Calle de Luis Buñuel",
            "Calle de Pau Casals",
            "Calle de Manuel de Falla",
            "Calle de Joaquín Rodrigo",
            "Calle de Gloria Fuertes",
            "Calle de Carmen Martín Gaite",
            "Calle de Ana María Matute",
            "Calle de Rosa Chacel",
            "Calle de Mercè Rodoreda",
            "Calle de Elena Fortún",

            // Additional names for version 1.4.2
            "Calle de los Abedules",
            "Calle de los Fresnos",
            "Calle de las Hayas",
            "Calle de los Alcornoques",
            "Calle de los Acebos",
            "Calle de los Tejos",
            "Calle de los Avellanos",
            "Calle de los Granados",
            "Calle de las Moreras",
            "Calle de los Madroños",
            "Calle de las Gardenias",
            "Calle de las Begonias",
            "Calle de las Caléndulas",
            "Calle de las Madreselvas",
            "Calle de las Adelfas",
            "Calle de las Buganvillas",
            "Calle de las Margaritas",
            "Calle de las Peonías",
            "Calle de las Fresias",
            "Calle de los Jacintos",
            "Calle de los Lirios",
            "Calle de los Nardos",
            "Calle del Azahar",
            "Calle de la Hierbabuena",
            "Calle de la Salvia",
            "Calle de los Mirlos",
            "Calle de los Petirrojos",
            "Calle de los Canarios",
            "Calle de los Verderones",
            "Calle de los Vencejos",
            "Calle de los Estorninos",
            "Calle de los Flamencos",
            "Calle de los Patos",
            "Calle de los Cisnes",
            "Calle de los Búhos",
            "Calle de las Lechuzas",
            "Calle de los Zorros",
            "Calle de los Conejos",
            "Calle de las Ardillas",
            "Calle de los Ciervos",
            "Calle de los Gamos",
            "Calle de los Linces",
            "Calle de los Delfines",
            "Calle de los Caballitos de Mar",
            "Calle de las Libélulas",
            "Calle del Acantilado",
            "Calle del Cabo",
            "Calle del Estuario",
            "Calle del Pinar Alto",
            "Calle del Pinar Bajo",
            "Calle del Prado Verde",
            "Calle del Monte Azul",
            "Calle de la Sierra Blanca",
            "Calle de la Sierra Verde",
            "Calle del Valle Alto",
            "Calle del Valle Bajo",
            "Calle del Arroyo Claro",
            "Calle del Río Verde",
            "Calle de la Laguna Azul",
            "Calle de la Fuente Clara",
            "Calle de la Fuente Nueva",
            "Calle de la Brisa",
            "Calle del Levante",
            "Calle del Poniente",
            "Calle de la Marea",
            "Calle de la Creatividad",
            "Calle de la Imaginación",
            "Calle de la Serenidad",
            "Calle de la Tolerancia",
            "Calle de la Diversidad",
            "Calle de la Cooperación",
            "Calle de la Bienvenida",
            "Calle de la Juventud",
            "Calle de la Infancia",
            "Calle de la Sabiduría",
            "Calle de la Lectura",
            "Calle de la Fotografía",
            "Calle de la Danza",
            "Calle del Cine",
            "Calle de la Poesía",
        };

        internal static readonly string[] StandardNames =
        {
            "Calle Mayor",
            "Calle Real",
            "Calle Nueva",
            "Calle Vieja",
            "Calle Central",
            "Calle del Comercio",
            "Calle del Mercado",
            "Calle de la Estación",
            "Calle del Ayuntamiento",
            "Calle de la Constitución",
            "Calle de la Independencia",
            "Calle de la Concordia",
            "Calle de la Unión",
            "Calle del Progreso",
            "Calle de la Industria",
            "Calle de los Artesanos",
            "Calle de los Herreros",
            "Calle de los Tejedores",
            "Calle de los Carpinteros",
            "Calle de los Panaderos",
            "Calle del Puerto",
            "Calle del Ferrocarril",
            "Calle del Hospital",
            "Calle del Teatro",
            "Calle del Museo",
            "Calle de la Universidad",
            "Calle de la Ciencia",
            "Calle de la Tecnología",
            "Calle de la Innovación",
            "Calle de la Energía",
            "Calle del Medio Ambiente",
            "Calle de Europa",
            "Calle de España",
            "Calle de Andalucía",
            "Calle de Aragón",
            "Calle de Asturias",
            "Calle de Cantabria",
            "Calle de Castilla",
            "Calle de Cataluña",
            "Calle de Extremadura",
            "Calle de Galicia",
            "Calle de La Rioja",
            "Calle de Madrid",
            "Calle de Murcia",
            "Calle de Navarra",
            "Calle de Valencia",
            "Calle del País Vasco",
            "Ronda Norte",
            "Ronda Sur",
            "Ronda Este",
            "Ronda Oeste",
            "Ronda Central",
            "Ronda del Parque",
            "Ronda del Puerto",
            "Ronda de la Estación",
            "Ronda de la Universidad",
            "Ronda de la Industria",
            "Paseo del Río",
            "Paseo del Mar",
            "Paseo de la Estación",
            "Paseo de la Constitución",
            "Paseo de los Tilos",
            "Paseo de los Olmos",
            "Carretera del Norte",
            "Carretera del Sur",
            "Carretera de la Costa",
            "Carretera de la Sierra",
            "Carretera del Valle",
            "Camino Real",
            "Vía Central",
            "Vía de Servicio",
            "Vía del Comercio",
            "Vía de la Estación",
            "Calle de la Aduana",
            "Calle de Correos",
            "Calle de los Bomberos",
            "Calle de la Guardia",
            "Calle de la Justicia",
            "Calle del Juzgado",
            "Calle del Archivo",
            "Calle del Matadero",
            "Calle de la Lonja",
            "Calle del Almacén",
            "Calle de la Fábrica",
            "Calle de los Talleres",
            "Calle de los Ceramistas",
            "Calle de los Alfareros",
            "Calle de los Curtidores",
            "Calle de los Sastres",
            "Calle de los Zapateros",
            "Calle de los Canteros",
            "Calle de los Molineros",
            "Calle de los Pescadores",
            "Calle de los Marineros",
            "Calle de Canarias",
            "Calle de Castilla-La Mancha",
            "Calle de Castilla y León",
            "Calle de las Islas Baleares",
            "Calle de Ceuta",
            "Calle de Melilla",
            "Calle de Toledo",
            "Calle de Córdoba",
            "Calle de Granada",
            "Calle de Bilbao",
            "Calle de Alicante",
            "Calle de Valladolid",
            "Calle de Salamanca",
            "Calle de Burgos",
            "Calle de León",
            "Calle de Cádiz",
            "Calle de Huelva",
            "Calle de Jaén",
            "Calle de Almería",
            "Calle de Santander",
            "Calle de Oviedo",
            "Calle de Pamplona",
            "Calle de Logroño",
            "Calle de Mérida",
            "Calle de Badajoz",
            "Calle de Cáceres",
            "Calle de Vigo",
            "Calle de A Coruña",
            "Calle de Santiago de Compostela",
            "Ronda de la Muralla",
            "Ronda del Castillo",
            "Ronda del Centro",
            "Ronda de los Barrios",
            "Ronda Metropolitana",
            "Ronda Exterior",
            "Ronda Interior",
            "Paseo de la Cultura",
            "Paseo de las Artes",
            "Paseo de la Música",
            "Paseo del Parque",
            "Paseo del Puerto",
            "Paseo de la Universidad",
            "Paseo de la Ciencia",
            "Carretera de la Montaña",
            "Carretera del Río",
            "Carretera del Puerto",
            "Carretera del Aeropuerto",
            "Carretera de la Estación",
            "Carretera de la Frontera",
            "Vía del Parque",
            "Vía de la Universidad",
            "Vía de la Industria",
            "Vía del Ferrocarril",
            "Vía del Puerto",
            "Vía de la Ciencia",
            "Vía de la Tecnología",
            "Vía Metropolitana",
            "Vía Urbana",
            "Vía de Circunvalación",

            // Additional names for version 1.4.2
            "Calle de la Bolsa",
            "Calle de la Banca",
            "Calle de la Cámara de Comercio",
            "Calle del Palacio de Justicia",
            "Calle de la Audiencia",
            "Calle del Parque de Bomberos",
            "Calle de Protección Civil",
            "Calle del Archivo Municipal",
            "Calle del Conservatorio",
            "Calle del Auditorio",
            "Calle del Palacio de Congresos",
            "Calle del Recinto Ferial",
            "Calle del Centro de Salud",
            "Calle del Polígono Industrial",
            "Calle del Centro Logístico",
            "Calle del Mercado Central",
            "Calle de la Lonja Nueva",
            "Calle de la Estación de Autobuses",
            "Calle del Puerto Deportivo",
            "Calle del Astillero",
            "Calle de Ávila",
            "Calle de Segovia",
            "Calle de Soria",
            "Calle de Teruel",
            "Calle de Cuenca",
            "Calle de Guadalajara",
            "Calle de Albacete",
            "Calle de Ciudad Real",
            "Calle de Tarragona",
            "Calle de Girona",
            "Calle de Lleida",
            "Calle de Huesca",
            "Calle de Zamora",
            "Calle de Palencia",
            "Calle de Ourense",
            "Calle de Lugo",
            "Calle de Pontevedra",
            "Calle de Donostia",
            "Calle de Vitoria-Gasteiz",
            "Calle de Santa Cruz de Tenerife",
            "Calle de Miguel Delibes",
            "Calle de Javier Marías",
            "Calle de Almudena Grandes",
            "Calle de Carmen Conde",
            "Calle de María Teresa León",
            "Calle de María Lejárraga",
            "Calle de Maruja Mallo",
            "Calle de Remedios Varo",
            "Calle de Eduardo Chillida",
            "Calle de Juan Gris",
            "Calle de Antonio López",
            "Calle de Luis García Berlanga",
            "Calle de Fernando Fernán Gómez",
            "Calle de Carlos Saura",
            "Calle de Montserrat Caballé",
            "Calle de Alicia de Larrocha",
            "Calle de María Goyri",
            "Calle de Josefina de la Torre",
            "Calle de Ángela Ruiz Robles",
            "Calle de Elena García Armada",
            "Vía del Campus",
            "Vía del Tranvía",
            "Vía del Metro",
            "Vía del Centro Logístico",
            "Ronda del Aeropuerto",
            "Ronda Universitaria",
            "Paseo de la Innovación",
            "Paseo del Conocimiento",
            "Carretera del Parque Tecnológico",
            "Carretera del Polígono Industrial",
        };

        internal static readonly string[] AvenueNames =
        {
            "Avenida de la Constitución",
            "Avenida de Europa",
            "Avenida de España",
            "Avenida de la Libertad",
            "Avenida de la Paz",
            "Avenida del Progreso",
            "Avenida de la Industria",
            "Avenida de la Universidad",
            "Avenida de la Ciencia",
            "Avenida de la Tecnología",
            "Avenida del Mediterráneo",
            "Avenida del Atlántico",
            "Avenida del Cantábrico",
            "Avenida de Andalucía",
            "Avenida de Aragón",
            "Avenida de Asturias",
            "Avenida de Castilla",
            "Avenida de Cataluña",
            "Avenida de Galicia",
            "Avenida de Valencia",
            "Avenida de Madrid",
            "Avenida de Barcelona",
            "Avenida de Sevilla",
            "Avenida de Zaragoza",
            "Avenida de Málaga",
            "Avenida del Puerto",
            "Avenida de la Estación",
            "Avenida del Parque",
            "Avenida del Río",
            "Avenida del Mar",
            "Gran Vía",
            "Gran Vía del Norte",
            "Gran Vía del Sur",
            "Gran Vía del Este",
            "Gran Vía del Oeste",
            "Bulevar de la Cultura",
            "Bulevar de las Artes",
            "Bulevar de la Música",
            "Bulevar de los Jardines",
            "Bulevar del Deporte",
            "Bulevar de la Innovación",
            "Bulevar de la Energía",
            "Bulevar del Comercio",
            "Bulevar del Puerto",
            "Bulevar Central",
            "Paseo de la Castellana",
            "Paseo de la Alameda",
            "Paseo del Prado",
            "Paseo Marítimo",
            "Paseo de la Independencia",
            "Avenida de Canarias",
            "Avenida de Castilla-La Mancha",
            "Avenida de Castilla y León",
            "Avenida de las Islas Baleares",
            "Avenida de Extremadura",
            "Avenida de Navarra",
            "Avenida de Murcia",
            "Avenida de La Rioja",
            "Avenida del País Vasco",
            "Avenida de Cantabria",
            "Avenida de Granada",
            "Avenida de Córdoba",
            "Avenida de Bilbao",
            "Avenida de Alicante",
            "Avenida de Valladolid",
            "Avenida de Salamanca",
            "Avenida de Toledo",
            "Avenida de Burgos",
            "Avenida de León",
            "Avenida de Cádiz",
            "Avenida de Miguel de Cervantes",
            "Avenida de Federico García Lorca",
            "Avenida de Pablo Picasso",
            "Avenida de Clara Campoamor",
            "Avenida de Santiago Ramón y Cajal",
            "Avenida de Severo Ochoa",
            "Avenida de Margarita Salas",
            "Avenida de la Igualdad",
            "Avenida de la Concordia",
            "Avenida de la Solidaridad",
            "Avenida de la Democracia",
            "Avenida de los Derechos Humanos",
            "Avenida del Futuro",
            "Avenida del Conocimiento",
            "Avenida de la Innovación",
            "Avenida del Medio Ambiente",
            "Avenida de la Cultura",
            "Avenida de las Artes",
            "Avenida de la Música",
            "Avenida del Deporte",
            "Avenida de los Jardines",
            "Avenida de la Alameda",
            "Avenida de la Ribera",
            "Avenida de la Costa",
            "Avenida de la Sierra",
            "Avenida del Valle",
            "Avenida del Aeropuerto",
            "Avenida del Ferrocarril",
            "Avenida del Comercio",
            "Avenida Central del Norte",
            "Bulevar de la Constitución",
            "Bulevar de Europa",
            "Bulevar de España",
            "Bulevar de la Libertad",
            "Bulevar de la Paz",
            "Bulevar de la Universidad",
            "Bulevar de la Ciencia",
            "Bulevar del Mediterráneo",
            "Bulevar del Atlántico",
            "Bulevar Metropolitano",

            // Additional names for version 1.4.2
            "Avenida de la Diversidad",
            "Avenida de la Tolerancia",
            "Avenida de la Cooperación",
            "Avenida de la Juventud",
            "Avenida de la Infancia",
            "Avenida de la Sabiduría",
            "Avenida de la Creatividad",
            "Avenida de la Imaginación",
            "Avenida de la Convivencia",
            "Avenida de la Salud",
            "Avenida de la Educación",
            "Avenida de la Investigación",
            "Avenida del Emprendimiento",
            "Avenida de la Sostenibilidad",
            "Avenida de la Movilidad",
            "Avenida de las Marismas",
            "Avenida de las Montañas",
            "Avenida de los Bosques",
            "Avenida de los Lagos",
            "Avenida de los Puentes",
            "Avenida de Palma",
            "Avenida de Las Palmas",
            "Avenida de Santa Cruz de Tenerife",
            "Avenida de Vigo",
            "Avenida de A Coruña",
            "Avenida de Oviedo",
            "Avenida de Santander",
            "Avenida de Pamplona",
            "Avenida de Logroño",
            "Avenida de Mérida",
            "Bulevar de los Olivos",
            "Bulevar de los Naranjos",
            "Bulevar de las Palmeras",
            "Bulevar del Azahar",
            "Bulevar del Jardín Botánico",
            "Bulevar del Parque Tecnológico",
            "Bulevar del Ferrocarril",
            "Bulevar del Aeropuerto",
            "Bulevar del Puerto Deportivo",
            "Bulevar de los Artesanos",
        };

        internal static readonly string[] NamedHighwayNames =
        {
            "Autovía del Norte",
            "Autovía del Nordeste",
            "Autovía del Este",
            "Autovía del Sur",
            "Autovía del Suroeste",
            "Autovía del Noroeste",
            "Autovía del Mediterráneo",
            "Autovía de la Plata",
            "Autovía del Cantábrico",
            "Autovía de Castilla",
            "Autovía del Camino de Santiago",
            "Autovía de la Costa Tropical",
            "Autovía del Olivar",
            "Autovía de Sierra Nevada",
            "Autopista del Mediterráneo",
            "Autopista del Atlántico",
            "Autopista del Norte",
            "Autopista del Sol",
            "Autopista Vasco-Aragonesa",
            "Ronda Litoral",
            "Ronda de Circunvalación",
            "Vía de Cintura",
            "Eje Atlántico",
            "Corredor del Mediterráneo",
            "Autovía de Andalucía",
            "Autovía de Aragón",
            "Autovía de Extremadura",
            "Autovía de Galicia",
            "Autovía de Navarra",
            "Autovía de Valencia",
            "Autovía de Murcia",
            "Autovía de los Viñedos",
            "Autovía de la Sagra",
            "Autovía del Duero",
            "Autovía del Ebro",
            "Autovía del Pirineo",
            "Autovía de la Meseta",
            "Autovía de la Costa del Sol",
            "Autovía de la Costa Blanca",
            "Autovía de la Costa Brava",
            "Autopista del Cantábrico",
            "Autopista del Ebro",
            "Autopista de Navarra",
            "Autopista de la Costa",
            "Autopista Central",
            "Autopista Metropolitana",
            "Ronda Norte Metropolitana",
            "Ronda Sur Metropolitana",
            "Corredor del Ebro",
            "Corredor Atlántico",
            "Eje Mediterráneo",
            "Eje del Duero",
            "Eje Pirenaico",
            "Enlace Metropolitano",

            // Additional names for version 1.4.2
            "Autovía del Júcar",
            "Autovía del Tajo",
            "Autovía del Guadiana",
            "Autovía del Guadalquivir",
            "Autovía del Miño",
            "Autovía del Segura",
            "Autovía de la Mancha",
            "Autovía de la Ribera",
            "Autopista de la Meseta",
            "Autopista del Levante",
            "Autopista de Poniente",
            "Corredor del Cantábrico",
            "Corredor de la Meseta",
            "Eje del Guadalquivir",
            "Eje del Tajo",
            "Ronda Metropolitana Este",
            "Ronda Metropolitana Oeste",
        };
    }
}
