// Road Name Generator
// Copyright (C) 2026 franky0078
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3
// or, at your option, any later version.

using System;
using System.Collections.Generic;

namespace RoadNameGenerator.Naming
{

    internal static class SwissRoadNames
    {
        internal static readonly string[] DirtNames =
            Merge(
                new[]
                {
                    "Alpweg",
                    "Maiensässweg",
                    "Suonenweg",
                    "Bisse du Rhône",
                    "Chemin de l'Alpage",
                    "Chemin des Vignes",
                    "Chemin du Lavaux",
                    "Chemin du Jura",
                    "Chemin du Léman",
                    "Sentier du Rhône",
                    "Sentier des Alpes",
                    "Sentier du Vignoble",
                    "Strada degli Alpi",
                    "Sentiero del Monte",
                    "Sentiero del Lago",
                    "Strada dei Grotti",
                    "Via d'Alp",
                    "Via da God",
                    "Via da la Val",
                    "Via dal Lai",
                    "Via da l'En",
                    "Via da Crasta",
                    "Via Prasüras",
                    "Via Salastrains",
                    "Via Suvretta"
                },
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse",
                    "Dent Blanche",
                    "Dents du Midi",
                    "Mont Fort",
                    "Grand Combin",
                    "Simplon",
                    "Grand-Saint-Bernard",
                    "Jaman",
                    "Moléson",
                    "Chasseral",
                    "Creux du Van",
                    "Rochers-de-Naye",
                    "Diablerets",
                    "Verbier",
                    "Crans",
                    "Montana",
                    "Zinal",
                    "Grimentz",
                    "Saas",
                    "Zermatt",
                    "Riviera",
                    "La Côte",
                    "Trois-Lacs",
                    "Helvétie",
                    "Confédération",
                    "Alpes",
                    "Mont-Blanc",
                    "Rütli",
                    "Gotthard",
                    "Saint-Maurice",
                    "Saint-Cergue",
                    "Sainte-Croix",
                    "La Chaux-de-Fonds",
                    "Le Locle",
                    "Les Paccots",
                    "Les Diablerets",
                    "Les Avants",
                    "Charmey"
                    },
                    "Chemin de ",
                    "Sentier de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico",
                    "Claro",
                    "Arbedo",
                    "Giubiasco",
                    "Camorino",
                    "Sant'Antonino",
                    "Cadenazzo",
                    "Gambarogno",
                    "Tenero",
                    "Brissago",
                    "Ronco",
                    "Losone",
                    "Intragna",
                    "Centovalli",
                    "Onsernone",
                    "Vallemaggia",
                    "Maggia",
                    "Verzasca",
                    "Leventina",
                    "Blenio",
                    "Malcantone",
                    "Vedeggio",
                    "Cassarate",
                    "Ceresio",
                    "Verbano",
                    "Ticino",
                    "San Gottardo",
                    "Monte Brè",
                    "Monte San Salvatore",
                    "Monte Generoso",
                    "Monte Tamaro",
                    "Pizzo di Claro",
                    "Lema",
                    "Lucomagno",
                    "Nufenen",
                    "Alpe",
                    "Grotto",
                    "Riviera",
                    "Confederazione",
                    "Elvezia"
                    },
                    "Sentiero ",
                    "Strada "
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Sils",
                    "Pontresina",
                    "Celerina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Sent",
                    "Guarda",
                    "Ardez",
                    "Zernez",
                    "Lavin",
                    "Susch",
                    "Ftan",
                    "Tarasp",
                    "Müstair",
                    "Sta. Maria",
                    "Fuldera",
                    "Tschierv",
                    "Valchava",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Trun",
                    "Flims",
                    "Laax",
                    "Falera",
                    "Vals",
                    "Vrin",
                    "Lumnezia",
                    "Safien",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Filisur",
                    "Savognin",
                    "Bivio",
                    "Thusis",
                    "Domleschg",
                    "Heinzenberg",
                    "Calanda",
                    "Ruinaulta",
                    "Inn",
                    "En",
                    "Rom",
                    "Rein",
                    "Lai",
                    "God",
                    "Alp",
                    "Val",
                    "Crasta",
                    "Prasüras",
                    "Salastrains",
                    "Suvretta",
                    "Somplaz",
                    "Serlas",
                    "Tinus",
                    "Chavallera",
                    "Brattas",
                    "Chasellas"
                    },
                    "Via da ",
                    "Via "
                )
            );

        internal static readonly string[] AlleyNames =
            Merge(
                new[]
                {
                    "Kramgasse",
                    "Gerechtigkeitsgasse",
                    "Junkerngasse",
                    "Spitalgasse",
                    "Münstergasse",
                    "Rathausgasse",
                    "Marktgasse",
                    "Rheingasse",
                    "Gerbergasse",
                    "Niederdorfstrasse",
                    "Trittligasse",
                    "Kuttelgasse",
                    "Froschaugasse",
                    "Mühlegasse",
                    "Schifflände",
                    "Rue de la Corraterie",
                    "Rue du Marché",
                    "Rue des Alpes",
                    "Rue de Carouge",
                    "Rue de la Servette",
                    "Rue du Bourg",
                    "Rue du Petit-Chêne",
                    "Rue du Grand-Chêne",
                    "Rue Centrale",
                    "Rue du Simplon",
                    "Rue de Bourg",
                    "Via Nassa",
                    "Via Canova",
                    "Via Cattedrale",
                    "Via Pessina",
                    "Via Motta",
                    "Contrada di Verla",
                    "Via Maistra",
                    "Via Tinus",
                    "Via Serlas",
                    "Via Somplaz",
                    "Via Chavallera",
                    "Via Brattas"
                },
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse"
                    },
                    "Rue de ",
                    "Passage de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico"
                    },
                    "Via ",
                    "Vicolo "
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Sils",
                    "Pontresina",
                    "Celerina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Sent",
                    "Guarda",
                    "Ardez",
                    "Zernez",
                    "Lavin",
                    "Susch",
                    "Ftan",
                    "Tarasp",
                    "Müstair",
                    "Sta. Maria",
                    "Fuldera",
                    "Tschierv",
                    "Valchava",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Trun",
                    "Flims",
                    "Laax",
                    "Falera",
                    "Vals",
                    "Vrin",
                    "Lumnezia",
                    "Safien",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Filisur",
                    "Savognin"
                    },
                    "Via ",
                    "Giassa "
                ),
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse"
                    },
                    "Ruelle de ",
                    "Impasse de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico"
                    },
                    "Corte ",
                    "Salita "
                ),
                BuildGermanSwissNames(
                    new[]
                    {
                    "Gotthard",
                    "Rütli",
                    "Säntis",
                    "Pilatus",
                    "Rigi",
                    "Mythen",
                    "Titlis",
                    "Eiger",
                    "Mönch",
                    "Jungfrau",
                    "Matterhorn",
                    "Dufour",
                    "Monte Rosa",
                    "Pizol",
                    "Tödi",
                    "Glärnisch",
                    "Stockhorn",
                    "Niesen",
                    "Gantrisch",
                    "Weissenstein",
                    "Napf",
                    "Bachtel",
                    "Uetliberg",
                    "Pfannenstiel",
                    "Lägern",
                    "Wildstrubel",
                    "Gemmi",
                    "Klausen",
                    "Furka",
                    "Grimsel",
                    "Susten",
                    "Oberalp",
                    "Julier",
                    "Bernina",
                    "Albula",
                    "Flüela",
                    "San Bernardino",
                    "Lukmanier",
                    "Aare",
                    "Limmat",
                    "Reuss",
                    "Rhein",
                    "Thur",
                    "Linth",
                    "Sihl",
                    "Emme",
                    "Töss",
                    "Engadin",
                    "Prättigau",
                    "Toggenburg",
                    "Emmental",
                    "Entlebuch",
                    "Seeland",
                    "Rheintal",
                    "Limmattal",
                    "Aaretal",
                    "Reusstal",
                    "Appenzell",
                    "Uri",
                    "Schwyz",
                    "Glarus",
                    "Graubünden",
                    "Wallis"
                    },
                    "gasse"
                )
            );

        internal static readonly string[] ResidentialNames =
            Merge(
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse",
                    "Dent Blanche",
                    "Dents du Midi",
                    "Mont Fort",
                    "Grand Combin",
                    "Simplon",
                    "Grand-Saint-Bernard",
                    "Jaman",
                    "Moléson",
                    "Chasseral",
                    "Creux du Van",
                    "Rochers-de-Naye",
                    "Diablerets",
                    "Verbier",
                    "Crans",
                    "Montana",
                    "Zinal",
                    "Grimentz",
                    "Saas",
                    "Zermatt",
                    "Riviera",
                    "La Côte",
                    "Trois-Lacs",
                    "Helvétie",
                    "Confédération",
                    "Alpes",
                    "Mont-Blanc",
                    "Rütli",
                    "Gotthard",
                    "Saint-Maurice",
                    "Saint-Cergue",
                    "Sainte-Croix",
                    "La Chaux-de-Fonds",
                    "Le Locle",
                    "Les Paccots",
                    "Les Diablerets",
                    "Les Avants",
                    "Charmey"
                    },
                    "Rue de ",
                    "Chemin de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico",
                    "Claro",
                    "Arbedo",
                    "Giubiasco",
                    "Camorino",
                    "Sant'Antonino",
                    "Cadenazzo",
                    "Gambarogno",
                    "Tenero",
                    "Brissago",
                    "Ronco",
                    "Losone",
                    "Intragna",
                    "Centovalli",
                    "Onsernone",
                    "Vallemaggia",
                    "Maggia",
                    "Verzasca",
                    "Leventina",
                    "Blenio",
                    "Malcantone",
                    "Vedeggio",
                    "Cassarate",
                    "Ceresio",
                    "Verbano",
                    "Ticino",
                    "San Gottardo",
                    "Monte Brè",
                    "Monte San Salvatore",
                    "Monte Generoso",
                    "Monte Tamaro",
                    "Pizzo di Claro",
                    "Lema",
                    "Lucomagno",
                    "Nufenen",
                    "Alpe",
                    "Grotto",
                    "Riviera",
                    "Confederazione",
                    "Elvezia"
                    },
                    "Via ",
                    "Strada "
                ),
                BuildGermanSwissNames(
                    new[]
                    {
                    "Gotthard",
                    "Rütli",
                    "Säntis",
                    "Pilatus",
                    "Rigi",
                    "Mythen",
                    "Titlis",
                    "Eiger",
                    "Mönch",
                    "Jungfrau",
                    "Matterhorn",
                    "Dufour",
                    "Monte Rosa",
                    "Pizol",
                    "Tödi",
                    "Glärnisch",
                    "Stockhorn",
                    "Niesen",
                    "Gantrisch",
                    "Weissenstein",
                    "Napf",
                    "Bachtel",
                    "Uetliberg",
                    "Pfannenstiel",
                    "Lägern",
                    "Wildstrubel",
                    "Gemmi",
                    "Klausen",
                    "Furka",
                    "Grimsel",
                    "Susten",
                    "Oberalp",
                    "Julier",
                    "Bernina",
                    "Albula",
                    "Flüela",
                    "San Bernardino",
                    "Lukmanier",
                    "Aare",
                    "Limmat",
                    "Reuss",
                    "Rhein",
                    "Thur",
                    "Linth",
                    "Sihl",
                    "Emme",
                    "Töss",
                    "Vierwaldstättersee",
                    "Zürichsee",
                    "Walensee",
                    "Bodensee",
                    "Thunersee",
                    "Brienzersee",
                    "Zugersee",
                    "Sempachersee",
                    "Hallwilersee",
                    "Murtensee",
                    "Helvetia",
                    "Eidgenossen",
                    "Tell",
                    "Alpen",
                    "Engadin",
                    "Prättigau",
                    "Toggenburg",
                    "Emmental",
                    "Entlebuch",
                    "Seeland",
                    "Rheintal",
                    "Limmattal",
                    "Aaretal",
                    "Reusstal",
                    "Appenzell",
                    "Uri",
                    "Schwyz",
                    "Glarus",
                    "Graubünden",
                    "Wallis"
                    },
                    "strasse",
                    "weg"
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Sils",
                    "Pontresina",
                    "Celerina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Sent",
                    "Guarda",
                    "Ardez",
                    "Zernez",
                    "Lavin",
                    "Susch",
                    "Ftan",
                    "Tarasp",
                    "Müstair",
                    "Sta. Maria",
                    "Fuldera",
                    "Tschierv",
                    "Valchava",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Trun",
                    "Flims",
                    "Laax",
                    "Falera",
                    "Vals",
                    "Vrin",
                    "Lumnezia",
                    "Safien",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Filisur",
                    "Savognin",
                    "Bivio",
                    "Thusis",
                    "Domleschg",
                    "Heinzenberg",
                    "Calanda",
                    "Ruinaulta",
                    "Inn",
                    "En",
                    "Rom",
                    "Rein",
                    "Lai",
                    "God",
                    "Alp",
                    "Val",
                    "Crasta",
                    "Prasüras",
                    "Salastrains",
                    "Suvretta",
                    "Somplaz",
                    "Serlas",
                    "Tinus",
                    "Chavallera",
                    "Brattas",
                    "Chasellas"
                    },
                    "Via ",
                    "Via da "
                )
            );

        internal static readonly string[] StandardNames =
            Merge(
                new[]
                {
                    "Bahnhofstrasse",
                    "Rämistrasse",
                    "Limmatquai",
                    "Utoquai",
                    "Mythenquai",
                    "Dufourstrasse",
                    "Gotthardstrasse",
                    "Pilatusstrasse",
                    "Bundesgasse",
                    "Thunstrasse",
                    "Murtenstrasse",
                    "Rue du Rhône",
                    "Rue de Lausanne",
                    "Rue de Genève",
                    "Rue du Mont-Blanc",
                    "Quai du Mont-Blanc",
                    "Boulevard Georges-Favon",
                    "Avenue de Champel",
                    "Route de Chêne",
                    "Avenue d'Ouchy",
                    "Route de Berne",
                    "Route de Fribourg",
                    "Via Nassa",
                    "Via Cantonale",
                    "Via San Gottardo",
                    "Via Giuseppe Motta",
                    "Via G.B. Pioda",
                    "Via Giacomo e Filippo Ciani",
                    "Viale Carlo Cattaneo",
                    "Riva Vincenzo Vela",
                    "Via Monte Boglia",
                    "Via Trevano",
                    "Via Cassarate",
                    "Via Maistra",
                    "Via dal Bagn",
                    "Via Suvretta",
                    "Via Alpina",
                    "Via Salastrains"
                },
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse",
                    "Dent Blanche",
                    "Dents du Midi",
                    "Mont Fort",
                    "Grand Combin",
                    "Simplon",
                    "Grand-Saint-Bernard",
                    "Jaman",
                    "Moléson",
                    "Chasseral",
                    "Creux du Van",
                    "Rochers-de-Naye",
                    "Diablerets",
                    "Verbier",
                    "Crans",
                    "Montana",
                    "Zinal",
                    "Grimentz",
                    "Saas",
                    "Zermatt",
                    "Riviera",
                    "La Côte",
                    "Trois-Lacs",
                    "Helvétie",
                    "Confédération",
                    "Alpes",
                    "Mont-Blanc",
                    "Rütli",
                    "Gotthard",
                    "Saint-Maurice",
                    "Saint-Cergue",
                    "Sainte-Croix",
                    "La Chaux-de-Fonds",
                    "Le Locle",
                    "Les Paccots",
                    "Les Diablerets",
                    "Les Avants",
                    "Charmey"
                    },
                    "Rue de ",
                    "Route de ",
                    "Avenue de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico",
                    "Claro",
                    "Arbedo",
                    "Giubiasco",
                    "Camorino",
                    "Sant'Antonino",
                    "Cadenazzo",
                    "Gambarogno",
                    "Tenero",
                    "Brissago",
                    "Ronco",
                    "Losone",
                    "Intragna",
                    "Centovalli",
                    "Onsernone",
                    "Vallemaggia",
                    "Maggia",
                    "Verzasca",
                    "Leventina",
                    "Blenio",
                    "Malcantone",
                    "Vedeggio",
                    "Cassarate",
                    "Ceresio",
                    "Verbano",
                    "Ticino",
                    "San Gottardo",
                    "Monte Brè",
                    "Monte San Salvatore",
                    "Monte Generoso",
                    "Monte Tamaro",
                    "Pizzo di Claro",
                    "Lema",
                    "Lucomagno",
                    "Nufenen",
                    "Alpe",
                    "Grotto",
                    "Riviera",
                    "Confederazione",
                    "Elvezia"
                    },
                    "Via ",
                    "Viale ",
                    "Strada "
                ),
                BuildGermanSwissNames(
                    new[]
                    {
                    "Gotthard",
                    "Rütli",
                    "Säntis",
                    "Pilatus",
                    "Rigi",
                    "Mythen",
                    "Titlis",
                    "Eiger",
                    "Mönch",
                    "Jungfrau",
                    "Matterhorn",
                    "Dufour",
                    "Monte Rosa",
                    "Pizol",
                    "Tödi",
                    "Glärnisch",
                    "Stockhorn",
                    "Niesen",
                    "Gantrisch",
                    "Weissenstein",
                    "Napf",
                    "Bachtel",
                    "Uetliberg",
                    "Pfannenstiel",
                    "Lägern",
                    "Wildstrubel",
                    "Gemmi",
                    "Klausen",
                    "Furka",
                    "Grimsel",
                    "Susten",
                    "Oberalp",
                    "Julier",
                    "Bernina",
                    "Albula",
                    "Flüela",
                    "San Bernardino",
                    "Lukmanier",
                    "Aare",
                    "Limmat",
                    "Reuss",
                    "Rhein",
                    "Thur",
                    "Linth",
                    "Sihl",
                    "Emme",
                    "Töss",
                    "Vierwaldstättersee",
                    "Zürichsee",
                    "Walensee",
                    "Bodensee",
                    "Thunersee",
                    "Brienzersee",
                    "Zugersee",
                    "Sempachersee",
                    "Hallwilersee",
                    "Murtensee",
                    "Helvetia",
                    "Eidgenossen",
                    "Tell",
                    "Alpen",
                    "Engadin",
                    "Prättigau",
                    "Toggenburg",
                    "Emmental",
                    "Entlebuch",
                    "Seeland",
                    "Rheintal",
                    "Limmattal",
                    "Aaretal",
                    "Reusstal",
                    "Appenzell",
                    "Uri",
                    "Schwyz",
                    "Glarus",
                    "Graubünden",
                    "Wallis"
                    },
                    "strasse"
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Sils",
                    "Pontresina",
                    "Celerina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Sent",
                    "Guarda",
                    "Ardez",
                    "Zernez",
                    "Lavin",
                    "Susch",
                    "Ftan",
                    "Tarasp",
                    "Müstair",
                    "Sta. Maria",
                    "Fuldera",
                    "Tschierv",
                    "Valchava",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Trun",
                    "Flims",
                    "Laax",
                    "Falera",
                    "Vals",
                    "Vrin",
                    "Lumnezia",
                    "Safien",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Filisur",
                    "Savognin",
                    "Bivio",
                    "Thusis",
                    "Domleschg",
                    "Heinzenberg",
                    "Calanda",
                    "Ruinaulta",
                    "Inn",
                    "En",
                    "Rom",
                    "Rein",
                    "Lai",
                    "God",
                    "Alp",
                    "Val",
                    "Crasta",
                    "Prasüras",
                    "Salastrains",
                    "Suvretta",
                    "Somplaz",
                    "Serlas",
                    "Tinus",
                    "Chavallera",
                    "Brattas",
                    "Chasellas"
                    },
                    "Via ",
                    "Via da "
                ),
                BuildPersonNames(
                    new[]
                    {
                    "Henri Dunant",
                    "Guillaume-Henri Dufour",
                    "Johanna Spyri",
                    "Ferdinand Hodler",
                    "Paul Klee",
                    "Max Frisch",
                    "Friedrich Dürrenmatt",
                    "Alberto Giacometti",
                    "Sophie Taeuber-Arp",
                    "Jean Tinguely",
                    "Le Corbusier",
                    "Carl Gustav Jung",
                    "Leonhard Euler",
                    "Daniel Bernoulli",
                    "Jakob Bernoulli",
                    "Auguste Piccard",
                    "Bertrand Piccard",
                    "Alfred Escher",
                    "Nicolas Hayek",
                    "General Guisan",
                    "Niklaus von Flüe",
                    "Huldrych Zwingli",
                    "Heinrich Pestalozzi",
                    "Gottfried Keller",
                    "Conrad Ferdinand Meyer",
                    "Robert Walser",
                    "Jeremias Gotthelf",
                    "Hermann Hesse",
                    "Paracelsus",
                    "Jean-Jacques Rousseau",
                    "Charles-Ferdinand Ramuz",
                    "Blaise Cendrars",
                    "Ella Maillart",
                    "Alice Rivaz",
                    "Agota Kristof",
                    "Corinna Bille",
                    "Meret Oppenheim",
                    "Angelika Kauffmann",
                    "Arthur Honegger",
                    "Ernest Ansermet",
                    "Frank Martin",
                    "Othmar Schoeck",
                    "Clara Haskil",
                    "Alfred Cortot",
                    "Hermann Rorschach",
                    "Emil Theodor Kocher",
                    "Albert Hofmann",
                    "Louis Agassiz",
                    "Horace-Bénédict de Saussure",
                    "Conrad Gessner",
                    "Jean Piaget",
                    "Albert Einstein",
                    "Emil Frey",
                    "Stefano Franscini",
                    "Alfredo Pioda",
                    "Vincenzo Vela",
                    "Carlo Cattaneo",
                    "Giuseppe Motta",
                    "Giacomo Ciani",
                    "Filippo Ciani",
                    "Frans Masereel",
                    "Roger Federer",
                    "Martina Hingis",
                    "Vreni Schneider",
                    "Pirmin Zurbriggen",
                    "Bernhard Russi",
                    "Didier Cuche",
                    "Simon Ammann",
                    "Dario Cologna",
                    "Nino Schurter",
                    "Segantini",
                    "Giovanni Giacometti",
                    "Augusto Giacometti",
                    "Hans Erni",
                    "Mario Botta",
                    "Peter Zumthor"
                    }
                )
            );

        internal static readonly string[] AvenueNames =
            Merge(
                new[]
                {
                    "Limmatquai",
                    "General-Guisan-Quai",
                    "Mythenquai",
                    "Utoquai",
                    "Quai du Mont-Blanc",
                    "Quai Wilson",
                    "Quai Gustave-Ador",
                    "Avenue de la Gare",
                    "Avenue d'Ouchy",
                    "Avenue de Champel",
                    "Boulevard Georges-Favon",
                    "Avenue du Léman",
                    "Riva Vincenzo Vela",
                    "Riva Albertolli",
                    "Viale Carlo Cattaneo",
                    "Viale Giuseppe Cattori",
                    "Lungolago"
                },
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Gland",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Onex",
                    "Vernier",
                    "Chêne",
                    "Champel",
                    "Servette",
                    "Ouchy",
                    "Vidy",
                    "Lavaux",
                    "Chablais",
                    "Valais",
                    "Jura",
                    "Léman",
                    "Sarine",
                    "Rhône",
                    "Arve",
                    "Orbe",
                    "Broye",
                    "Doubs",
                    "Venoge",
                    "Dranse",
                    "Dent Blanche",
                    "Dents du Midi",
                    "Mont Fort",
                    "Grand Combin",
                    "Simplon",
                    "Grand-Saint-Bernard",
                    "Jaman",
                    "Moléson",
                    "Chasseral",
                    "Creux du Van",
                    "Rochers-de-Naye",
                    "Diablerets",
                    "Verbier",
                    "Crans",
                    "Montana",
                    "Zinal",
                    "Grimentz",
                    "Saas",
                    "Zermatt",
                    "Riviera",
                    "La Côte",
                    "Trois-Lacs",
                    "Helvétie",
                    "Confédération",
                    "Alpes",
                    "Mont-Blanc",
                    "Rütli",
                    "Gotthard",
                    "Saint-Maurice",
                    "Saint-Cergue",
                    "Sainte-Croix",
                    "La Chaux-de-Fonds",
                    "Le Locle",
                    "Les Paccots",
                    "Les Diablerets",
                    "Les Avants",
                    "Charmey"
                    },
                    "Avenue de ",
                    "Boulevard de ",
                    "Quai de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Minusio",
                    "Muralto",
                    "Massagno",
                    "Paradiso",
                    "Pregassona",
                    "Viganello",
                    "Cassarate",
                    "Castagnola",
                    "Canobbio",
                    "Comano",
                    "Porza",
                    "Savosa",
                    "Sorengo",
                    "Agno",
                    "Bioggio",
                    "Manno",
                    "Lamone",
                    "Taverne",
                    "Rivera",
                    "Monteceneri",
                    "Capriasca",
                    "Tesserete",
                    "Sonvico",
                    "Gandria",
                    "Melide",
                    "Morcote",
                    "Carona",
                    "Figino",
                    "Barbengo",
                    "Collina d'Oro",
                    "Magliaso",
                    "Caslano",
                    "Ponte Tresa",
                    "Novaggio",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Bodio",
                    "Giornico",
                    "Claro",
                    "Arbedo",
                    "Giubiasco",
                    "Camorino",
                    "Sant'Antonino",
                    "Cadenazzo",
                    "Gambarogno",
                    "Tenero",
                    "Brissago",
                    "Ronco",
                    "Losone",
                    "Intragna",
                    "Centovalli",
                    "Onsernone",
                    "Vallemaggia",
                    "Maggia",
                    "Verzasca",
                    "Leventina",
                    "Blenio",
                    "Malcantone",
                    "Vedeggio",
                    "Cassarate",
                    "Ceresio",
                    "Verbano",
                    "Ticino",
                    "San Gottardo",
                    "Monte Brè",
                    "Monte San Salvatore",
                    "Monte Generoso",
                    "Monte Tamaro",
                    "Pizzo di Claro",
                    "Lema",
                    "Lucomagno",
                    "Nufenen",
                    "Alpe",
                    "Grotto",
                    "Riviera",
                    "Confederazione",
                    "Elvezia"
                    },
                    "Viale ",
                    "Riva ",
                    "Lungolago "
                ),
                BuildGermanSwissNames(
                    new[]
                    {
                    "Gotthard",
                    "Rütli",
                    "Säntis",
                    "Pilatus",
                    "Rigi",
                    "Mythen",
                    "Titlis",
                    "Eiger",
                    "Mönch",
                    "Jungfrau",
                    "Matterhorn",
                    "Dufour",
                    "Monte Rosa",
                    "Pizol",
                    "Tödi",
                    "Glärnisch",
                    "Stockhorn",
                    "Niesen",
                    "Gantrisch",
                    "Weissenstein",
                    "Napf",
                    "Bachtel",
                    "Uetliberg",
                    "Pfannenstiel",
                    "Lägern",
                    "Wildstrubel",
                    "Gemmi",
                    "Klausen",
                    "Furka",
                    "Grimsel",
                    "Susten",
                    "Oberalp",
                    "Julier",
                    "Bernina",
                    "Albula",
                    "Flüela",
                    "San Bernardino",
                    "Lukmanier",
                    "Aare",
                    "Limmat",
                    "Reuss",
                    "Rhein",
                    "Thur",
                    "Linth",
                    "Sihl"
                    },
                    "quai"
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Sils",
                    "Pontresina",
                    "Celerina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Sent",
                    "Guarda",
                    "Ardez",
                    "Zernez",
                    "Lavin",
                    "Susch",
                    "Ftan",
                    "Tarasp",
                    "Müstair",
                    "Sta. Maria",
                    "Fuldera",
                    "Tschierv",
                    "Valchava",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Trun",
                    "Flims",
                    "Laax",
                    "Falera",
                    "Vals",
                    "Vrin",
                    "Lumnezia",
                    "Safien",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Filisur",
                    "Savognin"
                    },
                    "Via ",
                    "Viale "
                )
            );

        internal static readonly string[] HighwayRouteNames =
            Merge(
                new[]
                {
                "A1",
                "A2",
                "A3",
                "A4",
                "A5",
                "A6",
                "A7",
                "A8",
                "A9",
                "A12",
                "A13",
                "A14",
                "A15",
                "A16",
                "A18",
                "A20",
                "A22",
                "A23",
                "A25",
                "A28",
                "A50",
                "A51",
                "A52",
                "A53",
                "Hauptstrasse 2a",
                "Hauptstrasse 2b",
                "Route du Simplon",
                "Route du Grand-Saint-Bernard",
                "Route du Jura",
                "Route du Léman",
                "Route des Alpes",
                "Autostrada del San Gottardo",
                "Autostrada del San Bernardino",
                "Strada del Lucomagno",
                "Strada della Novena",
                "Gotthardroute",
                "San-Bernardino-Route",
                "Simplonroute",
                "Julierroute",
                "Berninaroute"
                },
                BuildNumberedRoutes(
                    "Hauptstrasse ",
                    1,
                    30
                ),
                BuildNumberedRoutes(
                    "Route principale ",
                    1,
                    30
                ),
                BuildNumberedRoutes(
                    "Strada principale ",
                    1,
                    30
                ),
                BuildNumberedRoutes(
                    "Via principala ",
                    1,
                    30
                ),
                BuildFrenchPlaces(
                    new[]
                    {
                    "Genève",
                    "Lausanne",
                    "Montreux",
                    "Vevey",
                    "Nyon",
                    "Morges",
                    "Fribourg",
                    "Neuchâtel",
                    "Sion",
                    "Martigny",
                    "Delémont",
                    "Porrentruy",
                    "Bienne",
                    "Yverdon",
                    "Avenches",
                    "Morat",
                    "Gruyères",
                    "Bulle",
                    "Romont",
                    "Estavayer",
                    "Rolle",
                    "Meyrin",
                    "Carouge",
                    "Versoix",
                    "Vernier",
                    "Le Lavaux",
                    "Le Chablais",
                    "Le Valais",
                    "Le Jura",
                    "Le Léman",
                    "Le Rhône",
                    "Sarine",
                    "Le Grand-Saint-Bernard",
                    "Le Simplon",
                    "Saint-Maurice",
                    "Saint-Cergue",
                    "Sainte-Croix",
                    "La Chaux-de-Fonds",
                    "Le Locle",
                    "Riviera",
                    "La Côte",
                    "Trois-Lacs",
                    "Les Alpes"
                    },
                    "Route de "
                ),
                BuildItalianPlaces(
                    new[]
                    {
                    "Lugano",
                    "Locarno",
                    "Bellinzona",
                    "Mendrisio",
                    "Chiasso",
                    "Ascona",
                    "Airolo",
                    "Faido",
                    "Biasca",
                    "Giornico",
                    "Giubiasco",
                    "Cadenazzo",
                    "Gambarogno",
                    "Tenero",
                    "Brissago",
                    "Centovalli",
                    "Vallemaggia",
                    "Verzasca",
                    "Leventina",
                    "Blenio",
                    "Malcantone",
                    "Vedeggio",
                    "Ceresio",
                    "Verbano",
                    "Ticino",
                    "San Gottardo",
                    "San Bernardino",
                    "Lucomagno",
                    "Nufenen",
                    "Monte Ceneri",
                    "Monte Brè",
                    "Monte San Salvatore"
                    },
                    "Strada di "
                ),
                BuildGermanSwissNames(
                    new[]
                    {
                    "Gotthard",
                    "Rütli",
                    "Säntis",
                    "Pilatus",
                    "Rigi",
                    "Mythen",
                    "Titlis",
                    "Eiger",
                    "Jungfrau",
                    "Matterhorn",
                    "Dufour",
                    "Pizol",
                    "Tödi",
                    "Stockhorn",
                    "Niesen",
                    "Gantrisch",
                    "Weissenstein",
                    "Napf",
                    "Uetliberg",
                    "Wildstrubel",
                    "Gemmi",
                    "Klausen",
                    "Furka",
                    "Grimsel",
                    "Susten",
                    "Oberalp",
                    "Julier",
                    "Bernina",
                    "Albula",
                    "Flüela",
                    "San Bernardino",
                    "Lukmanier",
                    "Engadin",
                    "Prättigau",
                    "Toggenburg",
                    "Emmental",
                    "Entlebuch",
                    "Seeland",
                    "Rheintal",
                    "Limmattal",
                    "Aaretal",
                    "Reusstal",
                    "Appenzell",
                    "Uri",
                    "Schwyz",
                    "Glarus",
                    "Graubünden",
                    "Wallis"
                    },
                    "route"
                ),
                BuildRomanshPlaces(
                    new[]
                    {
                    "Engiadina",
                    "Surselva",
                    "Val Müstair",
                    "Albula",
                    "Bernina",
                    "Maloja",
                    "Flüela",
                    "Julier",
                    "Silvaplana",
                    "Pontresina",
                    "Samedan",
                    "Zuoz",
                    "Scuol",
                    "Zernez",
                    "Müstair",
                    "Ilanz",
                    "Disentis",
                    "Sedrun",
                    "Flims",
                    "Laax",
                    "Vals",
                    "Arosa",
                    "Davos",
                    "Lenzerheide",
                    "Bergün",
                    "Savognin",
                    "Thusis",
                    "Domleschg",
                    "Ruinaulta",
                    "Inn"
                    },
                    "Via principala da "
                )
            );

        private static string[] BuildFrenchPlaces(
            string[] places,
            params string[] prefixes)
        {
            List<string> names = new();

            foreach (string place in places)
            {
                foreach (string prefix in prefixes)
                {
                    names.Add(
                        ApplyFrenchPlacePrefix(
                            prefix,
                            place
                        )
                    );
                }
            }

            return names.ToArray();
        }

        private static string ApplyFrenchPlacePrefix(
            string prefix,
            string place)
        {
            if (!prefix.EndsWith(
                    "de ",
                    StringComparison.Ordinal))
            {
                return prefix + place;
            }

            string basePrefix =
                prefix.Substring(
                    0,
                    prefix.Length - 3
                );

            if (place.StartsWith(
                    "Le ",
                    StringComparison.Ordinal))
            {
                return
                    basePrefix +
                    "du " +
                    place.Substring(3);
            }

            if (place.StartsWith(
                    "La ",
                    StringComparison.Ordinal))
            {
                return
                    basePrefix +
                    "de la " +
                    place.Substring(3);
            }

            if (place.StartsWith(
                    "Les ",
                    StringComparison.Ordinal))
            {
                return
                    basePrefix +
                    "des " +
                    place.Substring(4);
            }

            if (place.StartsWith(
                    "L'",
                    StringComparison.Ordinal))
            {
                return
                    basePrefix +
                    "de l'" +
                    place.Substring(2);
            }

            if (StartsWithFrenchVowel(place))
            {
                return
                    basePrefix +
                    "d'" +
                    place;
            }

            return
                basePrefix +
                "de " +
                place;
        }

        private static bool StartsWithFrenchVowel(
            string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                return false;
            }

            char first =
                char.ToUpperInvariant(value[0]);

            return
                first == 'A' ||
                first == 'E' ||
                first == 'I' ||
                first == 'O' ||
                first == 'U' ||
                first == 'Y';
        }

        private static string[] BuildItalianPlaces(
            string[] places,
            params string[] prefixes)
        {
            List<string> names = new();

            foreach (string place in places)
            {
                foreach (string prefix in prefixes)
                {
                    names.Add(prefix + place);
                }
            }

            return names.ToArray();
        }

        private static string[] BuildGermanSwissNames(
            string[] roots,
            params string[] suffixes)
        {
            List<string> names = new();

            foreach (string root in roots)
            {
                string compactRoot =
                    root.Replace(" ", string.Empty)
                        .Replace("-", string.Empty);

                foreach (string suffix in suffixes)
                {
                    names.Add(compactRoot + suffix);
                }
            }

            return names.ToArray();
        }

        private static string[] BuildRomanshPlaces(
            string[] places,
            params string[] prefixes)
        {
            List<string> names = new();

            foreach (string place in places)
            {
                foreach (string prefix in prefixes)
                {
                    names.Add(prefix + place);
                }
            }

            return names.ToArray();
        }

        private static string[] BuildPersonNames(string[] people)
        {
            List<string> names = new();

            foreach (string person in people)
            {
                names.Add("Rue " + person);
                names.Add("Via " + person);
                names.Add(
                    person.Replace(" ", "-") +
                    "-Strasse"
                );
            }

            return names.ToArray();
        }

        private static string[] BuildNumberedRoutes(
            string prefix,
            int firstNumber,
            int lastNumber)
        {
            List<string> names = new();

            for (int number = firstNumber;
                 number <= lastNumber;
                 number++)
            {
                names.Add(
                    prefix +
                    number
                );
            }

            return names.ToArray();
        }

        private static string[] Merge(
            params string[][] groups)
        {
            HashSet<string> uniqueNames =
                new(StringComparer.OrdinalIgnoreCase);

            List<string> names = new();

            foreach (string[] group in groups)
            {
                foreach (string name in group)
                {
                    if (string.IsNullOrWhiteSpace(name))
                    {
                        continue;
                    }

                    string trimmedName = name.Trim();

                    if (uniqueNames.Add(trimmedName))
                    {
                        names.Add(trimmedName);
                    }
                }
            }

            return names.ToArray();
        }
    }
}
